### ISSUE TITLE
Replace file pulling filename from another file

### ISSUE THREAD

**Issue by rawbitt** [silverstripe/silverstripe-asset-admin#1008]
## Affected Version

SilverStripe CMS 4.3.4
Fixed in SilverStripe 4.4

## Description

Using the `Replace file` feature in the File section of the CMS, sometimes the Filename field will get replaced with another file name (even one that you may not have viewed in this session).

I was unable to recreate this in 4.4.X (albeit, it may still be happening)

## Steps to Reproduce

1. Click some existing files (so, at least 2-3 files already uploaded in the Files section).
2. Upload a new file to the CMS (example.pdf)
3. Click the ellipsis on your new `example.pdf` and click `Replace file`. Select a file to replace (could even be the same as the original) and you should see the Filename field get replaced with something else.

**Comment by maxime-rainville** [comment]
I just had a look and manage to replicate the problem in 4.3, but not in 4.4. We did a big refactoring of how asset works in 4.4. We might have fix this inadvertently.

To be honest, if it's a 4.3 only issue, it's unlikely we'll get around to fixing it.

**Comment by rawbitt** [comment]
> We did a big refactoring of how asset works in 4.4. We might have fix this inadvertently.

Our team also wondered if it might be the newer version of React that comes with 4.4 - in any case, it does look to only be a client-side issue.

**Comment by brynwhyman** [comment]
Given the amount of work that went into assets for 4.4, agree that it's unlikely that it would be worth backporting an (inadvertent) fix. That does however mean that we're watching assets in 4.4 very closely for new issues that may pop up. 

@NightJar suggested writing some tests to cover this scenario and avoid future regressions. Could that be a sufficient stop gap here?

**Comment by michalkleiner** [comment]
Close then?

**Comment by maxime-rainville** [comment]
Yeah ... I don't think we'll get to this.
