### ISSUE TITLE
"File is too big" despite setting the allowed size

### ISSUE THREAD

**Issue by spekulatius** [silverstripe/silverstripe-asset-admin#1024]
Hello,

I'm running a site using assets admin 1.2.1. On upload get this error:

![image](https://user-images.githubusercontent.com/8433587/66952860-b624ca80-f05d-11e9-9a63-de272387f061.png)

This happens instantly without any requests to the backend - so I assume it's a JavaScript validation. I guess it's failing because the allowed size isn't handed to the frontend of the CMS or processed there.

On the server PHP is configured with 'upload_max_filesize' as '10M' and 'post_max_size' to '16M'. In SilverStripe the limits are set to:

    SilverStripe\Assets\Upload_Validator:
      default_max_file_size:
        '[image]': '2M'
        '[document]': '2M'

So my assumption is that 2 MB image uploads should work. The files in questions are images (jpegs) and under 2 MB. I feel like I'm missing something obvious. Maybe someone could point me to it?

Cheers,
Peter

**Comment by dnsl48** [comment]
Hi @spekulatius, thank you for reporting the issue!

Could you try to update to 1.3 or 1.4? The version 1.2 has reached [EOL](https://forum.silverstripe.org/t/eol-for-4-2-is-31-06-2019/1427) about 3 months ago. The issue might have been fixed in the newer releases.

**Comment by spekulatius** [comment]
Hello @dnsl48 

fair call. It's quite a bit dated. I'll check if upgrading helps and report back.

Peter

**Comment by spekulatius** [comment]
I can confirm upgrading to 1.4.4 resolved the issue. Thanks for reminding me @dnsl48!
