### ISSUE TITLE
Recently uploaded files appear in parent folders

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-asset-admin#1025]
## Overview
There appears to be a bug where after uploading a file and subsequently navigating through different folders, the recently uploaded file will appear in each folder you navigate to.

If you're uploading a file to a specific folder, you want to be sure that it's been saved in the correct place. This bug is confusing and doesn't instil confidence that the file has been saved correctly.

## Steps to reproduce
1. Navigate to Files area
2. Create a new folder and navigate to it
3. Upload a new file
4. Identify that the file is displayed in the window
5. Bug: Navigate to the parent folder and see that the file appears here too. Navigate to other folders and see that the file persists in view.

### Expected result
5. Navigate to the parent folder (or any other) and you should not see the file that was recently uploaded.

## Acceptance criteria
* The issue is covered by some behat test
* The solution does not significantly degrade performance

## Versions affected
`silverstripe/asset-admin 1.4.x-dev 35f64e5`
`silverstripe/assets 1.4.x-dev dc8bebb`

# Pull request
* [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/1118

**Comment by bergice** [comment]
This is still an issue on `1.4.x-dev` and also `4.5`.

Additionally, the newly created folder will disappear.

**Comment by jules0x** [comment]
If you click on the file, in the place that you're not expecting to see it... it navigates your back to the place it was actually uploaded.

**Comment by rafaeldsousa** [comment]
I can reproduce issues above mentioned in `1.4.4` SS `4.4.4`.
