### ISSUE TITLE
Appending file version id to image url breaks Protected Asset previews with SilverStripe-S3

### ISSUE THREAD

**Issue by obj63mc** [silverstripe/silverstripe-asset-admin#1026]
Silverstripe version 4.3+

Currently when an asset is rendered via the cms it appends ?vid=X to the end of the image url.

When you utilize the silverstripe-s3 module this append version to the signed url causes the image to not render.

Exmaple of line that causes the issue - https://github.com/silverstripe/silverstripe-asset-admin/blob/e0f919d3c6a6b0415ae06c9e91da5bf37da99672/client/src/components/PreviewImageField/PreviewImageField.js#L265

This is related to issue https://github.com/silverstripe/silverstripe-s3/issues/33
This also appears to affect UploadFields in the CMS as well (really anywhere assets are rendered that are 'protected' assets).  Looks like https://github.com/silverstripe/silverstripe-asset-admin/commit/52ae679d1d246b5e935efd8e449eb9a95f2c9703 introduced this issue.

# Pull requests
* ~https://github.com/silverstripe/silverstripe-asset-admin/pull/1039~
* [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1040
* [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1119
* [ ] https://github.com/silverstripe/silverstripe-s3/pull/43

**Comment by obj63mc** [comment]
One possible quick solution for this would be to check if a querystring exists on the url, if it does don't append the version id.

**Comment by maxime-rainville** [comment]
This problem is sort of related to https://github.com/silverstripe/silverstripe-versioned-admin/issues/134 in that if we were using a sensible library to generate our URLs we would avoid this kind of errors.

**Comment by maxime-rainville** [comment]
https://github.com/silverstripe/silverstripe-asset-admin/pull/1040 should fix it. It uses a smarter logic to build that URL that should be OK with pre-existing query param.

**Comment by emteknetnz** [comment]
The linked pull-request has been merged, I'll close this issue now

**Comment by maxime-rainville** [comment]
Looks like making the logic to generate URL better doesn't fix the S3 issue because adding the `vid` invalidates the S3 signature.

https://github.com/silverstripe/silverstripe-asset-admin/pull/1040#issuecomment-660741105

**Comment by maxime-rainville** [comment]
Just looking at the possible solution for this. Of the top of my head, we could try this:
- Move the cache busting logic server side. Basically, the asset store or a related class would need to add the `vid` parameter. The S3 module could then disable the cache busting logic which it wouldn't need any way because the aws signature parameter would do that any way
- Add some config settings to `PreviewImageField.php` that would allow third party module to disable cache busting. That would be pass as some extra config option in the form schema. The front-end `PreviewImageField` component would need to read this config flag and skip the cache busting logic.
- The `PreviewImageField` react component could be overridden with a custom Preview field. That preview field could be overridden with a custom implementation that doesn't try to add the vid parameter.

**Comment by maxime-rainville** [comment]
Did a PR that adds an option to disable the cache busting. https://github.com/silverstripe/silverstripe-asset-admin/pull/1119

You should be able to disable cache busting by adding this to your YML config.
```yml
SilverStripe\AssetAdmin\Forms\PreviewImageField:
  bust_cache: false
```

I don't have a site working with S3 locally. Could someone actually using the S3 asset store give it a go to make sure this fix the problem?

**Comment by obj63mc** [comment]
I'll try to pull this down this morning and see how it works out. As a note this is really only an issue with Protected/Draft assets as only those are signed. Once published and not protected the asset no longer needs to be signed to access it and is public to anyone. So not sure if there is an easy way to only target just those assets with this configuration.

**Comment by obj63mc** [comment]
So not sure the best way to pull down the updated code but ended up pulling down the zip file from the forked repo.  When testing the preview on the right side works fine, but the left side thumbnails is still injecting the VID onto the url request.

Screen shot attached for reference.
![Screen Shot 2020-07-21 at 8 23 46 AM](https://user-images.githubusercontent.com/443120/88060402-cfe2c900-cb2b-11ea-9e37-d45dac79849f.png)

**Comment by maxime-rainville** [comment]
Just had another look. I've move the config hook to asset-admin so they would apply to both GalleryItem and PreviewImageField.

**Comment by thats4shaw** [comment]
@maxime-rainville I'm just been trying to get S3 working today and stumbled across this thread.  Your PR seems to resolve the issue with the following config:

```
SilverStripe\AssetAdmin\Controller\AssetAdmin:
  bust_cache: false
```

**Comment by maxime-rainville** [comment]
Just did one final PR to update the S3 module to disable cache busting by default. Once this last PR is merge we can probably close this issue.
