### ISSUE TITLE
Bug: Multi-File Upload - Upload Cancelled

### ISSUE THREAD

**Issue by jchenevey** [silverstripe/silverstripe-asset-admin#1030]
Affects SilverStripe 4.4.4.

Full composer list:

```
benmanu/silverstripe-simple-styleguide         2.0.5        Provides a kitchen sink template useful for theme development.
colymba/gridfield-bulk-editing-tools           3.0.0        SilverStripe GridField component to upload images/files and edit records ...
innis-maggiore/silverstripe-content-extensions 4.0          Content Extensions
innis-maggiore/silverstripe-smtp-tester        4.0          Silverstripe SMTP Tester allows developers to test their site's SMTP conf...
innis-maggiore/silverstripe-social-meta-tags   4.0.2        Adds social media meta tags to Silverstripe sites.
phpunit/phpunit                                5.7.27       The PHP Unit Testing framework.
silverstripe-themes/simple                     3.2.0        The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/blog                              3.4.0        A fresh take on blogging in Silverstripe set out to tackle the issue of a...
silverstripe/comment-notifications             2.0.1        Provides email notifications for visitor comments
silverstripe/comments                          3.2.1        This module provides commenting functionality for Pages and other DataObj...
silverstripe/recaptcha                         3.0.0-alpha1 Provides a form field which allows form to validate for non-bot submissio...
silverstripe/recipe-cms                        4.4.4        SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-plugin                     1.3.0        Helper plugin to install SilverStripe recipes
silverstripe/spamprotection                    3.0.1        Spam protection module for SilverStripe.
silverstripe/userforms                         5.4.1        UserForms enables CMS users to create dynamic forms via a drag and drop i...
silverstripe/vendor-plugin                     1.4.0        Allows vendor modules to expose directories to the webroot
silverstripe/versioned                         1.4.3        SilverStripe Versioned component
silverstripe/widgets                           2.0.2        Widgets are small pieces of functionality such as showing the latest Comm...
stripe/stripe-php                              v6.43.1      Stripe PHP Library
suin/php-rss-writer                            1.6.0        Yet another simple RSS writer library for PHP 5.4 or later.
symbiote/silverstripe-gridfieldextensions      3.2.1        A collection of useful grid field components
undefinedoffset/sortablegridfield              2.0.8        Adds drag and drop functionality to SilverStripe 4.x's GridField
webfox/silverstripe-blog-search                v2.2.0       A Silverstripe extension to add Blog Search functionality
wilr/silverstripe-googlesitemaps               2.1.5        SilverStripe support for the Google Sitemaps XML, enabling Google and oth...
```

--------------------------------------------------

When uploading multiple files in the admin area, the final file will show as "Upload cancelled."

![Screen Shot 2019-11-06 at 11 46 35 AM](https://user-images.githubusercontent.com/8449994/68322646-c09d1780-0091-11ea-9ac4-c68a3f5f12bd.png)

After reviewing the network tab in the browser's dev tools it appears the following is occurring:

- When uploading a group of files, a `createFile` request is created for each file
- Prior to the final `createFile` request completing, a UI refresh is triggered.
  - This seems to leave the final `createFile` request as "orphaned", as it will never update in the dev tools with a status, type, or response size, or with a response at all for that matter.
- When the UI refresh completes, the final file being uploaded will show the above "Upload cancelled." message.
- If you refresh the page in your browser, the image will appear, showing that the file upload _did_, in fact, complete in the background, even though the UI was not aware of the request completing due to the non-browser-reload UI refresh.

the network traffic from the browser's dev tools:

![Screen Shot 2019-11-06 at 12 05 49 PM](https://user-images.githubusercontent.com/8449994/68322964-6badd100-0092-11ea-91a1-6a83e9bffcce.png)

This issue was reproduced on 3 different sites running SilverStripe 4.4.4.

# PR's
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/1063

**Comment by ScopeyNZ** [comment]
Does appears to be a regression from 4.4.3?

**Comment by jchenevey** [comment]
The regression seems to have been introduced in 4.4.0.

**Comment by ScopeyNZ** [comment]
Thanks for testing all of that! That's really helpful

**Comment by brynwhyman** [comment]
Also seen in 4.5.alpha-1

**Comment by jp96201** [comment]
Anyone knows how to fix this bug?
