### ISSUE TITLE
Remove behat test that connects to youtube

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-asset-admin#1035]
tests/behat/features/insert-an-image.feature:40

Will make a connection to youtube.  Youtube has started responding with a 429 status code which means rate limited

Disable this test and switch to manually testing this functionality instead

**Comment by emteknetnz** [comment]
Pull request https://github.com/silverstripe/silverstripe-asset-admin/pull/1036

**Comment by brynwhyman** [comment]
Just a side note - interesting to see that production sites are getting limit rates too. The failing test is kind of helpful after all? https://github.com/silverstripe/silverstripe-framework/issues/9073#issuecomment-564732178

**Comment by robbieaverill** [comment]
Merged
