### ISSUE TITLE
Missing: Upload files into folders via drag/drop

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#104]
Can’t get to drag and drop page by clicking “Upload” button, it just pops up system folder to choose files to upload

![image](https://cloud.githubusercontent.com/assets/936064/14236423/9a17eb30-fa69-11e5-8c19-3b5bcb8c5140.png)

https://silverstripe.atlassian.net/browse/OSS-1438

## Related

 * [Move files via drag/drop](https://github.com/silverstripe/silverstripe-asset-admin/issues/216)
 * [Move files via folder location](https://github.com/silverstripe/silverstripe-asset-admin/issues/217)

**Comment by flashbackzoo** [comment]
You just drag files directly into the files area...

![drag](https://cloud.githubusercontent.com/assets/878176/14236461/6996da42-fa6a-11e5-820e-4d4bbd97c841.png)

**Comment by tractorcow** [comment]
I think it needs to be more obvious before you start dragging... you shouldn't need to know if an action is available before you try to invoke it.

**Comment by flashbackzoo** [comment]
@clarkepaul

**Comment by clarkepaul** [comment]
This hasn't been completely tested yet... for the users who are used to drag and drop interfaces they just expect them to work (mail, gdrive) they often don't include drop areas as people will normally try it to see if it works (drop into folders or between items in a list, just like on a PC). 

I would like to have an introduction to the files area, letting the user know drag and drop is available everywhere, then it doesn't need to have drop area visible all the time – for those that aren't used to drag drop "browse" is still available. If this plan doesn't work out through testing then we have a concept which makes the first item in the list a drop area. There will need to changes anyway when files can be dropped into folders (if prioritised) as this isn't currently possible with the full page overlay.

**Comment by sminnee** [comment]
Closing this issue - if we have more changes coming out of user testing we can raise issues for the changes needed.
