### ISSUE TITLE
Bulk files operation overlap on IE11

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-asset-admin#1044]
When selecting files in asset-admin in IE11, the list of file operations is mangled. All the possible operation appear to overlap.

![image](https://user-images.githubusercontent.com/1168676/72311063-60a59b80-36e8-11ea-8381-438dfb2a98e5.png)

# Pull requests
* [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1127

**Comment by maxime-rainville** [comment]
Confirmed on SS4.4 and 4.6.x.

**Comment by GuySartorelli** [comment]
This also affects the "Insert" button when selecting an image from the "Choose existing" option from an upload field. It seems to be an issue with IE11's implementation of flex. I have found that changing
```css
.bulk-actions > * {
  flex: 0;
}
```
to
```css
.bulk-actions > * {
  flex: none;
}
```
resolves the issue, and I haven't yet seen any negative side effects on any browser.

**Comment by maxime-rainville** [comment]
@GuySartorelli 's solution seems to work pretty well. I've got a PR for it. https://github.com/silverstripe/silverstripe-asset-admin/pull/1127

**Comment by emteknetnz** [comment]
The linked PR has been merged and merged-up, closing now
