### ISSUE TITLE
default image size ($insert_width)

### ISSUE THREAD

**Issue by Blueace** [silverstripe/silverstripe-asset-admin#1047]
Hi there,

On SS 4.5, and after reading #1015 I was expecting to see the value I set in app/_config/app.yml 
 like this 
`SilverStripe\AssetAdmin\Controller\AssetAdminFile:
  insert_width: 800`
But default width is always 600.

Am I wrong ?

**Comment by maxime-rainville** [comment]
#1015 fixes the issue for SS4.3 and SS4.4. However, in SS4.5 we added a slightly smarter way to define default image size that allows you to define image size presets.

You can [read more about image size preset on the Silverstripe CMS doc site](https://docs.silverstripe.org/en/4/developer_guides/forms/field_types/htmleditorfield/#image-size-pre-sets).

I don't think this is an actual issue we can address, so I will close it. But if you have follow up concerns, please feel free to comment and I'll reopen.
