### ISSUE TITLE
ShowInSearch checkbox missing from File form Fields

### ISSUE THREAD

**Issue by Leapfrognz** [silverstripe/silverstripe-asset-admin#1048]
ShowInSearch exists as a db field on Files. However there is no interface to edit this via the CMS.

silverstripe/asset-admin 1.4.2

**Comment by maxime-rainville** [comment]
I'm not sure how helpful this would be. If you're implementing File search, not having that value exposed and editable is annoying. However, the number of Silverstripe CMS projects that implement file search is probably very small ... and for all the other projects, having this field there will probably confused users.

In the short term, you could try these steps to expose this value and allow users to edit it:
* extend `SilverStripe\AssetAdmin\Forms\ImageFormFactory` and `SilverStripe\AssetAdmin\Forms\FileFormFactory`
* override one of the methods to add a CheckboxField to toggle the ShowInSearch property
* use the Injector to override the core FormFactory classes with your own.

We really should add a few extensions points on those FormFactory classes so developers can hook into them with Extensions.

**Comment by lerni** [comment]
https://github.com/lerni/folderindex is doing something like that but to keep it "simple" it's based on folders and settings are inherited for setting X-Robots tags. Independent of the mentioned module, I'm unsure if it makes sense to keep this issue open?

**Comment by ChloeSartorelli** [comment]
Closing this issue - we won't be implementing this feature.
