### ISSUE TITLE
Missing: Full File edit fields

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#105]
Some fields are missing for file info: title at the top, Used on, Owner, Folder.

![image](https://cloud.githubusercontent.com/assets/936064/14236847/d82b8e6c-fa6f-11e5-8fc8-7db1a155b842.png)

Jira: https://silverstripe.atlassian.net/browse/OSS-1719

### TODO
- [x] Create list of links where File is used on (excludes Campaign)
- [x] Added and edited dates

**Comment by flashbackzoo** [comment]
Fields are currently hardcoded. We need to use the form schema to generate the view.

**Comment by tractorcow** [comment]
Additionally: Don't show dimensions for non-image files.

**Comment by mikenz** [comment]
Our users don't understand the "Owner" concept for an image, neither do I really. But what is important is who uploaded the image. 

So if 'Owner' became read only and was renamed 'Uploaded By' that'd be one less customization I have to make each time ;-)

**Comment by clarkepaul** [comment]
In the new designs the Owner field has been simplified down to just description stating who added the file. It is also separated out from the file details into an area about file usage (who did what and where is being used). I haven't had the appropriate discussions whether or not the feature of being able to change ownership is really even required but with this new design there is still the possibility to keep the functionality but it would be a few steps to change ownership which I feel is more appropriate. 
![pasted_image_11_04_16__12_57_pm](https://cloud.githubusercontent.com/assets/555033/14414298/019568de-ffe5-11e5-94c9-d0707dc5dc2a.png)

**Comment by clarkepaul** [comment]
@tractorcow my HTML/CSS is here for this panel https://github.com/silverstripe/silverstripe-asset-admin/pull/107/commits/442f528731ee78cf4d54e4b5b9010810d4014fa8
I suggest the folder location field should just be a dropdown for alpha.

**Comment by tractorcow** [comment]
Thanks... now to get it integrated into the code.

TODO...

**Comment by clarkepaul** [comment]
Once tabs are available in the file edit panel, we can make sure all of the additional missing fields are accounted for as per designs.
See: 
https://projects.invisionapp.com/boards/8PX68PMBX6VT/
https://projects.invisionapp.com/boards/6GX68P9YKERH/
And wireframe above for the usage tab.

**Comment by clarkepaul** [comment]
@sminnee What do you think about adding this one to alpha 2 as it makes the edit panel for files a feature match with what was there previously. Obviously it could also wait but @flamerohr has just implemented the tabs which have nothing in them as far as I'm aware.

To add:
Added and edited dates (excluding owner)
Used on pages links (excluding campaigns)

**Comment by flamerohr** [comment]
Pull requests made:
https://github.com/silverstripe/silverstripe-framework/pull/6024
https://github.com/silverstripe/silverstripe-cms/pull/1613

**Comment by tractorcow** [comment]
Reviewed and changes pushed up.

**Comment by tractorcow** [comment]
Fixed.
