### ISSUE TITLE
Missing: Validation error display

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#106]
If uploading too large or incorrect file types the upload reads "Failed to upload" but doesn't include the actual error.

If a file is invalid type, it should error without trying to upload at all.

Jira: https://silverstripe.atlassian.net/browse/OSS-1720

**Comment by flashbackzoo** [comment]
We should be able handle client-side file type validation with http://www.dropzonejs.com/#config-acceptedFiles assuming valid file types can be passed from the server-side config

**Comment by tractorcow** [comment]
Yep I think so. :D We should set the list of allowed extensions, as we do for uploadfield.

**Comment by tractorcow** [comment]
You should be able to validate filesize with html5 too.

**Comment by mister-todd** [comment]
Closed as fixed.

**Comment by 3Dgoo** [comment]
Was this implemented? This seems to be missing from the latest version. It would be great to add this in.
