### ISSUE TITLE
IE11 Insert file split mode display issue

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-asset-admin#1084]
silverstripe/asset-admin 1.x-dev a789c6b
silverstripe/framework 4.x-dev ce3dba5

When I edit a page
And I select split mode
And I use TinyMCE
And I click the "Insert an image" button
And I select an image
Then I see the following display issue in IE11:

![image](https://user-images.githubusercontent.com/4809037/80770270-ecfaa200-8ba3-11ea-9141-cdf1a0afb106.png)

**Comment by maxime-rainville** [comment]
I think that's a duplicate of https://github.com/silverstripe/silverstripe-cms/issues/2473.
