### ISSUE TITLE
Version's relative time in History viewer appears as a link (but is not)

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-asset-admin#1088]
In the history tab, the relative time a version was created looks like a link (underline and cursor: pointer) but doesn't perform any action.

![Screen Shot 2020-05-11 at 9 08 51 PM](https://user-images.githubusercontent.com/233342/81545191-a0496f00-93cc-11ea-8c35-89f8d28368ac.png)

I'd suggest changing the styling to remove the link-like look.

**Comment by robbieaverill** [comment]
I agree. I would expect it to show me a raw datetime on hover though (personally).

cc @silverstripeux

**Comment by clarkepaul** [comment]
File history isn't a default UI so we aren't involved too much design-wise in it at the moment. I agree with the issue and suggestion to resolve it.

**Comment by robbieaverill** [comment]
For context, https://github.com/silverstripe/silverstripe-asset-admin/commit/7f21b25e9a9f83d5c72393609a0c0c3d5493d705 introduced the pointer cursor and underline on this. I'll remove it though since we agree it doesn't need to be there.

It already shows the full datetime on hover.

**Comment by robbieaverill** [comment]
Fixed in 1.5
