### ISSUE TITLE
Should "src" and "tests" be top-level folders?

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-asset-admin#110]
Hey,

I'm a little confused by the folder structure. `src` is a folder typically distinct from `tests`. `tests` is inside `src`.

The SilverStripe module standard suggests `code` and `tests` as top-level folders for PHP. So I guess we should put the front-end code in a separate folder, but I mixing tests through the code makes it quite confusing, and it doesn't make a lot of sense to have `src` as a subfolder, given `src` in this context in most other projects means "not the tests".

What do you think about this structure?

 * code
 * tests
 * client
   * dist
      * en.js
      * bundle.js
      * ...
   * lang
      * en.js
      * ...
   * src
     * components
     * state
     * ...
   * tests

The changes are:

 * Rename "javascript" to "client". ("frontend" would also work")
 * Move tests out of source to their own 2nd-level folder
 * Get rid of the src subfolder in lang, and instead compile into dist

**Comment by tractorcow** [comment]
I have no strong disagreements; This needs to be discussed in the larger context of "standard module paths" to make sure they line up with our supported module definition, though (which should really be as sparse as it can).

I think declaring supported modules use "client" for public files that would be sufficient.

Want to raise this at the next core hangout?

**Comment by tractorcow** [comment]
Ugh, this reminds me... I need to update `cow` to work with `lang js directories that contain other files that shouldn't be translated`.

https://github.com/silverstripe/cow/blob/master/src/Steps/Release/UpdateTranslations.php#L197 

With i18n translations, the "src to dist" compilation step is handled by cow, not via npm/grunt. Might need to set a new convention; Perhaps a subfolder in src for lang files?

**Comment by tractorcow** [comment]
To be fair, the js "source" files for languages are actually json files, not executable scripts. Maybe it should be kept distinct? I'd rather the extension was .json too to match the content type.

How about

* code
* tests
* client
  * dist
    * lang
      * en.js
    * bundle.js
  * src
      * lang
        * en.json
      * source1.js

**Comment by sminnee** [comment]
It would be good to hear from the JS developers about how carefully considered the status-quo decision was, and how they're finding it compared to working with our PHP approach of top-level test folders.

**Comment by flashbackzoo** [comment]
Having tests in a component's folder keeps components portable. There have been cases where we've needed to move components between modules, from asset-admin to framework for example, and it's made it really easy having everything on one folder.

If we decide to create npm modules for components at some point this will be useful too.

It also makes tests easily discoverable and keeps testing in the front of your mind. When you're working on a component and the tests folder is right it makes it hand not to write tests.

**Comment by tractorcow** [comment]
> Having tests in a component's folder keeps components portable. There have been cases where we've needed to move components between modules, from asset-admin to framework for example, and it's made it really easy having everything on one folder.

As long as we can be sure that whenever we want to omit a directory from a distribution package, we can safely assume that all files in that directory should be removed at the same time).

In this case, tests and source files can be left out, but it's not always the case.

**Comment by flashbackzoo** [comment]
@chillu any thoughts on this?

**Comment by chillu** [comment]
Basically what @flashbackzoo said :) There's little performance overhead in discovering tests via NodeJS globs in a folder structure with fairly limited amount of files. And in case you want to ship archives without tests, `.gitattributes` supports glob-style exclusions via `export-ignore` as well (see https://www.kernel.org/pub/software/scm/git/docs/gitattributes.html and https://www.kernel.org/pub/software/scm/git/docs/gitignore.html).

We've adopted this practice from WP Calypso. It's not explicitly described in their conventions, but hinted at in the "components" guide (around reusability): https://github.com/Automattic/wp-calypso/blob/master/docs/components.md.

BTW, agree with `javascript -> client` rename, since the folder now also contains per-component style sheets

**Comment by chillu** [comment]
Fixed with https://github.com/silverstripe/silverstripe-asset-admin/commit/cff8c8f738b54f9c8667cac5d56bc091984dd176
