### ISSUE TITLE
Interacting with breadcrumb reverts list view display to grid

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-asset-admin#1109]
# Steps to reproduce
- Navigate to a subfolder
- Switch to the list view
- Use the breadcrumb to navigate to a different folder

Expected results: You get taken to that folder and files are still displayed in the list view
Actual results: You get taken to that folder, but files are displayed in a grid

https://youtu.be/bBn3yFZfCUY

# Notes
The back button work fine.

# PR's

- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1129

**Comment by emteknetnz** [comment]
Linked pull request has been merged
