### ISSUE TITLE
Rename "Details" button to "Edit Details"

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-asset-admin#1116]
_Initially reported in original PR: https://github.com/silverstripe/silverstripe-asset-admin/pull/1038_

New in Silverstripe 4.6 is the ability to edit file information directly in the modal.

When adjusting an image in an UploadField, the _Details_ fields are read-only, and the button to make them editable is confusing just labelled "Details":

![Screenshot 2020-06-02 at 09 43 37m@2x](https://user-images.githubusercontent.com/329880/83500600-e6b75880-a4b6-11ea-812a-46287ae5b9b3.png)

A primary use case of this button is when using the FocusPoint module.

---

The same button exists in a different context when editing a WYSIWYG image:

![Screenshot 2020-06-02 at 09 42 07@2x](https://user-images.githubusercontent.com/329880/83500385-9a6c1880-a4b6-11ea-9b44-6d33bc7c81f6.png)

Here, the Details fields are not visible, so changing it to just say "Edit" would be unclear.

---

Therefore I suggest renaming it to say **Edit Details** so that the action is clear in both contexts.

**Comment by purplespider** [comment]
I should mention, that the ideal here is that when adjusting an UploadField image, the details fields are immediately editable, rather than read-only. Then we don't even need to display a button.

**Comment by lerni** [comment]
To me click on a button to edit settings that belongs to a file makes sense and therefor just have fields like placement etc. editable is well OK. But "Details" doesn't make clear that you probable edit something that is used elsewhere. I agree "Edit Details" or even "Edit File Settings" would explain that better than just "Details".

**Comment by micschk** [comment]
The '(Edit) Details' button isn't shown at all when this same modal gets loaded from an UploadField.
Only a cross is shown, without any label or title or any clue ("Cancel" aria-label, actually unlinks the current image) 🤦‍♂️.
Stunning UI 'improvements', all this used to work way more intuitive in a certain earlier versions...

**Comment by lerni** [comment]
I've tried to reproduce what @micschk wrote with 4.8.x and 4.9.0-rc1  but either I do not understand or I cannot.

This button?
![Bildschirmfoto 2021-09-10 um 12 11 33](https://user-images.githubusercontent.com/472115/132839118-a1617b71-0273-42ff-b7ba-b1ee88ed2b91.png)


I wonder with what versions or other "Environment variables" like language etc. you used, to get that result?

**4.8.x**
```
silverstripe/framework (4.8.0)
silverstripe/admin (1.8.0) 
silverstripe/cms (4.8.0)
silverstripe/assets (1.8.0)
```

**4.9.0-rc1**
```
silverstripe/framework (4.9.0-rc1)
silverstripe/admin (1.9.0-rc1)
silverstripe/cms (4.9.0-rc1)
silverstripe/assets (1.9.0-rc1)
```

**Comment by purplespider** [comment]
@micschk Maybe you are experiencing this bug?: ["(Edit) Details" button only visible if grid shows the page of selected file #1136](https://github.com/silverstripe/silverstripe-asset-admin/issues/1136)

**Comment by micschk** [comment]
> @micschk Maybe you are experiencing this bug?: ["(Edit) Details" button only visible if grid shows the page of selected file #1136](https://github.com/silverstripe/silverstripe-asset-admin/issues/1136)

Aah, yes that appears to be it! And the issue thread even contains a composer command to pull the fix in... Thanks!

**Comment by clarkepaul** [comment]
I've left a bit more thoughts on issue https://github.com/silverstripe/silverstripe-asset-admin/issues/1209, for example not having much space near the file title due to long file names and another idea of having the link in the actions bar at the bottom. 

Works a bit better for the Uploadfield experience too as a potential quick fix. 
Doesn't resolve the double click to edit for the upload field though, more on that in #1209 as well.

**Comment by nathanbrauer** [comment]
Going back to the original ask of this issue: Rename "Details" to "Edit Details"....

I would argue that this is deserving of a higher impact label seeing as I just spent an hour trying to find a way to enable editing on via UploadField only to finally find these tickets find that "[Icon] Details" actually meant "Edit Details".  I'm sure I'm not the only one.

Given how incredibly simple this change should be, do we think we can get this updated soon?

PS: Hi, it's been a while but I'm back :)

**Comment by ChloeSartorelli** [comment]
Closing as a duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/1209 since there's more discussion in that issue.
