### ISSUE TITLE
Replace file is by drag and drop not clear

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-asset-admin#1123]
You can replace a file by dragging a file from your file manager onto the preview for that file. I literally didn't realised you could do this until I glance at the code for the Preview react component and saw the replace file logic.

**Comment by maxime-rainville** [comment]
@silverstripeux I think this is mostly a UX problem. I'll let you decide how much value you want to place on this.

**Comment by Cheddam** [comment]
Provisional impact label applied, @silverstripeux feel free to bump it up if necessary.

**Comment by clarkepaul** [comment]
I didn't think that was a thing either, pretty sure it's never been mentioned—I guess the library just had that functionality? I've just a play with it and feels pretty intuitive as is, I think people would use the action from the main "more options (...)" dropdown. Even if it was done as a mistake they have the opportunity to "Undo". We could add a note in use help to describe the functionality. I tested when on "Placement" tab for a file (from TinyMCE) and you can't replace from there, you need to go to "Details" and it works as expected.

I think we could close this issue unless there was other interactions which over complicated it?

**Comment by maxime-rainville** [comment]
From the glance I had at the code, it didn't look like some accidental feature that we inherited from some libraries. It looks like someone put a fair bit of effort in getting this working.

If we don't think it's a wortwhile feature, then maybe we should just remove it.

I'll close this for now.

**Comment by clarkepaul** [comment]
Cool. There are a few visual enhancements we can do to make the dropzone clearer (image that appears is not viewable at all sizes) but I can raise that as a separate issue.
