### ISSUE TITLE
Newly created top-level folders disappear after navigating

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-asset-admin#1131]
### Affected versions

Tested against 1.6.x-dev / 1.6.0, potentially impacts older releases too.

### Summary

Folders created in the top-level / root directory of the Files area disappear after navigating in and out of a folder.

Steps to reproduce:

1. Create a new folder in the top-level of the Files area
2. Open the folder
3. Navigate back to the top-level area
4. Observe that the new folder (along with any other folders created since loading the Files area) has disappeared.

Creating another folder or uploading a file temporarily fixes the issue, and reloading the CMS will also fix the issue.

**Comment by ChloeSartorelli** [comment]
Confirmed this happens sometimes in the CMS 5 beta as well. It's yet another example of state issues in the assets section.

**Comment by ChloeSartorelli** [comment]
Just found #874 which has more discussion on it. Marking this as duplicate.
