### ISSUE TITLE
Use variables.scss from framework

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#114]
This module currently has a `variables.scss` file (https://github.com/silverstripe/silverstripe-asset-admin/blob/master/javascript/src/styles/variables.scss) with a large overlap to the framework file based off bootstrap: https://github.com/silverstripe/silverstripe-framework/blob/master/admin/scss/bootstrap/_variables.scss. Only module specific styles should be retained in this modules own `variables.scss`, and build tooling adjusted to pull in the framework file

/cc @clarkepaul

**Comment by clarkepaul** [comment]
Yeah i would say that there is only 7 variables unique to Asset-admin, could we move those variables to the global variables or do they need to be module specific? If we moved them they could potentially be reusable then (just not sure of the use case yet).

**Comment by chillu** [comment]
Pauls done that through fffe3427dc28a7332052072b67f502c8f469575e
