### ISSUE TITLE
File delete modal should use same data as new used on table

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-asset-admin#1146]
When deleting a file, the number of place(s) a file is used should use the same data source as the [updated used on table](https://github.com/silverstripe/silverstripe-admin/issues/1098)

![image](https://user-images.githubusercontent.com/4809037/96059569-c4b0f680-0eea-11eb-871f-522e5201672d.png)

## ACs
- [x] The new endpoint created as part of the used on table work is referenced
- [x] Performance impacts are considered. If there's significant delay, consider reviewing the modal wording with PUX
- [x] Modal wording is updated to report the number of files within the folder (a more performant query)
- [x] Implementation in PR is for GraphQL3 - create follow up issue to check in GraphQL4 update: it works fine in GraphQL4 so no need

## Notes
- There's a couple of scenarios to consider with this modal. This will need some broad testing when: deleting a folder, v.s. deleting a file, etc.
- Consider the performance impacts of deleting large folders and consider options for reducing this.

## PRs
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1178

**Comment by emteknetnz** [comment]
The file count on the modal when you attempt to delete a folder is currently even more broken then when you attempt to delete a file

Setup:
- folder 'abc' which contains a 2x images, one of a fantail image, another of a tui image

- fantail sample image used 5x:
- 3x via page content
- 2x via has_one on a Page.has_one relations
- file usage table correct reports 5x usage
- file delete modal (use on "owns" endpoint) incorrectly reports 3x

- tui sample image used 3x
- 2x via page content
- 1x via has_one on Page.has_on
- file delete modal incorreclty reports 2x

However when I attempt to delete the parent 'abc' folder, the modal shows the following:

![image](https://user-images.githubusercontent.com/4809037/107583572-fa2edc00-6c5f-11eb-821d-e91d4c85f757.png)

So it seems the language is pretty misleading. What it's actually reporting is that "2 of the files contained in this folder are used AT LEAST ONCE (according to the 'owns' method)

**Comment by brynwhyman** [comment]
Nice catch on the existing bug on how the modal is counting file usage @emteknetnz. For context these new GraphQL query endpoints [were created this relatively recently](https://github.com/silverstripe/silverstripe-asset-admin/issues/931).

I understand that the performance impacts could be a concern if a folder contains a significant amount of files in uses. If the wording was reduced to something like "you're about to delete a folder that contains [n] file(s) which may be used in site content." I don't think that's a major change to the UX flow now. Even with a modal that counts file usage, there's no clear path for a user to then go and see what files _are in use_ without clicking through the details of each one individually. 

Given there's no quick way for a user to source what files in a folder are in use, another option (with the existing graphql query) could be to just alert the user that "_at least one_" file within the folder is in use before deleting the folder. I'm not sure how useful that actually is though...

> One option, which I don't recommend at all, would be to mitigate file usage to queuedjobs setup
Agree, let's not do this!

**Comment by emteknetnz** [comment]
>> could be to just alert the user that "at least one" file within the folder is in use before deleting the folder

I don't think this is a good solution.  The problem is the graphql query used for the modal does not include the has_one etc relationships that were added during the used on table work.  For instance if there is only a single file in a folder that is about to be deleted, and that file is only used via a DataObject.has_one relationship, then that WILL NOT appear in the graphql endpoint that reports folder file usage.

So my recommendation is that we changes to simply report the number of files within the folder.

**Comment by clarkepaul** [comment]
If we can't be confident in saying at least one file is in use (which I thought we could do) then I'm happy with @emteknetnz 's wording for the message. If we ever extended the messaging/functionality it would be to identify the images which are used, and not where they are in use (makes more sense to me).

**Comment by brynwhyman** [comment]
Thanks @clarkepaul I've added an additional AC to reflect that.

**Comment by emteknetnz** [comment]
@clarkepaul OK have run into a bit of a hurdle on this one, what is the messaging supposed to be when you attempt to delete combination of Files AND Folders at the same time?

You can do this by selecting both things via the checkboxes or holding the mouse button down and drawing a selection square around them

Previously it calculated the (incorrect) file usage for the 2.  Now we have two things we need to communicate:
- the number of files and the total file usage count
- the number of folders and the nested file count

What should the messaging here be?

**Comment by clarkepaul** [comment]
I thought we weren't able to comfortably count the total files used? 

I would simplify it to this:
Warning: you're about to delete ~~a folder that contains~~ [n] file(s) which may be used in your site's content. Please carefully check the file usage on the files before deleting the folder.

We could put the folder count in but thats not as important in my books, keep the messaging only about files only I reckon.

**Comment by emteknetnz** [comment]
OK so if you tick the following

[x] Folder with 3 files
[ ] Folder with 2 files
[x] bird.jpg
[ ] dolphin.jog

And then you click the "Delete" button

You'll get a message that says the following:

Warning: you're about to 4 file(s) which may be used in your site's content. Please carefully check the file usage on the files before deleting the folder.


And for the following:

[ ] Folder with 3 files
[ ] Folder with 2 files
[x] bird.jpg
[x] dolphin.jog

Warning: you're about to 2 file(s) which may be used in your site's content. Please carefully check the file usage on the files before deleting the folder.


And even for a single file, we still don't mention the number of times it's used

[ ] Folder with 3 files
[ ] Folder with 2 files
[x] bird.jpg
[ ] dolphin.jpg

Warning: you're about to 1 file(s) which may be used in your site's content. Please carefully check the file usage on the files before deleting the folder.


Is that what you'd like?  That's certainly the easiest way to go about it.

**Comment by clarkepaul** [comment]
All good by me thanks

**Comment by brynwhyman** [comment]
Blocked, pending UX feedback in the pull request. CC @clarkepaul :P

**Comment by brynwhyman** [comment]
This was blocked awaiting a small suggestion for modal wording. I've added a suggestion as a comment in the pull request. There's still some outstanding minor feedback to address @emteknetnz

**Comment by emteknetnz** [comment]
PR has been updated

**Comment by brynwhyman** [comment]
> Implementation in PR is for GraphQL3 - create follow up issue to check in GraphQL4

Can we at least check the compatibility with GraphQL 4 as part of this issue? V4 is supposed to be backwards compatible so if we make this work shouldn't we check that it works for both versions now?
