### ISSUE TITLE
Checkbox unable to be selected/deselected in gallery list view

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-asset-admin#1156]
### 4.7.0 beta-1 kitchen sink testing

**To reproduce:**
- Navigate to the Files section
- Navigate to a folder
- Change view of gallery to list
- Select the checkbox

**Outcome:**
Item is selected but visually not as no checkbox tick is visible. Switching back to gallery view, note the item is selected. Switching back to list view the tick box is present but can not be deselected.

![Screen Shot 2020-11-06 at 11 49 34 AM](https://user-images.githubusercontent.com/24258161/98305788-67aaeb00-2027-11eb-806f-843ff60428d7.png)

Note here the pagination is also broken.

cc @maxime-rainville 

# Pull request
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1159

**Comment by maxime-rainville** [comment]
Could be related to https://github.com/silverstripe/silverstripe-asset-admin/commit/eee32b6ea6fdf512b928580a5f89a4fdb4bc4bd2

I updated the way the table is rendered so it only renders the rows that have change. React might net realise row selection counts as a change.

**Comment by maxime-rainville** [comment]
@sachajudd Sorry I merged the fix without running it past you. Do you want to have a look before I close the issue?

**Comment by sachajudd** [comment]
Happy with Garion's peer review, all good to close.
