### ISSUE TITLE
File search not reflecting selection of advanced filters

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-asset-admin#1158]
The file search allows you to select advanced filters. When you specify one of those it's meant to show as a label in the search box.

![image](https://user-images.githubusercontent.com/1168676/98335819-95fdea00-206a-11eb-8d0d-c43d689af622.png)

However, it doesn't any more for the File section. Gridfield appears to be working fine. The criteria is applied to the seach result but forgotten on the next search.

https://youtu.be/icbziGNdNO4

### Notes
- There's an idea that the function that renders this may have been erroneously removed?

### PRs

- [ ] #1160

**Comment by maxime-rainville** [comment]
@silverstripeux ^

I'm pretty sure this was working fine 4.6 and that's a 4.7 regression.

**Comment by bergice** [comment]
Please see https://github.com/silverstripe/silverstripe-asset-admin/issues/356#issuecomment-698736465

**Comment by maxime-rainville** [comment]
This is a 4.6 regression. It was working fine in 4.5.
