### ISSUE TITLE
Saving page strips html comments

### ISSUE THREAD

**Issue by dratr** [silverstripe/silverstripe-asset-admin#1190]
Coming from SS 3.x, our page editors were used to being able to insert HTML comments in some pages using the tinymce source code browser.

In 4.x (framework 4.7.3, admin 1.7.3, asset-admin 1.7.1 are our exact versions),  HTML comments are being stripped away on save despite our configuring Tiny MCE to accept them.

We traced this down to "TinyMCE_ssmedia.js", specifically in its SaveContent handler.
Here, some work is done to deal with image shortcodes, then the result of that is serialized back to HTML by walking the resulting set of nodes and concatenating the "outerHTML" of each.
Because comment nodes do not have an outerHTML, they are skipped and discarded from the result.

## PRs
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1206

**Comment by dhensby** [comment]
I'm not sure this is something that will be looked into. There's very little value to most users in retaining HTML comments in TinyMCE - unless @dratr is prepared to author a fix for this, I don't think we should worry about this. Sure, it's a change in behaviour since ss3, but that doesn't mean it's a problem.

**Comment by dratr** [comment]
I fixed this in our installation - here is what we are using.  

[ss-fixcomments.patch.txt](https://github.com/silverstripe/silverstripe-asset-admin/files/6481713/ss-fixcomments.patch.txt)

**Comment by dhensby** [comment]
Are you willing to open a PR so it can be considered? Otherwise I think we should close this issue...

**Comment by ChloeSartorelli** [comment]
This seems to be working fine now without any changes.
If this problem persists for you please let us know so we can investigate.
