### ISSUE TITLE
Schema must contain unique named types but contains multiple types named "Result"

### ISSUE THREAD

**Issue by smaier** [silverstripe/silverstripe-asset-admin#1195]
after upgrading to Silverstrip 4.7 (from 4.4)
i'm receiving the above Error. i tried debugging it - but she callstack is too huge. any suggestions appreciated very much

**Comment by smaier** [comment]
Using silverstipe-graphql version 3.4.1 instead of 3.5 solves the issue!

**Comment by emteknetnz** [comment]
Great to hear that you've fixed this

We released and shortly after revoked the graphql 3.5.0 tag after noticing it caused issues with some Silverstripe installation. When we re-release graphql 3.5.0 it will contain some `conflict` values to prevent installation with Silverstripe 4.7 or less, meaning that 3.4.1 will install instead

https://github.com/silverstripe/silverstripe-graphql/blob/3.5/composer.json#L13
