### ISSUE TITLE
Broken build (1.7) - behat failures

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-asset-admin#1199]
There are a number of behat failures from the 1.7 branch and above.

--- Failed scenarios:
    tests/behat/features/insert-an-image.feature:15
    tests/behat/features/insert-an-image.feature:27
    tests/behat/features/insert-an-image.feature:39
    tests/behat/features/insert-an-image.feature:79

https://travis-ci.com/github/silverstripe/silverstripe-asset-admin/jobs/504190641

**Comment by bergice** [comment]
Resolved.
