### ISSUE TITLE
Folder name and checkbox out of place

### ISSUE THREAD

**Issue by jinjie** [silverstripe/silverstripe-asset-admin#1205]
Not sure if this was reported but did not find any issues related to this. 

![Screenshot 2021-06-01 at 9 20 49 PM](https://user-images.githubusercontent.com/2721195/120330306-44c38980-c31f-11eb-8f25-ae80fc8e3991.png)

I did a build, flush, vendor-expose and cleared browser cache but nothing works.

**Comment by kinglozzer** [comment]
Sounds like the same issue as https://github.com/silverstripe/silverstripe-asset-admin/issues/1184. Is your browser zoom at something other than 100%?

**Comment by jinjie** [comment]
> Sounds like the same issue as #1147. Is your browser zoom at something other than 100%?

Ah! Yes. It's at 90%. It goes off anything lower than 100%.

Closing this! :)
