### ISSUE TITLE
Assets search

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#121]
## Acceptance criteria:

- You can search for files by a keyword
- You can search by file type
- You can search by last updated date, as a date range (datepicker control needed)
- You can search in either the current folder and its subfolders, or just current folder (depending on pattern created and tested is most intuitive) and across the whole asset library

---
UX CSS:
Search wireframes: https://projects.invisionapp.com/boards/FAX68PE52Y8W/
* [x] Mock templates (using HTML from form templates)
  * [x] Expanding search field
  * [x] Search field and button
  * [x] Expanding filter panel 
  * [x] File type dropdown
  * [x] Limit to current folder checkbox
  * [x] Date range, fields (not datepicker)
  * [x] Search button / cancel button
  * [x] BEM styles
  * [x] Design pattern for clearing results and know you are viewing filtered results
* [x] Browser testing

DEV:
* [x] Replace temp markup with form schema
  * [x] Filter by type (image, audio, video (includes flash), archive, document, folder [nice to have])
  * [x] Date fields
  * [x] Limit to current folder checkbox
* [x] On search load, search field (not filter panel) must remain open and both search field and filters remain populated
* [x] When selecting search the search input is in focus
* [x] Search results with message to clear
* [x] Breadcrumbs represent search
* [x] Ensure hitting "enter" on any field in the form triggers a search.
* [x] Ensure all aria-expanded="true" are set to false when closed and vice versa 
* [x] Remove temporary JS
* [x] Clear form when clearing results

# Pull requests
* [ ] https://github.com/silverstripe/silverstripe-framework/pull/6389
* [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/330

**Comment by tractorcow** [comment]
We should remove the `admin/assets` => `admin/assets/show/0` redirect, and have `admin/assets` as the canonical URL for showing assets in the root directory. It also breaks the "back" button when going back through this url.

**Comment by sminnee** [comment]
As long as we're aware that this means we'll need to redirect `admin/assets/show/0` => `admin/assets`.

**Comment by sminnee** [comment]
We can probably live without this for alpha1.

**Comment by chillu** [comment]
Paul has removed search icon, fixing can wait until alpha2

**Comment by clarkepaul** [comment]
I done the styling for the search in https://github.com/silverstripe/silverstripe-asset-admin/issues/200 , from discussions we will probably go with just the search input and hold off on the advanced filters for the time being.

**Comment by chillu** [comment]
PHP search API endpoint has been fixed as part of https://github.com/silverstripe/silverstripe-asset-admin/pull/202/files. See `AssetAdmin->getList()`. We need to decide if we want to split a) advanced search and b) search form through form schema as separate github issues.

**Comment by chillu** [comment]
If we include advanced search in this card, it is dependant on creating React components for checkbox and dropdowns first (see #5521)

**Comment by flamerohr** [comment]
Insert media modal will need filter by images file type, it would be good to include this functionality during this story rather than that story

See https://github.com/silverstripe/silverstripe-asset-admin/issues/173 for more details

**Comment by clarkepaul** [comment]
I've created a new branch with the latest from master. The markup is mock and uses temporary js in LeftandMain.ss which will need removing.

**Comment by tractorcow** [comment]
See https://github.com/open-sausages/silverstripe-asset-admin/tree/pulls/4.0/asset-admin-search

**Comment by tractorcow** [comment]
And https://github.com/open-sausages/silverstripe-framework/tree/pulls/4.0/asset-admin-search

**Comment by clarkepaul** [comment]
**Search results page**
* Show back "<" link to previous folder.
* Search results toolbar text instead of breadcrumb (not limited to folder) examples:
** Results with keywords "keyword"
** Results with keywords "keyword" from "images"
** Results with keywords "keyword" from "images" last edited "11/12/16 - 20/12/16"
** Results from "images" last edited between "11/12/16-20/12/16"
** Results last edited between "11/12/16-20/12/16"



Search results toolbar text instead of breadcrumb (limited to folder):

**Comment by clarkepaul** [comment]
Visuals for search landing page https://projects.invisionapp.com/boards/PEX68PZC3TSH/

**Comment by flamerohr** [comment]
Pull requests
https://github.com/silverstripe/silverstripe-framework/pull/6389
https://github.com/silverstripe/silverstripe-asset-admin/pull/330

**Comment by clarkepaul** [comment]
When search fields are empty
![pasted_image_21_12_16__4_45_pm](https://cloud.githubusercontent.com/assets/555033/21376808/ef09b370-c79c-11e6-8277-d78b9729139f.png)
:
![image](https://cloud.githubusercontent.com/assets/555033/21376177/c4c12954-c797-11e6-8616-b36e72f92cd5.png)

**Comment by clarkepaul** [comment]
The search should remain open after the search has been made.

**Comment by flamerohr** [comment]
Thanks for the feedback @clarkepaul, I might leave searching by type and create a separate issue for after graphql is implemented.
I've fixed search field when empty (and grammatical issues for english)
When the panel expands, I've set the first field to get focus. And the accessibility issue was caused by a race-condition with the initial input focus.

**Comment by flamerohr** [comment]
oh speaking of the type search, it was a typo that stopped it from working :D

**Comment by clarkepaul** [comment]
Nice work, really nice to use. Friendly enough to use, and I can add a new issue for the tab order as not a stopper.

**Comment by clarkepaul** [comment]
I tried to do a rebase on framework because of failing tests but its beyond my level.

**Comment by tractorcow** [comment]
I'm taking over this PR. :)
