### ISSUE TITLE
Remove entwine/PJAX dependency from AssetAdmin boot logic

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#131]
Currently `AssetAdmin.php` relies on 3.x style PJAX loading of the main `<form>`. `AssetGalleryField.php` is implemented as a form field with a `<div>` placeholder which is "configured" via HTML5 data attributes. These get picked up by Entwine via `$('.asset-gallery-component-wrapper')` in `client/src/boot/index.js`, and passed on to a React component. 

Since we now have a form field schema, this approach is outdated. It should be replaced with the main form loaded via form field schema (rather than PJAX HTML), and the react component initialised the same way as `GridField` in `CampaignAdmin`.

This will also require loading the `asset-admin` related JS bundle via `LeftAndMain::init()`, since we shouldn't rely on that JS being lazy loaded via `jQuery.ajax()` monkey patches of `jQuery.ondemand`.

**Comment by flashbackzoo** [comment]
The routing work for this has been started https://github.com/open-sausages/silverstripe-asset-admin/tree/pulls/4.0/update-routing

**Comment by chillu** [comment]
That's been completed with the move to react-router
