### ISSUE TITLE
remote content (YouTube videos) are uneditable and break the CMS when if a video is removed

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-asset-admin#1344]
If one has a page, and that page embeds a YouTube video via the media button in the WYSIWYG, this is good.
Until the video expires for whatever reason.
In this case if one wishes to edit the embed to insert a new valid video link it results in a broken modal that never loads.

https://github.com/silverstripe/silverstripe-asset-admin/blob/1204ac2a68980e9fb44f05f287d1989ab417d5ec/code/Extensions/RemoteFileModalExtension.php#L99-L120

By design the controller action returns HTTP 500, which is not handled by the client (on the front end).
In the least a very confused and frustrated content editor.
In the worst, javascript errors and a non-functioning CMS. (unconfirmed, can't remember)

Test case: https://www.youtube.com/watch?v=IvTJ3cRzVbc

![image](https://user-images.githubusercontent.com/778003/228675093-11c0a8c7-e7b3-46aa-a6df-b5e0ba35db9a.png)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1574

**Comment by sabina-talipova** [comment]
PR merged. Issue was solved. This will be automatically tagged. Close.
