### ISSUE TITLE
Chosen dropdown class has changed

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#135]
It seems the chosen class names have changed but they haven't been updated in AssetAdmin.

In AssetAdmin styles its chzn-single vs chosen-single in the template so it doesn't render properly.
@chillu do you have any info on what its supposed to be?
![pasted_image_3_05_16__5_48_pm](https://cloud.githubusercontent.com/assets/555033/14975578/3b0f7c70-1157-11e6-9025-e28a6ec2ca3e.png)

**Comment by chillu** [comment]
Yeah, I think @hafriedlander must've either missed those in the chosen.js library upgrade a month or so ago, or it was a merge regression: https://github.com/silverstripe/silverstripe-framework/commit/2983dd58ff9d152d641deffa519aa10b966d03b8
