### ISSUE TITLE
TinyMCE: Right align the image without caption doesn't work

### ISSUE THREAD

**Issue by MelissaWu-SS** [silverstripe/silverstripe-asset-admin#1370]
## Step to reproduce

- Insert an image to a tinyMCE editor
- Choose '**Right**' for image alignment

![Screen Shot 2023-06-19 at 2 40 05 PM](https://github.com/silverstripe/silverstripe-asset-admin/assets/81267819/b9997dfd-2a35-4679-a620-2b8395e644d3)

## Expected behaviour:
The image should be aligned right and there should be no text wrapping around the image.

## Actual behaviour:
There is no way we can clear the text around the image, as we are not able to select the parent `<p>` element of the image in CSS. So the image is always wrapped with text.

![Screen Shot 2023-06-19 at 2 33 09 PM](https://github.com/silverstripe/silverstripe-asset-admin/assets/81267819/b7e19353-5ef7-459c-8a3f-27d607d67d80)

![Screen Shot 2023-06-19 at 2 32 57 PM](https://github.com/silverstripe/silverstripe-asset-admin/assets/81267819/fc561056-d963-4cb8-a5d0-20baca958359)

## Potential solution

The potential solution would be adding class names to the parent `<p>` element when an image is inserted. It could be done in the [TinyMCE_ssmedia.js](https://github.com/silverstripe/silverstripe-asset-admin/blob/86f1e4a6b7cabcb05ea4f3d16ab2537982846449/client/src/entwine/TinyMCE_ssmedia.js#L475). It would be similar to the image with caption, where a `<div>` element is added to replace the `<p>` element and there are class names on the `<div>`, so we can select the `<div>` for clearing the text around the image.

![Screen Shot 2023-06-19 at 2 49 50 PM](https://github.com/silverstripe/silverstripe-asset-admin/assets/81267819/e8c1304d-a608-4839-ba42-b4272ede175c)

## ACs
- Make image right alignment behave like CMS 4

**Comment by sabina-talipova** [comment]
I tested the provided example and didn't find any problem. All elements are aligned according to the selected setting. If wrap is selected, the text wraps around the image according to the selected setting.

**Comment by MelissaWu-SS** [comment]
Hey @sabina-talipova, the problem is with **RightAlone** option. If RightAlone is selected as below, there should **not** be text wrapping about the image. Currently, the image is wrapped with text if the image is "RightAlone". 
We have this issue on a project that uses. `silverstripe/recipe-cms: 5.0.0`.

![246712336-b9997dfd-2a35-4679-a620-2b8395e644d3](https://github.com/silverstripe/silverstripe-asset-admin/assets/81267819/fe11b8ef-da69-4e7d-9853-fa92c8c372c2)

**Comment by sabina-talipova** [comment]
Issue was fixed. Close.
