### ISSUE TITLE
Upload can't handle large amount of files (runs out of memory)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#139]
After adding images or folders to the assetAdmin items disappear completely.

## Related

 * [Implement cachable asset store](https://github.com/silverstripe/silverstripe-assets/issues/43)
 * [Large folder breaks GraphQL fetch](https://github.com/silverstripe/silverstripe-asset-admin/issues/536)
 * [Optimise Gallery Transfer](https://github.com/silverstripe/silverstripe-framework/issues/6457)

**Comment by clarkepaul** [comment]
@scott1702 just tested this issue and didn't have the same issue as me but we are both running the latest master version.

**Comment by clarkepaul** [comment]
Did some further testing... After about uploading 100 images it seems the AssetAdmin hits max capacity because there is no pagination and then fails to display the thumbnails.

Message within network tab of inspector:
Allowed memory size of 134217728 bytes exhausted (tried to allocate 77861472 bytes) in

**Comment by Firesphere** [comment]
The problem is caused by the system running out of memory while generating the thumbnails. Depending on your config, it may be a 100, but could also be at 600.
Pagination should resolve this, as the ajax response also takes a very long time when there are a lot of files..

**Comment by chillu** [comment]
We should limit the number of files which can be uploaded in one go to avoid the upload running out of memory. This is different from the API endpoint displaying large number of files, which should be implemented via pagination or lazy loading: https://github.com/silverstripe/silverstripe-asset-admin/issues/159

**Comment by sminnee** [comment]
I uploaded 185 files in one go and it worked well, except for #535 and #536.

I think this one can be closed.
