### ISSUE TITLE
The "Link to a File" option in the TinyMCE WYSIWYG allows links with no link text

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-asset-admin#1401]
## Description

<img width="521" alt="Screenshot 2023-09-12 at 2 28 23 PM" src="https://github.com/silverstripe/silverstripe-asset-admin/assets/87288324/a8c91b94-654a-4476-9d83-66bb7c5ebe15">

User can add link to file without "Link text". This field is not required. But it looks like link was added, since I can see additional actions like "Edit link / Remove Link". But if I save page a link disappeared.

## PR
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1403

**Comment by emteknetnz** [comment]
Linked PR has been merged
