### ISSUE TITLE
TODO: Refactor "queued files" into separate visual area and remove coupling here

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-asset-admin#1407]
## Description
We should refactor "queued files" into separate visual area and remove coupling in some functions in asset admit.
   - `handleMoveFilesSuccess`.  [See](https://github.com/silverstripe/silverstripe-asset-admin/blob/02728e1adcf5c912b3ab0d8dc64963a717139d0f/client/src/containers/AssetAdmin/AssetAdmin.js#L561)
   - `mapStateToProps`. [See](https://github.com/silverstripe/silverstripe-asset-admin/blob/02728e1adcf5c912b3ab0d8dc64963a717139d0f/client/src/containers/AssetAdmin/AssetAdmin.js#L802)
   - `mapDispatchToProps`. [See](https://github.com/silverstripe/silverstripe-asset-admin/blob/02728e1adcf5c912b3ab0d8dc64963a717139d0f/client/src/containers/AssetAdmin/AssetAdmin.js#L815)

**Comment by ChloeSartorelli** [comment]
@sabina-talipova What are "queued files" and what would a separate visual area be like?
I think this is one of those issues where we don't have enough context and should probably close it.

**Comment by sabina-talipova** [comment]
I left this TODO comment, because I think that the main idea here was to extract `queuedFiles` and all related logic into additional Component. 
But if you think that we are not going to spend time on this enhancement we can close this ticket.

**Comment by ChloeSartorelli** [comment]
I think the status quo is probably okay for now - we're not likely to spend time on this in the foreseeable future.
