### ISSUE TITLE
Can't delete files

### ISSUE THREAD

**Issue by vinh63** [silverstripe/silverstripe-asset-admin#142]
The delete button for Files simply doesn't work :)

**Comment by vinh63** [comment]
Also, if there is one function to perform (Delete), why do we need "checkbox", then "delete", why not just "delete'?

**Comment by chillu** [comment]
@vinh63 Can't reproduce this (on IE10 or Chrome). Can you provide more details?

**Comment by vinh63** [comment]
Weird! Working now :)
