### ISSUE TITLE
Permission check causes admin asset to breaks down when there's a lot of files

### ISSUE THREAD

**Issue by aria5305** [silverstripe/silverstripe-asset-admin#1427]
**Descriptions**

When there's a lot of files, (we got this when running a project with about 50,000+ within one folder) assets admin will no longer be able to render the files and will display the following error message. 

<img width="1354" alt="Screenshot 2023-12-12 at 9 55 35 AM" src="https://github.com/silverstripe/silverstripe-asset-admin/assets/25812675/c0e00ca1-6e64-4645-ac0f-6bec7c9b50a9">

Error message: 
```
Couldn't run query: SELECT "File_Live"."ID", (COALESCE("File_Localised_en_001"."Name", "File_Live"."Name")) AS "_SortColumn0" FROM "File_Live" LEFT JOIN "File_Localised_Live" AS "File_Localised_en_001" ON "File_Live"."ID" = "File_Localised_en_001"."RecordID" AND "File_Localised_en_001"."Locale" = ? WHERE ("File_Live"."ID" IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ??, ?) OR "File_Live"."ID" IS NULL))
  
  ORDER BY "_SortColumn0" ASC
  
  Prepared statement contains too many placeholders
````

This seems to be caused by the permission check within `resolveFolderChildren` in FolderTypeResolver

Expected: 
Images to display without error

**Comment by ChloeSartorelli** [comment]
Thank you for reporting this.
Does this happen with asset-admin 1.x, 2.x, or both?

This is quite an extreme edge case so I doubt it will be worked on in the immediate future - if this is urgent for you please consider submitting a bug fix in a pull request for this issue.

**Comment by aria5305** [comment]
We are on 1.x for this, I am assuming the same will happen for 2.x as well as the snippet of code that triggers the break down is still in FolderTypeResolver.

We are currently just removing permission check as a workaround to avoid this issue.

**Comment by lozcalver** [comment]
I’ve also reached this, apparently the limit is 65,535: https://github.com/MariaDB/server/blob/10.5/sql/sql_prepare.cc#L2639. I quickly tested hacking in an `array_chunk` in `InheritedPermissions::batchPermissionCheck()` to break up the array of IDs into smaller chunks (I tested 20,000 chunk size) and it works. There are a few methods in `InheritedPermissions` that pass a list of IDs to `->byIDs()`, so it’d be good to patch all of them if this is deemed an appropriate fix.

It’s not pretty, but I don’t think it matters - devs should just be able to pass a list of IDs to their `PermissionChecker` and not know/care about how many queries it makes/how it calculates the result. As for chunk size, we’d want to undercut the 65,535 a bit so there’s room for additional placeholders (e.g. in joins/other filters), say 50k?

**Comment by lozcalver** [comment]
Actually that still won’t fully resolve it in 4.x:
- [The number of placeholders doubles if the object has stages](https://github.com/silverstripe/silverstripe-framework/blob/ff3a6f72df39cca2bf40e46c10a6a9e20b39f78f/src/Security/InheritedPermissions.php#L307-L309) - turns out I have ~35k folders, which is why my above “fix” appeared to work
- There could still be too many IDs returned and then [passed to another query here](https://github.com/silverstripe/silverstripe-asset-admin/blob/a144ac1884fe04d8521eddebe8ce992ef74057c3/code/GraphQL/Resolvers/FolderTypeResolver.php#L71-L75)

However, this PR might have resolved in 5.x anyway: https://github.com/silverstripe/silverstripe-framework/pull/10861

**Comment by ChloeSartorelli** [comment]
Closing - we aren't releasing new enhancements for CMS 4, and CMS 5 avoids this problem as of https://github.com/silverstripe/silverstripe-framework/pull/10861 and https://github.com/silverstripe/silverstripe-framework/pull/10904
