### ISSUE TITLE
Labels missing in image details page

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-asset-admin#143]
The labels “Title” and “Filename” existed on last hackday.
In addition, the texts are in wrong fonts comparing to the texts on last hackday.
![screen shot 2016-05-06 at 3 40 20 pm](https://cloud.githubusercontent.com/assets/6565447/15063821/7e8579cc-13a1-11e6-852e-d717e1ef1b22.png)

**Comment by clarkepaul** [comment]
Picking up issue.

**Comment by clarkepaul** [comment]
Putting down issue. :) is a react thing which is beyond me
