### ISSUE TITLE
Sort by title is not working in IE10

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-asset-admin#144]
Tested in IE10 on Win7, the sort by title for files are not working, while it works in Chrome.
![screen shot 2016-05-06 at 3 48 30 pm](https://cloud.githubusercontent.com/assets/6565447/15063903/51a89474-13a2-11e6-8a3e-f66313164d06.png)

**Comment by chillu** [comment]
`SCRIPT5007: Unable to get property 'field' of undefined or null reference `

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-asset-admin/pull/305

**Comment by flamerohr** [comment]
As mentioned in the pull request, a fair amount of refactor happening and will have fixed this issue
