### ISSUE TITLE
Asset folder name drops down from its icon in IE10

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-asset-admin#145]
Tested in SS4 demo site, the asset folder name drops down from its icon in IE10.
![screen shot 2016-05-06 at 3 52 35 pm](https://cloud.githubusercontent.com/assets/6565447/15063962/f42f2a3c-13a2-11e6-806a-b50fc344b62b.png)

**Comment by chillu** [comment]
Can't reproduce - how wide was your window when doing this? Did you just upload a file prior to this, delete a folder or a file, etc?

**Comment by jeffreyguo** [comment]
@chillu , not able to replicate it now. I did deleting folder and uploading. Did you do a new deployment to the SS4 demo site? Seems some of issues I logged were not able to replicate now.

**Comment by clarkepaul** [comment]
Will look into issue now and confirm either way.

**Comment by clarkepaul** [comment]
I can't replicate this either. I've tried a few different things and seems to work fine in IE10.
![pasted_image_9_05_16__4_30_pm](https://cloud.githubusercontent.com/assets/555033/15103772/83936d98-1603-11e6-9f57-422cbe8c2d62.png)
