### ISSUE TITLE
Thumbnails in CMS File system not showing up in Subfolders

### ISSUE THREAD

**Issue by draghu9** [silverstripe/silverstripe-asset-admin#1459]
### Module version(s) affected

2.2.0

### Description

Silverstripe Framework version 5.2.6
Asset admin version 2.2.0
Operating in clean Silverstripe install with no customizations

Uploading images in the CMS Files system is working but thumbnails are not showing up upon Publish. **This is happening at the sub directory level**. Example If we create a folder structure in Files as Files->Level1->Level2->Level3 and Upload an image at directory Level 3 and publish the thumbnail is missing.

I have checked the image src and the problem seems to be missing forward slashes (/) that separates the sub directories. Adding the forward slashes in the path via Inspect Element showed me the thumbnail. 

Following GIF should represent what I mentioned above.

![SS_Thumbnail](https://github.com/silverstripe/silverstripe-asset-admin/assets/1045707/d0361ae4-91b4-4998-9147-8a58ed361b9c)

### How to reproduce

1. Login to CMS running on Silverstripe framework 5.2.6 and Admin-Assets 2.2.0
2. Navigate to Files section from Left hand menu
3. Create nested sub-directories. Example Files->Level1Directory->Level2Directory->Level3Directory
4. Upload an image in Level3Directory
5. Publish

### Possible Solution

Navigating through the code I found there is a function called generateThumbnailLink(AssetContainer $file, $width, $height, $graceful = false) in ThumbnailGenerator.php file.

$result = $this->generateLink($thumbnail); gives the missformed thumbnail URL with all backslashes
adding str_replace("\\","\/",$result); seems to resolve the issue.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-assets/pull/603

**Comment by emteknetnz** [comment]
I'm unable to replicate this.

Is your webserver running Windows?

Could you try updating `vendor/silverstripe/assets/src/Flysystem/PublicAssetAdadter::getPublicUrl()` to the following:

```php
    public function getPublicUrl($path)
    {
        $path = Convert::slashes($path, '/'); // this line is new
        return Controller::join_links(Director::baseURL(), $this->parentUrlPrefix, $path);
    }
```

And let me know if that fixes the issue?

**Comment by draghu9** [comment]
I have done the changes as you mentioned, and it seems to have fixed the issue. Also Yes, my web server is running on Windows

**Comment by ChloeSartorelli** [comment]
PR merged. This will be automatically tagged by GitHub actions.
