### ISSUE TITLE
Auto-redirecting to admin/pages when page preview is already loaded

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#147]
Go to `admin/pages/edit/show/1` directly (not via PJAX from `admin/pages`), then use the CMS menu to navigate to `admin/assets`. It'll keep the right hand preview panel around, load the previously shown page preview in the iframe, then redirect you to `admin/pages/edit/show/1`.

**Comment by tractorcow** [comment]
I didn't notice the redirect anymore, but I've resolved the preview panel remaining.

https://github.com/silverstripe/silverstripe-framework/pull/5994
https://github.com/silverstripe/silverstripe-cms/pull/1611
