### ISSUE TITLE
Review filename sanitisation when asset is uploaded

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-asset-admin#1507]
### Module version(s) affected

2.2.4

### Description

**Note that this is not a security vulnerability report because as far as I can see there is no security issue, just a potential future issue.**

It is possible to upload files with double extensions such as `test.jpg.png`, however as far as I can see it is **not** possible to use this to upload script files such as `test.php.jpg` as upload validation picks this up.

![Screenshot 2024-10-31 at 9 36 49 AM](https://github.com/user-attachments/assets/3c4155a7-e14e-4f98-96f2-65cc180231da)

The recommendation is to review the current filename sanitisation config as it's good practice to not allow files with double extension in general even though there is technically no issue present currently.

### How to reproduce

Upload a file via asset admin that contains double extensions in the filename `test.jpg.png`. Check the URL of the uploaded asset. It looks like this: `/assets/test-images/6e8ad921fc/test.jpg.png`. The double extension is present.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by ChloeSartorelli** [comment]
How do you programatically determine that `file.jpg.png` is a double extension, but `file.orig.png` is not? Or are you suggesting just not allowing `.` in file names at all?

**Comment by mfendeksilverstripe** [comment]
Yeah, I recommend reviewing if something simple can be done to address this. Excluding specific characters completely sounds like a good idea (using sanitisation).

**Comment by ChloeSartorelli** [comment]
> Excluding specific characters completely sounds like a good idea

If we did that, we'd probably want to transform the value rather than throw an error. There's precedent for that, other characters already do result in transformation of the filename when it's uploaded.

Can you please help me understand what problems this is actually causing? Is your example `test.jpg.png` a jpg file with the wrong extension, or is it a png with the png extension?
If the former, what happens if you just rename it to `test.png`? Does it get caught by validation in that case?

**Comment by mfendeksilverstripe** [comment]
As far as I can see there is no functional issue currently. I raised this to just pass this information as this came up in one of our pen tests reports. I think it's totally acceptable to just roll with the current behaviour but I wanted to be sure that I'm not missing anything.

**Comment by mfendeksilverstripe** [comment]
I wanted to check if it would be possible to sanitise the name like this:

`test.jpg.png` -> `test-jpg.png` or similar. So no validation error, just a simple transformation.

**Comment by ChloeSartorelli** [comment]
That would certainly be possible - but if this isn't causing any problems, I don't think there's any reason to make any changes.

**Comment by mfendeksilverstripe** [comment]
All good, feel free to close the issue ✅
