### ISSUE TITLE
BUG When renaming file preview link doesn't update quickly

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#155]
Regression from https://github.com/silverstripe/silverstripe-asset-admin/pull/154, but can be fixed in alpha2.

If you rename a file the preview link stays the same. Refreshing the page displays the correct url.

![image](https://cloud.githubusercontent.com/assets/936064/15171830/91b95c72-17a5-11e6-8cab-3824934ac127.png)

Should be `bob__resampled.png`

**Comment by chillu** [comment]
That's fixed now (since we switched the edit view to form schema)
