### ISSUE TITLE
Assets adheres to a NFR for the amount of files it can handle

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#159]
## Acceptance criteria

- A folder containing ~~10,000~~ 1000 files can be opened in the asset admin

Note:
This should avoid out-of-memory errors on large folders. Our NFR for stable is 100,000 files with 10,000 files in a single folder but for Alpha4 we have reduced the NFR to 1000 files.

**Comment by dhensby** [comment]
We should be careful to still allow users to jump to a specific "page" and to hot link to parts of the assets to prevent UX regression

**Comment by tractorcow** [comment]
Could we have a dynamically-rolling hashlink? So that as you scroll down, it changes to `#page_<num>`?

**Comment by tractorcow** [comment]
If we have a good enough search feature, that should solve the issue with finding specific files.

**Comment by dhensby** [comment]
but not of hotlinking

**Comment by chillu** [comment]
If we end up using GraphQL, this story about pagination will become relevant: https://github.com/chillu/silverstripe-graphql/issues/7

**Comment by clarkepaul** [comment]
I've removed the parts of this issue to do with lazy load and infinite scroll so that this is just focused on performance. I'm dropping the NFR of folder to handle 1000 items for Alpha based on conversations with @sminnee and we can look to increase this potentially for Beta.

**Comment by sminnee** [comment]
@tractorcow did you do some testing of this already? how did we far? what is remaining?

**Comment by tractorcow** [comment]
The asset admin is usable with a large number of files. I have tested 10,000 files in root and noticed no noticeable slowdown in basic operations (navigation, uploading files, pagination). I'm happy to close this story. This is really an acceptance criteria of all stories going forward, rather than a story in itself, wouldn't you agree?

**Comment by chillu** [comment]
Removing estimate to avoid skewing the velocity. Agree that it's an NFR rather than a story, but since we didn't consider this aspect early enough in the AssetAdmin build, this card was supposed to be catchup and validation work related to the NFR.
