### ISSUE TITLE
Add success indication after "save" operation

### ISSUE THREAD

**Issue by nfauchelle** [silverstripe/silverstripe-asset-admin#163]
Once I've uploaded a file and then click on it to View it, I change the Title and hit save.

I get 3 little dots for a second and then they go away. There is no status or notification otherwise, I can see in the network tab I get a status OK response.

It might be nice to go back to the gallery list automatically, since clicking Cancel feels weird.

## AC
I would like to see a confirmation when I've edited the details of a file.

**Task**
- [ ] Save button (and cloud icon) shows a green "Saved" (with tick icon) once a file is saved (as per design below)

## Design
![screen shot 2017-08-23 at 4 20 04 pm](https://user-images.githubusercontent.com/8085295/29598832-a07fa860-881f-11e7-8461-de14efd44ece.png)

**Comment by chillu** [comment]
@clarkepaul What's your take on this? You were talking about a generic form message system the other day, right?

**Comment by clarkepaul** [comment]
Feedback could be via the button if we follow the pattern established on "Save / Publish" buttons. eg. https://projects.invisionapp.com/boards/WEX68PT5396C/

Personally I don't think we should close it on save (if you predict wrongly what the user wants it can be very frustrating for them, in this case I would leave it up to them they can still select another item or navigate away), but I do think we need a notification in addition to the save button status change if we where to do that.

**Comment by purplespider** [comment]
I was expected the _Save_ and _Publish_ buttons on assets to follow the same pattern as pages, updating to show their status after clicking. Feels a bit odd/broken to me without this.

**Comment by clarkepaul** [comment]
I already thought this was an open issue elsewhere but I don't see it so I've increased its visibility by adding to Beta2. I must have raised the same issue but on a different button or something?

**Comment by flamerohr** [comment]
Pull requests to fix this
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/220
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/610
