### ISSUE TITLE
Use FormBuilder in file edit form

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#171]
`Editor.js` currently instanciates `<TextFieldComponent>` directly (through `props.editorFields`), which is a relic of an earlier implementation when we didn't have the `FormBuilder` component.

- [x] Create a form in the `AssetAdmin` PHP class, with "Name" and "Title" fields
- [x] Reference the form schema location in AssetAdmin->getClientConfig(), allow passing through to the `<Editor>` component
- [x] Use `FormBuilder` in `<Editor>` component to create form
- [x] Save file through standard PHP form API (so we can trigger validation errors, tracked [separately](https://github.com/silverstripe/silverstripe-framework/issues/5523)). Form submission could be hidden in current `AssetGalleryField->update()` API endpoint

**Comment by tractorcow** [comment]
Question about this; Do you see us doing this correctly in CampaignAdmin? If that's the case, I can it as a base when porting across to asset-admin.

**Comment by chillu** [comment]
Not sure if I understand you correctly - we're using `FormBuilder` in CampaignAdmin already. It's not 100% since we should use a form library for dealing with form state (rather than the `onChange` handlers writing into our own state tree at the moment). But CampaignAdmin has the currently correct way of creating a form through `FormBuilder` :)

**Comment by flamerohr** [comment]
Framework changes:
https://github.com/open-sausages/silverstripe-framework/tree/pulls/4.0/formbuilder-file-edit
Assets-admin changes:
https://github.com/open-sausages/silverstripe-asset-admin/tree/pulls/4.0/formbuilder-file-edit

**Comment by tractorcow** [comment]
PRs at:
- https://github.com/silverstripe/silverstripe-framework/pull/5880
- https://github.com/silverstripe/silverstripe-asset-admin/pull/215
