### ISSUE TITLE
Additional space if there are no folders

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#174]
If there are no folder present there is an extra gap above files which should be removed.
![pasted_image_31_05_16__3_38_pm](https://cloud.githubusercontent.com/assets/555033/15662576/139f7636-2746-11e6-984b-da437641f367.png)

**Comment by chillu** [comment]
Confirmed this is still the case

**Comment by clarkepaul** [comment]
PR https://github.com/silverstripe/silverstripe-asset-admin/pull/301
and https://github.com/silverstripe/silverstripe-framework/pull/6289
