### ISSUE TITLE
Make "sort" dropdown keyboard accessible

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#183]
The "sort by..." item on the top right of admin/assets can't receive a keyboard focus. It's using Chosen.js which should already be keyboard friendly.

**Comment by sheadawson** [comment]
`.gallery__sort {
  .chosen-container-active {
    .chosen-single {
      outline: $gray-dark dotted thin; // firefox, ie
      outline: -webkit-focus-ring-color auto 4px; // webkit
    }
  }
}`

Didn't quite get this finished, but here's a start

**Comment by bergice** [comment]
Looks like this is resolved.
