### ISSUE TITLE
React/CSS: Create "url field" component (and write Jest test)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#184]
Bottom right of https://projects.invisionapp.com/boards/9GX68PTXUQFH/#/1547737/71606997

Could be a collaboration between multiple people, splitting up CSS, React and Jest unit testing tasks.

Create a React component for this purpose. Use bootstrap for the base elements (http://v4-alpha.getbootstrap.com/components/forms/)

Make sure the component can work standalone (e.g. doesn't rely

React component philosophy is explained here: https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/css.md
https://github.com/Automattic/wp-calypso/blob/master/docs/components.md

**Comment by flamerohr** [comment]
The design has shifted to the preview image will link to the file, so the "link" field on the bottom right is no longer relevant
