### ISSUE TITLE
Bulk actions don't stick to the top when scrolling

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#189]
A little bit of rearranging of divs is required so that the bulk-actions appear as fixed to the top bar but that they are also aware of the left menu (whether it is open and closed)

**Comment by clarkepaul** [comment]
PR https://github.com/silverstripe/silverstripe-asset-admin/pull/190

**Comment by tractorcow** [comment]
Fixed with #190
