### ISSUE TITLE
Uploadfield to align with 4.0 designs

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#191]
# Acceptance criteria:
- The form control has_one links to File fields matches the new look & feel
- The form control many_many links to File fields matches the new look & feel
---

The ability to add files to a page without inserting it into the editor. Refer to designs https://projects.invisionapp.com/boards/VGX68PKC7PYB/

Broken into sub-stories:
 - https://github.com/silverstripe/silverstripe-asset-admin/issues/296
 - https://github.com/silverstripe/silverstripe-asset-admin/issues/297
 - https://github.com/silverstripe/silverstripe-asset-admin/issues/298

Insert media link triggers the files area to appear in a pop up modal. Refer to https://projects.invisionapp.com/boards/6GX68P9YKERH/ which is covered by issue https://github.com/silverstripe/silverstripe-asset-admin/issues/173

**Comment by tractorcow** [comment]
Re-sized to 0 and closed; Replaced with split stories.
