### ISSUE TITLE
BUG: File edit doesn't update URL after navigating to different React section

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#193]
* Open `admin/assets`
 * Click on a file, navigating to `admin/assets/show/0/edit/<id>`
 * Click on `admin/campaigns` in the CMS menu
 * Click on `admin/assets` in the CMS menu
 * Click on a file, navigating to `admin/assets/show/0/edit/<id>`

Result: Shows `admin/assets/show/0` URL
Expected: Should show `admin/assets/show/0/edit/<id>` URL

Note this is different from https://github.com/silverstripe/silverstripe-asset-admin/issues/188

**Comment by chillu** [comment]
Refactoring this with a similar approach to `<CampaignAdmin>` (see https://github.com/silverstripe/silverstripe-framework/pull/5436/files) should resolve this (since there's no `_didHandleURL` hackery required any longer)

**Comment by tractorcow** [comment]
Top level menu navigation is now a full page redirect, so this doesn't happen anymore. :)
