### ISSUE TITLE
Media or fallback thumbnails should be available in the file edit panel

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#197]
## Acceptance criteria
- When you open a movie or audio file in the asset-admin, the sidebar shows a small playable video or audio widget

---

Media like videos should be reviewable in the file edit panel otherwise the fall back icon should be used as a fallback.

Files like .doc and .xls should should the fallback icon as a placeholder.

![pasted_image_21_06_16__5_53_pm](https://cloud.githubusercontent.com/assets/555033/16219260/2a1e78c8-37d9-11e6-923f-4e6bdd44aada.png)

**Comment by tractorcow** [comment]
To do this you would need to pull in something like https://github.com/tractorcow/silverstripe-mediadata, which adds a HUGE server overhead.

Let's just add a hook so that users can define their own thumbnail extension for media files, and default it to the icon.

**Comment by wilr** [comment]
Icon now defaults which allows you to play / preview in a new window. Not as good as a functional player but at least now it's available.
