### ISSUE TITLE
Move files and folders via drag/drop on gallery view

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#216]
## Acceptance Criteria
- Selected files and folders can be moved into one of the immediate subfolders shown in the gallery view
- Files and folders without edit permission can be silently ignored
## Related
- [Move files and folders via new folder location selection in "edit folder"](https://github.com/silverstripe/silverstripe-asset-admin/issues/217)
- [Upload files into folders via drag/drop](https://github.com/silverstripe/silverstripe-asset-admin/issues/104)

**Comment by sminnee** [comment]
Done!
