### ISSUE TITLE
Missing files render with red checkmark

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#218]
![image](https://cloud.githubusercontent.com/assets/111025/17652831/aa7211c4-62db-11e6-895c-4e86033a74d9.png)

The red checkmark is not communicating the right message here. The files are broken (not available on filesystem). You can simply recreate this issue with `rm -rf assets`.

Also: The red background is too much (could just be a red background image file?) - see https://github.com/silverstripe/silverstripe-asset-admin/issues/221

**Comment by clarkepaul** [comment]
This will need an else_if added in React I reckon. There should also be a message added to explain that the "File cannot be found" or "File not found" if space is limited. I'm thinking it should have a ? icon and then have a delete and replace image options on the edit panel.

if (this.props.uploading) {
 show cancel upload (X)
else_if missing {
 show ? icon
else {
 show success tick
}

**Comment by flamerohr** [comment]
Selected Files have a weird looking Icon:
![screen shot 2016-09-19 at 12 32 32 pm](https://cloud.githubusercontent.com/assets/1064889/18620614/28b88b72-7e6a-11e6-9560-51e2aa59ee72.png)

Disable selecting the files would be counter intuitive right?
Currently I've switched the colours to look like this:
![screen shot 2016-09-19 at 1 11 20 pm](https://cloud.githubusercontent.com/assets/1064889/18620636/a3e7261e-7e6a-11e6-8b12-d1dd6891dc02.png)

**Comment by flamerohr** [comment]
For reference

Paul Clarke [2:21 PM]  
@cjoe yeah i guess it makes more sense to leave the checkbox in that corner in this case and use the new icon with supporting text over the red area (like file exceeds limit: https://projects.invisionapp.com/boards/ZRX68PCPKESN/ )

**Comment by flamerohr** [comment]
Pull requests made:
https://github.com/silverstripe/silverstripe-asset-admin/pull/256
https://github.com/silverstripe/silverstripe-framework/pull/6035

Framework one isn't necessary, but since the icons need refreshing, would be good to include it now

**Comment by cjoe** [comment]
@clarkepaul @flamerohr I do not think I was meant to be tagged in this thread?

**Comment by flamerohr** [comment]
apologies, that was my alias in another chat program we use and I had copy+pasted

**Comment by clarkepaul** [comment]
Tested on IE10 and it seems that sometimes it only deletes files the second time you press the delete action, this isn't only for missing files.

**Comment by flamerohr** [comment]
yeah, it I'm not sure why... :( but definitely a separate issue
for some reason the ajax call is not registering properly until you click 2-3 tmes after the first time. (you can see the call being made in the Network capturing tab)

**Comment by clarkepaul** [comment]
CSS wise I can see some things I can tweak to improve the UI but I don't mind capturing those separately. 
eg white background on thumbnail, tick icon remove white background

Looks good to me

**Comment by clarkepaul** [comment]
Noticed an issue with uploading new files, might be related to this? https://github.com/silverstripe/silverstripe-asset-admin/issues/261

**Comment by clarkepaul** [comment]
Visual testing all good, I've created a minor enhancement for adding the message "file not found" to the editor panel here https://github.com/silverstripe/silverstripe-asset-admin/issues/265

**Comment by chillu** [comment]
Closing this by merging https://github.com/silverstripe/silverstripe-asset-admin/pull/256
