### ISSUE TITLE
Improve usability for deleting folders, files while considering associations to linked pages

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#219]
## Acceptance criteria

- When a user tries to delete a folder containing files that are still in-use on the draft site, an error message is shown detailing the files that are still being used and the places they are being used
- When a user tries to delete folder containing files that aren't used anywhere, a message saying the number of files being deleted and confirming that they are not used on the site is shown

Note: deletion and archive are synonymous for the sake of this story. Deletion on "stage only" is a future enhancement.

---

Subtasks

UX subtasks:

 - [x] Flow diagrams for each scenario. E.g. moving files, immediate deletion
 - [x] UX concept for deletion through campaigns
 - [x] Visual representation for missing files in HTML content editor (instead of the current broken image we see).
 - [x] Visual messaging for alerts (pre-deletion confirmation, post-deletion results alert) for moving / deleting.

I've made some wireframe mockups[ here](https://invis.io/KX9JXI9D3#/209151802_File_Deletion_Home) and general Asset-admin UX can be found on the CMS [style guide ](https://projects.invisionapp.com/boards/9GX68PTXUQFH/). The icon for warning is a placeholder for the time being and will need to be added to icon suite. 

** From @clarkepaul **
As a first step I think it would be best to safe guard the deletion of files that are in use with warnings, but when deleting a folder it would be best to block the deletion if its contents are in use. Deleting files directly it isn't as dangerous as the user has consciously selected the file to delete were as folders might have a network of nested folders and files which becomes hard for the user to know the implications of deleting it. If a folders contents are not are use then we can allow the deletion of folder and contents.

I had a think about how campaigns can potentially help to show relationships of files but currently files are not shown as the centre of the relationship as they are shown from a page perspective, and if you where to show all relationship of everything in a campaign it would soon bloat and not be relevant to a user anymore.

Further enhancements (excluded from this issue):
Adding a option to move folder contents.
Currently if a file is in use and its deleted then the file shows as missing on the site, as a "nice to have" I think we could hide missing files on the live site but show them in draft along with a warning for the admin (warning can be a separate issue).
 
Implementation
 - [x] Implement pre-deletion file counting (counts number of files + pages used prior to deletion)
 - [x] Implement delete alert pre-notice
 - [x] Implement post-deletion alert results notice.
 - [x] Behat tests
 - [x] Sparse docs update

---
Considered scenarios:
- User deletes folder which contains files, should the files also be deleted (could we show a campaign of related changes?). 
- The folder could be blocked from being deleted if files are being used, meaning the user would first need to remove those files from the places they are being used.
- Users should have the ability to move files and folders so that folders can be deleted without effecting the files contained within.
- Pages can be archived how does pattern cross over to files
## Related
- [Implement file publish control actions](https://github.com/silverstripe/silverstripe-asset-admin/issues/169)
- [Not clear if files are protected by default](https://github.com/silverstripe/silverstripe-asset-admin/issues/161)

**Comment by clarkepaul** [comment]
UX can be found on the CMS [style guide ](https://projects.invisionapp.com/boards/9GX68PTXUQFH/)
[Flow for deleting single/multiple files](https://projects.invisionapp.com/boards/9AX68PSPBY34/) from within asset-admin:


[Flow for deleting folders](https://projects.invisionapp.com/boards/XKX68PETMGZN/) within asset-admin:

**Comment by clarkepaul** [comment]
@sminnee this issue started off as a UX issue but, we added implementation tasks for basic improvements, the main difference with my current mocks and current functionality is that I think its best to block folder deletion if its contents is in use, the rest is improvements to messaging.

I just want to check it was you intention that basic implementation is included in this issue and for this alpha, and that your okay with the approach.

**Comment by flamerohr** [comment]
Perhaps this is a good chance to bring this table up to help the usability of this story? @sminnee https://github.com/silverstripe/silverstripe-asset-admin/issues/251

**Comment by clarkepaul** [comment]
We are going with the first option (of the three versions) for deleting folders for Alpha 4.

**Comment by flamerohr** [comment]
Pull request created https://github.com/silverstripe/silverstripe-asset-admin/pull/360
still got tests to write

**Comment by tractorcow** [comment]
Done!
