### ISSUE TITLE
Upload indicator has red background

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#221]
![image](https://cloud.githubusercontent.com/assets/111025/17722841/671b0e62-6489-11e6-9d6e-08771e1fc023.png)

Related: Missing files have red checkmark (https://github.com/silverstripe/silverstripe-asset-admin/issues/218)

**Comment by clarkepaul** [comment]
This isn't just a CSS issue from what i can tell. Dropzone should be creating a thumbnail which should be almost immediately usable, so I'm assuming we are applying a error class because the thumbnail generation isn't working. I don't know enough React to tamper with it unfortunately.

**Comment by flamerohr** [comment]
Had a quick look at the dropzone and galleryitem components, and it looks like it checked if it exists in the database without checking if it is uploading
I'll push a fix up soon :)

**Comment by flamerohr** [comment]
Added unit tests for file uploading, I ran into issues mocking images, so will need to research on how to do that...

Pull request is: https://github.com/silverstripe/silverstripe-asset-admin/pull/241
