### ISSUE TITLE
File edit sidebar is not keyboard accessible

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#224]
Somehow the keyboard focus state gets cancelled out when going through the gallery images before it can reach the file edit form (in Chrome 52)

**Comment by clarkepaul** [comment]
I think from memory it is tab accessible but it is before the gallery when tabbing through.

**Comment by chillu** [comment]
Fixed by https://github.com/silverstripe/silverstripe-asset-admin/issues/229
