### ISSUE TITLE
Editor sidebar preview exceeds panel width

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#232]
* It should have a padding on the right, rather than have the larger image expand the scroll space.
 * images (in the full-width view) don't resize to 100%
 * portrait images don't have a max-height, so can fill out the whole sidebar panel

![image](https://cloud.githubusercontent.com/assets/111025/17952086/74e7bfc6-6abb-11e6-88d4-4e36da6821c9.png)

![image](https://cloud.githubusercontent.com/assets/111025/18109972/07b6a0cc-6f69-11e6-8f09-f8ae25b02729.png)

Update: The missing space with "Title" will be fixed by adding tabs there.

/cc @clarkepaul

**Comment by clarkepaul** [comment]
Noted. This must be a regression, could be when the hidden tabs were removed.

**Comment by flamerohr** [comment]
I think this was when the image switched to using `PreviewThumbnail()` which doesn't add any classes to give it responsive behaviour?

**Comment by clarkepaul** [comment]
So I did a quick check and it seems all the classes are missing in the top part of the editor panel. 
The heading needs this class wrapping it -> .editor__heading
The image needs this class wrapping it -> .editor__file-preview
And the image needs this class -> .editor__thumbnail

That should get it most of the way back to how it was but there could be other classes missing.

**Comment by clarkepaul** [comment]
@flamerohr do your changes above fix this issue? I see you've added some classes as mentioned above.

**Comment by flamerohr** [comment]
@clarkepaul yes, I can provide a screenshot of after the classes were added if you'd like

I can't separate it out of that branch because it relies on CompositeField being defined in React :(

**Comment by clarkepaul** [comment]
Na that is fine, just saw this issue in the backlog and remember you were working on it so I thought I'd move it up to the next column.
