### ISSUE TITLE
Success screen on "add to campaign" not overlaying form

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#234]
![image](https://cloud.githubusercontent.com/assets/111025/18031202/8377ca66-6d29-11e6-9548-7dda304bdab6.png)

Context: https://github.com/silverstripe/silverstripe-framework/issues/5613

/cc @clarkepaul

**Comment by tractorcow** [comment]
Seems fine to me; I've tested in both pages and asset admin.

![image](https://cloud.githubusercontent.com/assets/936064/18657828/0bb62744-7f52-11e6-93d8-5195109053f5.png)

![image](https://cloud.githubusercontent.com/assets/936064/18657832/139b5dda-7f52-11e6-8f91-5f7d37fdd42c.png)
