### ISSUE TITLE
No graceful 404 handling for files/folders

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#236]
When a file/folder is accessed directly by path (e.g. `admin/asset/show/<id>`) but doesn't exist, it simply shows the loader forever. Show a generic error message instead, either through a general purpose messaging system (top of screen?), or centred in the middle of the screen.

@clarkepaul Ideas?

**Comment by clarkepaul** [comment]
I'm thinking a central message which you have to acknowledge by closing it, it would be the safest as the other notifications can be easily overlooked leading to confusion.

**Comment by flamerohr** [comment]
Created pull request https://github.com/silverstripe/silverstripe-asset-admin/pull/285

**Comment by tractorcow** [comment]
Fixed with #285
