### ISSUE TITLE
Image thumbnails are loading in full size (not resampled)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#237]
They've got the `_Resampled` suffix, but are in fact the original size - that's a showstopper for performance, since it'll load megabytes of image data - particularly until we implement infinite scrolling or pagination.

**Comment by chillu** [comment]
Confirmed this is still an issue, even with https://github.com/silverstripe/silverstripe-asset-admin/issues/248 merged.

**Comment by flamerohr** [comment]
Pull request https://github.com/silverstripe/silverstripe-asset-admin/pull/283
