### ISSUE TITLE
Popup position should calculate appropriate position of popups so they are visible (use tether)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#250]
Actions within the popup are partially hidden. I this example delete can be moved within the popup so more of the popup is visible, also because a publish action is likely to be added here as well.
![pasted_image_14_09_16__10_58_am](https://cloud.githubusercontent.com/assets/555033/18494528/b13e421a-7a6a-11e6-8f73-f24d7dc3e034.png)

**Comment by lukereative** [comment]
This no longer appears to be an issue.

**Comment by clarkepaul** [comment]
This was resolved some time ago cheers
