### ISSUE TITLE
Use a custom React component to render "used by" table in File details view

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#251]
Follow up from https://github.com/silverstripe/silverstripe-asset-admin/issues/105, which implemented this as server-generated HTML (which creates a rigid UI that's not extensible via React).

Switch the `File->getCMSFields()` implementation to include something like this:

``` php
function getCMSFields() {
    $fields->push(
        LiteralField::create('UsedOnTable')
            ->setSchemaData([
                'url' => singleton('AssetAdmin')->Link('api/usedOn/%d'),
                'columns' => [
                    'Used On' => 'PageTitle',
                    'Type' => 'Type'
                ],
                'component' => 'FileUsedByTable'
            ])
    )
}
```

The `<FileUsedByTable>` could make use of `<GridField>` to generate the table as a HOC, but ideally shouldn't extend the `GridField` ES6 class. The labels ("draft", "published") could be implemented as column-based rendering customisations in `<GridField>`, but that's likely wasted effort since we're planning to switch to a more sophisticated component like https://griddlegriddle.github.io eventually - for now, those view customisations can live in the `<FileUsedByTable>` component.

Data should be fetched from a new API endpoint created in `AssetAdmin`, which is cleaner than inlining the data in the original file API response (even if it causes another XHR).

This is an attempt to reality check our `<FormBuilder>` approach with a more advanced use case. There's more ideas floating around (dependency injection on React components, customising mapping of field lists in form builders, replacing `<FormBuilder>` in a particular context like `<AssetAdmin>`), but they're out of scope for this story.

![image](https://cloud.githubusercontent.com/assets/111025/18495640/b53a1750-7a73-11e6-902c-9b20f259d870.png)

**Comment by flamerohr** [comment]
Cool, but if this is already a custom component on the React side, couldn't we have a generic `CustomComponent` class for the PHP to define those kind of schema data with for the FormBuilder to call?
I guess to me using the current schema makes more sense trying to deliberately pull it out for separation.
Are we going to do something similar with `GridField` and eventually reduce/remove the reliance on `GridField` by shifting to Griddle?
I'd like to understand what the goal is to justify a whole new/separate schema and API call.

**Comment by chillu** [comment]
Closing this in favour of https://github.com/silverstripe/silverstripe-asset-admin/issues/593
