### ISSUE TITLE
Edit panel visual regressions

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#252]
It seems there are a few more regressions that are yet to be resolved, possibly more missing classes. Similar issues have been resolved back with this PR https://github.com/silverstripe/silverstripe-asset-admin/issues/232 but there was a few more not captured then.
- [ ] Spacing under heading too big
- [ ] Image not aligned (pretty sure it was to be full width of panel)
- [ ] There was a magnifying glass on hover which open the image in a new tab (temp to see full size)
- [ ] Spacing below image

![pasted_image_15_09_16__5_52_pm](https://cloud.githubusercontent.com/assets/555033/18539783/00520c0c-7b6e-11e6-82c1-f3b8df3052e4.png)

**Comment by wilr** [comment]
Looks good now for me.
![screen shot 2016-11-15 at 5 41 52 pm](https://cloud.githubusercontent.com/assets/101629/20293388/d7382b90-ab5a-11e6-9dbe-008ee929aeed.png)

**Comment by clarkepaul** [comment]
Cheers, yup this one is already done.
