### ISSUE TITLE
Slide-in effect of batch actions is off

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#257]
![image](https://cloud.githubusercontent.com/assets/555033/18693096/454bf06e-7ff3-11e6-8ee9-56677dfd0bcb.png)

When an item is selected it slides down and across to the left, it should slide down only.

**Comment by clarkepaul** [comment]
PR https://github.com/silverstripe/silverstripe-asset-admin/pull/258

**Comment by tractorcow** [comment]
Fixed.
