### ISSUE TITLE
Asset path has double forward slash if file missing

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#260]
The double forward slash happens if you check the missing file and then use the bulk action "Edit", it should only be a single forward slash.
![image](https://cloud.githubusercontent.com/assets/555033/18698047/1114a8fe-801b-11e6-917f-fbcb38f334e9.png)

**Comment by lukereative** [comment]
This no longer appears to be an issue, it now only displays a single slash.

**Comment by clarkepaul** [comment]
Closing cheers
