### ISSUE TITLE
Enlarge image in editor on click

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#262]
## Acceptance criteria
- When you click on the medium-size thumbnail in the sidebar, you open the image in a new tab
- When you click on the icon of a non-image file in the sidebar, you open the file in a new tab
---

This functionality was originally in there in a proof state but it has since been removed for the ongoing React development. In its basic form there was an icon which appeared above the image on hover and when the image was clicked it opened in a new tab at full size (browser default behaviour).

The styles and old php are removed around this time frame https://github.com/silverstripe/silverstripe-asset-admin/commit/56b5de449c8d5f6e510ead918441d7508ece20d0#diff-1725a22613a9ff930ae321601182c714R97

Example or design https://projects.invisionapp.com/boards/8PX68PMBX6VT/

This could be improved using modal or expanding Edit panel but that might be out of scope at this stage.

**Comment by flamerohr** [comment]
@clarkepaul It'd make sense to remove the "Clickable Link" field right? :) (bottom of details tab)

I switched the styling to use `opacity: 0` instead of `display: none`, has a better experience when hovering over the `:before` icon

**Comment by clarkepaul** [comment]
What do you think about showing the URL on hover above the image? I was thinking it might be a something that might end up being a "Copy" URL.

Showing on hover might have issues with small icon sized images or docs though. 
Otherwise I think this is fine.

**Comment by flamerohr** [comment]
Yeah, the small icon sized image is a little bit overwhelmed.
![screen shot 2016-11-03 at 12 14 55 pm](https://cloud.githubusercontent.com/assets/1064889/19950876/3dc0559a-a1bf-11e6-9f17-770866db8670.png)

Hmm, I'd suggest something like github's "Clone or download" button for displaying and copying the URL, where an input box could appear for copying (and possibly a copy call-to-action as well).
This could work in favour of small devices as well.

**Comment by clarkepaul** [comment]
The problem is that those "copy" things usually require a bit of flash to work, but thats also what I was thinking.

**Comment by flamerohr** [comment]
yeah, that's why I tentatively put "possibly" in, I don't agree with using Flash to have that feature either.

Javascript has gained traction in supporting clipboard commands http://stackoverflow.com/a/30810322

**Comment by clarkepaul** [comment]
Lets go with how your've done it and I can add a copy URL issue enhancement to the backlog with a design concept. It would be low priority I would think.

**Comment by clarkepaul** [comment]
I'm just going to add a transition to the image, will push up in a few minutes once IE10 tested.

**Comment by clarkepaul** [comment]
@flamerohr are you able to add a class to the editor panel if the file is missing? Otherwise the magnify icon still shows even if file is missing.

**Comment by clarkepaul** [comment]
Added image scale on hover

**Comment by flamerohr** [comment]
Would it be better if I removed the link altogether? I can still add a `editor__details--file-missing` class or something

**Comment by clarkepaul** [comment]
Yeah thats basically what I was going to do with css but probably better to put the smarts in there to not even show it in the first place, cheers.

**Comment by clarkepaul** [comment]
Can we show the message instead of the icon? I can style it.

**Comment by flamerohr** [comment]
Done something like this
![screen shot 2016-11-03 at 2 26 18 pm](https://cloud.githubusercontent.com/assets/1064889/19953354/c2a39012-a1d1-11e6-9b84-9895b953b709.png)

**Comment by clarkepaul** [comment]
nice ta

**Comment by clarkepaul** [comment]
Just added a bit of colour.
![image](https://cloud.githubusercontent.com/assets/555033/19953572/45a9838e-a1d4-11e6-95ea-82ce4d836823.png)

**Comment by flamerohr** [comment]
Great, this makes more sense than an icon :D

**Comment by flamerohr** [comment]
Pull request made here https://github.com/silverstripe/silverstripe-asset-admin/pull/300
