### ISSUE TITLE
Empty form description field holds additional space

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#263]
If empty the description field should not be there at all. Seems like it is just in assetAdmin?

![image](https://cloud.githubusercontent.com/assets/555033/18729144/9b958dfc-80a4-11e6-9cd1-45c8989c2172.png)

**Comment by wilr** [comment]
Tested this via my work on asset-admin, can't replicate and can see a wrapper for messages now. Still wouldn't handle the case if message was set to like ' ' but I think that's an edge case.
