### ISSUE TITLE
Progress bar background

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-asset-admin#266]
The progress bar while uploading only shows the blue "percentage done" portion, and seems to be missing a background for the whole bar.

See screenshot:
![screen shot 2016-09-22 at 12 52 55 pm](https://cloud.githubusercontent.com/assets/1064889/18734014/2ce5f1a6-80c4-11e6-96e7-7c6735f5dba2.png)

**Comment by clarkepaul** [comment]
Designs supplied here https://projects.invisionapp.com/boards/ZRX68PCPKESN/
