### ISSUE TITLE
Can't navigate between folders in insert media modal

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#268]
Once you navigate to a folder you can't navigate back, this whole modal will be rebuilt soon so best to leave if that is happening sooner rather than later.
![image](https://cloud.githubusercontent.com/assets/555033/18736502/bb5963d4-80db-11e6-806d-ed67df29281e.png)

**Comment by flamerohr** [comment]
So by default it shows ALL files (includes files in folders, not just root)
Selecting a folder, there is not option to change back to "All files"

Two points to cover:
 * Should we fix the "All files" behaviour when no folder is selected?
 * Would a button that triggers clearing the selected folder enough?

**Comment by clarkepaul** [comment]
I think either of those options would be okay as a temp idea, but actually I think it is best to move this issue to the end of Alpha4 work as we are supposed to replace this modal completely then (should be happening very soon).

@sminnee I'm moving this to Alpha4 as I don't think it will an issue once the work assigned to that release is complete.

**Comment by flamerohr** [comment]
I think this is ok to close now with the new insert media modal in place, what do you think @clarkepaul

**Comment by clarkepaul** [comment]
yup closing
