### ISSUE TITLE
Delete folder doesn't work

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-asset-admin#271]
The delete folder button is totally non-functional. It seems to trigger the save action instead.

**Comment by sminnee** [comment]
but this I mean the delete button shown on the folder detail side-panel.

**Comment by tractorcow** [comment]
This reminds me that we need to make it clear to the user what deleting a folder does; For example, deleting all files in that folder, and potentially having some kind of confirmation.

**Comment by flamerohr** [comment]
Fixed by https://github.com/silverstripe/silverstripe-asset-admin/pull/273
