### ISSUE TITLE
Create AssetAdmin unit tests

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-asset-admin#274]
## Acceptance criteria

- Asset-Admin module has at least 70% unit test coverage in its PHP code

---

There are a few complex logic functions in AssetAdmins which would be a good idea to have for code coverage.

**Comment by chillu** [comment]
Code coverage isn't enabled in CI for asset-admin, because we haven't figured out how to run those yet: https://github.com/silverstripe/silverstripe-asset-admin/pull/275. My assumption is that we can satisfy this card by getting coverage stats locally as a one-off

**Comment by robbieaverill** [comment]
FWIW the coverage as of today is about 45% when run locally with phpdbg (worth noting that xdebug and phpdbg can sometimes report different coverage levels).

**Comment by chillu** [comment]
I've manually reviewed coverage, and it's OK. There's a few classes which are mostly CMS field generation (= don't need much in terms of unit tests). Then there's a bunch of GraphQL stuff that should be moved to a more scaffolded approach, so adding more unit tests is a bit of a sunk cost. I'm closing this off for now, we just have to keep up good practices going forward.
