### ISSUE TITLE
Fix Postgres support

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#277]
See breakages in https://travis-ci.org/silverstripe/silverstripe-asset-admin/jobs/162918737

**Comment by tractorcow** [comment]
I'll probably attack this once alpha 3 is out.

**Comment by tractorcow** [comment]
Installer is successfully running this build on pgsql; This issue can be closed.

https://travis-ci.org/silverstripe/silverstripe-installer/jobs/249504137
