### ISSUE TITLE
Drag & drop movement of files

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-asset-admin#279]
## Acceptance criteria:

 - I can drag a file from the gallery into a folder which is in the same view 
 - I can drag a file into a folder from my desktop directly into a folder
 - If I have multi-select enabled, then dragging any of the selected files will move all selected files into the destination folder
 - A message is present with an indication of how many items have been moved if successful
 - If multiple items are moved and some cannot be moved (ie no permissions), then we move the items that can be moved and alert the user to which items could not be moved.

## Exclusions:

 - "Rectangle drag" based multi-select (nice-to-have / optional)
 - No drag & drop in mobile unless built into functionality as part of library

**Comment by clarkepaul** [comment]
See https://projects.invisionapp.com/boards/C3X68PKQ6M7Z/ for initial UX concept for dragging a single file into a folder and bulk selection of files (this would allow items to be dragged as a group and enable the bulk actions).

Multi-select would also be enabled for adding and removing items if multiple items are selected using "command + click" (mac) and respective shortcut for windows.

**Comment by flamerohr** [comment]
Griddle would either need a lot of hacking/tweaking to work, or a full replacement...
its behaviour is so weird... default wrapper is `<table>` with headers, but if you want to customise the row component, it goes all out and replaces the wrapper with `<div>` and no headers... Meaning, I won't be able to apply the necessary HOCs to the row/item without replicating all the Griddle-internal render logic.

**Comment by sminnee** [comment]
What if we just started with the gallery view and left the list view until later?

**Comment by flamerohr** [comment]
Sure, I've almost got all the kinks out for the Gallery view with drag and drop, it's working really nicely.
I suggest pulling the list view to a separate story for a more detailed investigation?

**Comment by clarkepaul** [comment]
![pasted_image_16_02_17__4_43_pm](https://cloud.githubusercontent.com/assets/555033/23006505/1f797f4e-f467-11e6-9587-18dbd2928831.png)

@flamerohr hopefully these aren't too late otherwise I can do some more styling during beta. From memory I have some styles for depth level (variations of shadow depths) and thats what .z-depth-x is.

**Comment by clarkepaul** [comment]
Also I think two layers communicates enough to say there is more than one item being dragged, the direction of the stacking is different from what you had though.

**Comment by flamerohr** [comment]
thanks @clarkepaul, not late at all :)
I have things setup similarly, so it'll be small tweaks from here, I haven't finished adding the "Files added here" indicator badge yet so that'll be first.

**Comment by flamerohr** [comment]
Pull requests:
https://github.com/silverstripe/silverstripe-asset-admin/pull/385
https://github.com/silverstripe/silverstripe-framework/pull/6634

**Comment by tractorcow** [comment]
Merged!
