### ISSUE TITLE
Can't scroll the file edit form in Firefox

### ISSUE THREAD

**Issue by ewweaver** [silverstripe/silverstripe-asset-admin#290]
Occurs in master.

Cannot scroll the file edit form in firefox.

Likely related to [silverstripe/silverstripe-framework#6170](https://github.com/silverstripe/silverstripe-framework/issues/6170)

**Comment by kinglozzer** [comment]
Looks related, adding fill-height to these classes seems to fix it: https://github.com/silverstripe/silverstripe-asset-admin/blob/cb6000cca4268f4bc07be92a1ee81cba7ffba62e/client/src/containers/AssetAdmin/AssetAdmin.js#L213

**Comment by ewweaver** [comment]
Looks like you can't scroll the main files view either. Just need enough thumbnails to go off the bottom of the page.

**Comment by flamerohr** [comment]
This seems have been fixed some time between when this issue was raised and now.

@ewweaver would you be able to confirm that you are able to scroll in Firefox now?

I seem to have no issues now, although some other visual issues in Firefox involving `<fieldset>` which is not related.

**Comment by ewweaver** [comment]
This issue looks resolved to me. I can now scroll both the main asset admin and the file edit form in firefox.
Closing this issue.
