### ISSUE TITLE
Insert Media modal button label

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-asset-admin#309]
If an existing image was selected, then the form button should show "Update" instead of "Insert", so it does not confuse the action of actually inserting the selected.

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-admin/pull/180
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/574

**Comment by phalkunz** [comment]
Pull request: https://github.com/silverstripe/silverstripe-asset-admin/pull/499

**Comment by flamerohr** [comment]
deferred this to beta2, as the fix presented currently was too complex for just a button label change

**Comment by flamerohr** [comment]
Doable with the form injector work now in place :)

**Comment by clarkepaul** [comment]
Isn't this issue irrelevant now that the images have a "Edit" and "Delete" action?

**Comment by clarkepaul** [comment]
Ah ignore my previous comment as I was thinking this issue was about the button to trigger the modal and not the action within the modal.
