### ISSUE TITLE
Asset-admin behat tests

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-asset-admin#311]
Recreate the behat tests here https://github.com/silverstripe/silverstripe-asset-admin/commit/1933fb0b375623861442f3b40746c09ca495801f
which was removed because they were for the old asset-admin and requires updating.

PRs:
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/326
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/6366

**Comment by tractorcow** [comment]
In progress:

Early framework PR at https://github.com/silverstripe/silverstripe-framework/pull/6366

Partially complete tests at https://github.com/open-sausages/silverstripe-asset-admin/commits/pulls/4.0/asset-admin-behat

**Comment by tractorcow** [comment]
See initial comment for PR links
