### ISSUE TITLE
Batch multiple delete queries

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#317]
It should be easy to implement [query batching](http://dev.apollodata.com/core/network.html#query-batching) without changes to the PHP side of things, but it's unclear how/if that works

**Comment by chillu** [comment]
Aaron's GraphQL scaffolding work will allow for this by default

**Comment by bergice** [comment]
Looks like this is done: ![image](https://user-images.githubusercontent.com/541886/94231866-f4f31e00-ff58-11ea-9af8-83a44aaa8749.png)
