### ISSUE TITLE
CMS as dependency

### ISSUE THREAD

**Issue by anselmdk** [silverstripe/silverstripe-asset-admin#319]
I Installed this on a framework only project as I wanted to administer assets from the backend, and saw that the entire cms module was installed, which in turn caused problems (e.g. `/admin` cannot be accessed because `Security` requires a `Page` class to be present). And in general I don't need the entire cms module on this project.
It it by design that this module needs cms or might this be an oversight?

**Comment by tractorcow** [comment]
At the moment the dependency is mostly a convenience to development... it would not be a lot of work to remove this. :) I think it's a good suggestion.

**Comment by flamerohr** [comment]
This has been fixed, I've got a framework-only project started and powering a single-page-app
CMS wasn't necessary for that project :)
