### ISSUE TITLE
Navigating down folders breaks sometimes (no folder title or back button)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#321]
This is supposed to be a nested folder (2 deep), Folder name and way back up the levels is missing. On refresh it returns an error. I tested this multiple times with the same result every time.
![pasted_image_1_12_16__11_43_am](https://cloud.githubusercontent.com/assets/555033/20774640/11d918a0-b7bc-11e6-9b6c-13f12a842b2b.png)
![pasted_image_1_12_16__11_42_am](https://cloud.githubusercontent.com/assets/555033/20774644/1808c2ac-b7bc-11e6-9283-ecb336a76e78.png)

**Comment by wilr** [comment]
Have retested this against the latest master for the last 10 minutes. Reviewed with Paul and believe this is fixed in master.
