### ISSUE TITLE
Save and publish buttons are not joined or showing the current state of file

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#324]
## Acceptance criteria

 * The buttons in the file details form use the style indicated below
 * <strike>When content is changed-in-draft / unpublished the button state change as indicated below</strike> (addressed in https://github.com/silverstripe/silverstripe-framework/issues/6683)

This can be a solution specific to asset-admin-file-details-form

----

The file actions should replicate the behaviour of pages save and publish buttons (the CSS/design is still outdated though):
Files buttons:
![image](https://cloud.githubusercontent.com/assets/555033/20912590/2e7f042a-bbd5-11e6-8dbb-149f3860c29e.png)

Pages buttons:
![image](https://cloud.githubusercontent.com/assets/555033/20912605/46169a8a-bbd5-11e6-926a-845362e87c87.png)

----

## Dependencies

 * https://github.com/silverstripe/silverstripe-framework/issues/6683

## Tasks

 * [ ] Group buttons
 * <strike>Update status of button, use colour and icons as per pages buttons</strike> (addressed in https://github.com/silverstripe/silverstripe-framework/issues/6683)
 * [ ] ...

**Comment by tractorcow** [comment]
Yes they should be joined. Shouldn't be too hard to  fix. ;)

**Comment by clarkepaul** [comment]
Just needs a surrounding div around the two actions [save|publish] with the class .btn-group
![image](https://cloud.githubusercontent.com/assets/555033/24126311/203bc6e6-0e32-11e7-9083-fbfca083c8c3.png)
