### ISSUE TITLE
Wrong Aria used for "More options" popover, references missing id

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#334]
~~Pretty sure the button to trigger the popover should use aria-owns, or aria-controls rather than aria-describedby. ~~ It seems the aria described by is being used correctly from what others say although I'm not really sure that it is the best use of that aria.
Either way this button shows as an accessibility issue as the button references an id which doesn't exist in the markup (due to react popover).

I think its best to not set aria-describedby unless the referenced element is in the DOM, otherwise perhaps with the addition of aria-hidden="true" might work?
![image](https://cloud.githubusercontent.com/assets/555033/21243393/881fb0f6-c37d-11e6-919d-d578dd03a046.png)

## Pull requests

- [x] https://github.com/open-sausages/react-bootstrap/pull/1/files
- [x] Publish to npm and update yarn.lock for Admin
- [x] https://github.com/silverstripe/silverstripe-admin/pull/51

**Comment by chillu** [comment]
Pointers on how to fix: `getPopoverMenu()` in `FileFormFactory.php` creates this menu. The `PopoverField.js` renders it

**Comment by phalkunz** [comment]
Actually, this is done by `react-bootstrap` (https://github.com/react-bootstrap/react-bootstrap/blob/v0.30.6/src/OverlayTrigger.js#L266)
