### ISSUE TITLE
PHPDoc for GraphQL classes in asset-admin

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#343]
Split out from https://github.com/silverstripe/silverstripe-asset-admin/issues/316

PR:
 - [ ] https://github.com/silverstripe/silverstripe-graphql/pull/55

**Comment by tractorcow** [comment]
Begun this work at:
 - https://github.com/open-sausages/silverstripe-asset-admin/tree/pulls/4.0/graphql-docs
 - https://github.com/open-sausages/silverstripe-graphql/tree/pulls/4.0/graphql-docs
