### ISSUE TITLE
Pagination stays in place between folders

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#345]
If you navigate to the second page of the root folder (`admin/assets/show/0?page=2`), then navigate to a subfolder (e.g. `admin/assets/show/99?page=2`), the `page` query param stays in place. If the subfolder doesn't have pagination going that far, you'll see an empty page.

Reproduce:
 * Set AssetAdmin.page_length=2
 * Create three folders in root
 * Go to third folder (second pagination page)
 * Upload a file there
 * Reload page (with `?page=2`). The file will disappear

**Comment by chillu** [comment]
PR at https://github.com/silverstripe/silverstripe-asset-admin/pull/347

**Comment by chillu** [comment]
Fixed as part of the search+graphql refactor in https://github.com/silverstripe/silverstripe-asset-admin/pull/330/

**Comment by flamerohr** [comment]
@chillu I don't see the changes in #330, was it removed due to a rebase?

**Comment by chillu** [comment]
Damn, you're right, this isn't fixed! I'll have a look at it early arvo (meeting from 1:30 to 2:30)

**Comment by flamerohr** [comment]
I've cherry picked the commit over, looked good anyway :)
