### ISSUE TITLE
Show message when current folder or file record can't be found

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#349]
When opening `admin/assets/show/1`, if a Folder with `ID=1` doesn't exist, it simply shows an empty screen - not great. We should display a friendly error message, with an option to navigate to the root folder.

Note that this is different from a file not being found in the "edit file" preview (see https://github.com/silverstripe/silverstripe-asset-admin/issues/265)

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/446
- [x] https://github.com/silverstripe/silverstripe-admin/pull/41

**Comment by flamerohr** [comment]
The issue is GraphQL doesn't provide an indication that loading has started/stopped, and so even though it has finished loading, the components that are connected to GraphQL still thinks it's loading data.

**Comment by clarkepaul** [comment]
When does admin/assets/show/1 get used except when you click on on the actual folder, I must be missing something as navigating to the files area takes you to admin/assets/.
