### ISSUE TITLE
Sorting symbol still showing for sort-disabled columns

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-asset-admin#351]
See screenshot, sorting is disabled for the Size column, but the symbol still shows
![screen shot 2017-01-09 at 1 42 30 pm](https://cloud.githubusercontent.com/assets/1064889/21755067/bd8060fe-d671-11e6-978a-0be3871f3445.png)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-asset-admin/pull/388
