### ISSUE TITLE
Localise date display in search, table view and edit view

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#356]
CMS authors can set a preferred date, and CMS projects infer the best date format based on the chosen locale. That's rarely the technical ISO format (YYYY-mm-dd). GraphQL response formatting shouldn't be specific to the currentMember context, so we should try to format this in JS on the client. Which means finding a JS date library which can handle the ISO date strings we configure through `i18n.php`

![image](https://cloud.githubusercontent.com/assets/111025/21761622/0f3c902e-d6b9-11e6-9fb5-6758c21ef84c.png)

**Comment by bergice** [comment]
Looks like the search result notice is not even rendered anymore. Maybe this happened with the GraphQL rework or something?

See: `Gallery.render` and `Gallery.getSearchMessage`.

**Comment by dhensby** [comment]
It looks like this should be quite simple using `moment` (https://momentjs.com/docs/#/customization/)

**Comment by chillu** [comment]
If we're already using momentjs, then let's not change that. But if we don't, let's not start. momentjs is a big include, and last I checked wasn't easy to break down via bundlers. Google Lighthouse tooling recommends against using it now for this reason.

**Comment by maxime-rainville** [comment]
The search result notice got removed when we redid the search around SS4.2. I think we can probably close this.
