### ISSUE TITLE
Search: date range search has an incorrect label or searches an incorrect field

### ISSUE THREAD

**Issue by mikenz** [silverstripe/silverstripe-asset-admin#363]
In the search box, there is a search for "Last changed" and date range fields. This searches the Created field, not LastEdited field. 
`"childrenFilter":{"createdFrom":"2017-01-01","recursive":true}`

https://github.com/silverstripe/silverstripe-asset-admin/blob/master/code/Forms/FileSearchFormFactory.php#L92

Either change the label to match the functionality, or the functionality to match the label?

**Comment by mikaelayoung** [comment]
This seems to be fixed already, it is now searching by LastEdited.

**Comment by mikaelayoung** [comment]
Merge request: https://github.com/silverstripe/silverstripe-asset-admin/pull/442
