### ISSUE TITLE
Bulk action delete triggers view switch

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-asset-admin#367]
Deleting a file or folder causes the view to change back to default gallery/thumbnail view, when it should stay in list/table view.

Deleting item(s) should also preserve all display queries:
- Pagination
- Sorting
- Search
- Filter
- ...

## Excludes:

- Deleting last item(s), user shouldn't see an empty page (https://github.com/silverstripe/silverstripe-asset-admin/issues/466)

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/463

**Comment by chillu** [comment]
Confirmed this is still an issue.

**Comment by phalkunz** [comment]
This also happens with single item deletion as well.
