### ISSUE TITLE
UploadFile api does not check for conflicts

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-asset-admin#369]
Paraphrasing @tractorcow 
This is an issue where saving a file in asset-admin wasn't safely ensuring the name was unique
The asset store does a file-exists uniqueness check, but there's a case where a File dataobject with a missing physical file would not trigger a conflict.

So we need to enforce uniqueness against:
- Filename against all File dataobjects
- Filename and Hash against the actual file store

**Comment by tractorcow** [comment]
WIP fix at https://github.com/open-sausages/silverstripe-asset-admin/commits/pulls/4.0/fix-replace-setname

**Comment by tractorcow** [comment]
Original acceptance criteria: https://github.com/silverstripe/silverstripe-asset-admin/issues/295

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-asset-admin/pull/370.

Note: We aren't retaining same URL anymore for replacing existing file with same name + sha.
