### ISSUE TITLE
Add missing npm modules for 'run build' and 'shrinkwrap'

### ISSUE THREAD

**Issue by zacps** [silverstripe/silverstripe-asset-admin#372]
`npm run build` requires `dropzone` and `griddle-react` neither of which are specified in `package.json`.
`npm shrinkwrap` requires `react-addons-css-transition-group`

**Comment by flamerohr** [comment]
Closing, as the packages mentioned are defined in the `dependencies` and not the `devDependencies`

@zacps please check your npm installation, may possibly require deleting your `node_modules` folder in your framework module and afterwards `npm install` again
