### ISSUE TITLE
Longer folder names break the line too early

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#377]
![Example](https://cloud.githubusercontent.com/assets/5170590/22311145/01c33c1c-e3b7-11e6-8607-d7038d677be5.png)

`width: 100%` on `.breadcrumb__container.fill-height` looks better, but not sure if the width is calculated before the heading is added by React?

**Comment by chillu** [comment]
@flamerohr Did you work on this recently?

**Comment by flamerohr** [comment]
@chillu yes, it was fixed with this commit https://github.com/silverstripe/silverstripe-asset-admin/commit/acad82e83a34753a7e29e341a1ca68b99f6324e9#diff-41a10865fddf84ea88caf079f650dc07R1570
The Search component styles were broken which caused this regression.
