### ISSUE TITLE
Fix README (still references "asset gallery field")

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#379]
It's way outdated, from the time when we intended this module to be a form field only. Update with a proper description what this module does.

## Pull requests 
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/677

**Comment by sminnee** [comment]
Documentation can be left post-beta1.

**Comment by robbieaverill** [comment]
Can we add an instruction to ensure yarn is used instead of npm for anyone who doesn't know that (me) - reference #530
