### ISSUE TITLE
PHP Fatal error:  Class SilverStripe\AssetAdmin\GraphQL\ReadFileQueryCreator contains 1 abstract method and must therefore be declared abstract or implement the remaining methods 

### ISSUE THREAD

**Issue by KINKCreative** [silverstripe/silverstripe-asset-admin#383]
It seems that for `/code/GraphQL/ReadFileQueryCreator.php` the method $this->connection() should actually be named `createConnection()` to fulfill the abstract method  of `SilverStripe\GraphQL\Pagination\PaginatedQueryCreator::createConnection`.

Otherwise, the asset admin on 4.0.0x-dev stays blank with the above error.

**Comment by mikenz** [comment]
Fixed in https://github.com/silverstripe/silverstripe-asset-admin/pull/382 when it gets merged
