### ISSUE TITLE
Asset gallery not loading due to missing abstract method

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-asset-admin#393]
No assets loading on my site, error thrown is:

```
[Sat Feb 25 15:09:23.411183 2017] [:error] [pid 23412] [client 79.71.182.51:51883] PHP Fatal error:  Class SilverStripe\\AssetAdmin\\GraphQL\\ReadFileQueryCreator contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (SilverStripe\\GraphQL\\Pagination\\PaginatedQueryCreator::connection)
```

As the `ReadFileQueryCreator` is missing the `connection()` method.

Using dev-master - e94844f4e2b6415510d1d487dc0077a44012376c
GraphQL 0.2.0 - 3309fc7c8395f75de8b226fa0d6d24c1d24883c2

Looks like a regression for 1.0.0-alpha4.

**Comment by chillu** [comment]
That's been fixed since
