### ISSUE TITLE
Wrong folder open for opened file

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-asset-admin#396]
This happens in particularly with InsertMediaModal, where you have a file selected to modify attributes for.

It will open the file properly in the Editor, but you cannot save the modified data because the Gallery has the wrong folder open (some metadata relies on the proper data being loaded in the Gallery view)

Potential fix is remove the reliance on the Gallery view data and have all data ready in the Editor.
Alternatively, could setup a check and redirect if in a folder which doesn't contain the opened file. I find the former better because of its decoupling from Gallery.

Fix at https://github.com/silverstripe/silverstripe-asset-admin/pull/429

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-asset-admin/pull/429
