### ISSUE TITLE
UploadField missing canUpload option

### ISSUE THREAD

**Issue by mikenz** [silverstripe/silverstripe-asset-admin#399]
\SilverStripe\Forms\UploadField had a canUpload option that allowed the field to only be used to select from already uploaded assets.

\SilverStripe\Forms\UploadField has been removed and it's replacement, SilverStripe\AssetAdmin\Forms\UploadField, doesn't have a way to restrict users to only selecting from existing assets.

# PRs:

 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/732

**Comment by tractorcow** [comment]
@mikenz PR at https://github.com/silverstripe/silverstripe-asset-admin/pull/732

you can also disable the modal if you need.
