### ISSUE TITLE
Page with UploadField loses file association upon saving from another tab

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-asset-admin#400]
## Summary

A `Page` subclass has an `UploadField` on it's Main tab, and additional fields on a second tab.  Upon saving while the second tab is active, the association is stored.  However, saving a second time from the second tab, the association is lost.

## Steps to Reproduce

1. Create a `Page` or `SiteTree` subclass with an `UploadField` on the main tab, and some other fields on second tab.
2. Upload a file via the `UploadField` on the main tab.
3. Switch to the second tab.
4. Save the record.
5. Save the record once more.

## Expected Results

The file association remains in place after saving multiple times while other tabs are active.

## Actual Results

The file association has vanished!

## Environment

- SilverStripe 4 `dev-master`
- PHP 5.6.29
- Apache 2.4.23 (x64)
- Firefox Developer Edition 54.0a2 (2017-03-12) (x64)
- Windows 10 Pro x64 1607 Build 14393.693

**Comment by mikenz** [comment]
We're reliably seeing this too.

**Comment by mikenz** [comment]
Not sure if it's the proper fix, but it's what we're doing in the mean time:

```
diff --git a/client/src/entwine/UploadField/UploadFieldEntwine.js b/client/src/entwine/UploadField/UploadFieldEntwine.js
index b131e3e..d1fd235 100644
--- a/client/src/entwine/UploadField/UploadFieldEntwine.js
+++ b/client/src/entwine/UploadField/UploadFieldEntwine.js
@@ -12,7 +12,7 @@ jQuery.entwine('ss', ($) => {
   /**
    * See boot/index.js for `.react-boot` bootstrap
    */
-  $('.js-react-boot input.entwine-uploadfield:visible').entwine({
+  $('.js-react-boot input.entwine-uploadfield').entwine({

     onunmatch() {
       this._super();
```

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-asset-admin/pull/428

**Comment by phalkunz** [comment]
I have already looked and approved the pull request but it still needs to be merged in.

**Comment by flamerohr** [comment]
@phalkunz thanks for the reminder, perhaps ping us on Slack or comment on the PR (sorry if I had missed it)
