### ISSUE TITLE
Change icon in asset list view for missing file

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#402]
In SSv4: A simple switch out of the icon to something more meaningful so that it doesn't look like it is a delete action.

![image](https://cloud.githubusercontent.com/assets/555033/24125555/250c825e-0e2e-11e7-9005-7fe70a3ce1e4.png)

Replace with:
![image](https://cloud.githubusercontent.com/assets/555033/24125562/30cbb02e-0e2e-11e7-9d7a-f353aeaf5771.png)

The new icon will need to be added to the repo.

**Comment by chillu** [comment]
Pointer on how to fix this: `TableView.js` takes care of rendering the rows, you'll want to look at `renderThumbnail()`

**Comment by phalkunz** [comment]
This is assigned to Mikaela Y.

**Comment by mikaelayoung** [comment]
PR https://github.com/silverstripe/silverstripe-asset-admin/pull/437
