### ISSUE TITLE
Improvements to selecting/dragging and moving of files

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#424]
# Acceptance criteria

* When a file is being dragged the cursor should change from a pointer to a drag cursor. 
* Fade-out/remove original file being dragged in original location and fade-in the file attached to the cursor (too much emphasis on the old place and not enough on the file being dragged).
* Improve the highlighting of the drop-zones (back up folder, into folders) as they are hidden.
* Include intuitive keyboard interactions and commands for selecting items.
  * Cmd (Mac) or Ctrl (PC) and select to check/uncheck items
  * Select start, hold shift and select end item to select all items in between
* ~~Include a drag to select area option for selecting multiple items.~~ (tracked in https://github.com/silverstripe/silverstripe-admin/issues/127)

# Designs
Interactive prototype: https://invis.io/27C0T40G4#/237327492_Drag_N_Drop_Select
Flat style guide: ?

# Notes

 * Drag and drop of list items out of scope?
 * See [Add multi-select shortcuts for dragging files](https://github.com/silverstripe/silverstripe-admin/issues/127)

# Tasks
- [ ] Design review after development

# Pull requests
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/738

**Comment by flamerohr** [comment]
Pointer: css rules to apply the correct cursor
Might need a boolean prop for `GalleryItem` to indicate that dragging is happening, so that it knows to face out.
This may require some jumping around, or maybe my I'm overestimating the complexity.

I've changed the effort required to reflect the slight difficulty that this could present

**Comment by flamerohr** [comment]
@newleeland Some feedback, I agree with the first three points, it really needs an improvement there... what do you think about reducing the size of the items being dragged? That way it'd make it easier to make the folder areas easier to highlight/interact with.

About the keyboard/additonal interactions:
> Cmd (Mac) Cntrl (PC) and select to check/uncheck items

Are you talking about checking anywhere on the tile? So if the user is holding down ctrl/cmd and click on the thumbnail, it wouldn't open the file but instead select/deselect it?

> Select start, hold shift and select end item to select all items in between

I kind of wonder if this is still relevant with the select-box implemented...
This one is going to be tricky to understand what behaviour we would want, let alone implement.
So say we have this grid of items in the gallery:
```
  1  |  2  |  3  
  4  |  5  |  6
  7  |  8  |  9
```
If we clicked `1`, held shift and clicked `7`, would it select `1, 4, 7` or `1, 2, 3, 4, 5, 6, 7`? Considering responsiveness and how tile placements can be unpredictable, the first scenario would be trickier to implement (also covered by the select-box work), and the second may not be intuitive to the user?

**Comment by newleeland** [comment]
@flamerohr Thanks for the feedback. 

**Smaller drag visuals**. Yep, the prototype has a smaller drag graphic.

Ctrl/Cmd Select. Yes we would want to check by clicking the whole tile, as it would be much easier pressing the whole tile. Additionally, wouldn't make much difference if the user had to hold the Ctrl/Cmd and check the checkbox (from what it is now). Your thoughts @clarkepaul?

Shift checking would be `1, 2, 3, 4, 5, 6, 7` ideally, this is a design pattern that you see in google drive and windows

**Comment by clarkepaul** [comment]
@newleeland fyi we need to remove the drag-drop on the list view from those mocks.

**Comment by clarkepaul** [comment]
Related issue https://github.com/silverstripe/silverstripe-asset-admin/issues/605

**Comment by chillu** [comment]
Table rendering might be a blocker for getting DnD done in list view. @unclecheese has mentioned that a refactor from `<table>` to `<ul>` might be beneficial, e.g. for better responsive rendering. If that's required to implement DnD for the list, we'll have to split out to another card.

**Comment by unclecheese** [comment]
I have researched this a bit. It's a well-known issue. It's not something that ReactDND can fix, as IE/Edge are missing critical APIs for changing the `dragLayer`. If you try the React DND [demo site](https://react-dnd.github.io/react-dnd/examples-customize-handles-and-previews.html) in Edge, you'll see the preview images don't work there either.

This isn't worth pursuing, IMO.

**Comment by chillu** [comment]
IE strikes again! Happy to leave it

**Comment by unclecheese** [comment]
s/IE/Edge

**Comment by clarkepaul** [comment]
Great! I see the design review task hasn't been checked yet, I presume we need to check out the latest from master or has it been through a review with @newleeland ?

**Comment by flamerohr** [comment]
It has been through review with @newleeland ;)

**Comment by clarkepaul** [comment]
Nice I'll check the task then
