### ISSUE TITLE
Saving files causes JS errors in firefox only

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#430]
Caused by https://github.com/silverstripe/silverstripe-asset-admin/pull/415

Error is `TypeError: "_d" is read-only`

**Comment by tractorcow** [comment]
@flamerohr can you look at this please?

**Comment by flamerohr** [comment]
yeah, I'll look into it, that's weird...

**Comment by flamerohr** [comment]
Fixed by https://github.com/silverstripe/silverstripe-asset-admin/pull/431
