### ISSUE TITLE
Make asset-admin usable without the cms and campaign-admin dependencies

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-asset-admin#450]
Asset admin should be usable without having to install `cms` and `campaign-admin`. 

composer.json lists these as requirements, but from a first glance, these modules aren't really required for asset-admin to work. Deleting the folders manually doesn't cause any errors, except that the **Add to campaign** button no longer works (just opens an empty dialog):

![Add to campaign button](https://cloud.githubusercontent.com/assets/1006185/25489674/d64ed54a-2b6a-11e7-8187-1791606c0695.png)

Is this the only part of asset-admin that relies on `campaign-admin`? Why is there a `cms` requirement?

**Comment by flamerohr** [comment]
Good point, and worth starting an investigation into :)
Off the top of my head, Campaigns is primarily for that button... in retrospect, that actually could be moved to either campaign-admin as an extension or have a condition to check for campaign-admin's existence.
I don't remember why cms was needed, so investigating will help understand this.

**Comment by bummzack** [comment]
Small update on this:

- Tests run successfully, even without `cms` or `campaign-admin`
- I checked the JS dependencies and it appears as if there's no dependency to components from CMS. If I overlooked something and cms is indeed a dependency because of JS, then it should probably be included as a dev-dependency.
- It seems like the required extensions are already in place to extend the form actions.

Here's my proposed set of changes:

- Remove the `cms` and `campaign-admin` dependencies from `composer.json`
- Remove the `getAddToCampaignAction` from `FileFormFactory` and adjust `FileFormBuilderTest` accordingly.
- Add the action that was previously added via `getAddToCampaignAction` via an extension (this extension would become a part of `campaign-admin`).
- Probably also move the translation key `SilverStripe\\AssetAdmin\\Controller\\AssetAdmin.ADDTOCAMPAIGN` over to `campaign-admin`.

Thoughts?

**Comment by flamerohr** [comment]
Sounds good to me :)

I think that covers pretty much everything
I'd just cover off to probably leave cms as is (or minimal changes) and focus these change for only asset-admin.
I would be keen to see how you look to tackle campaign-admin checks for asset-admin to add the "Add to Campaign" button, as they no longer have any dependency on each other after these changes happen.

**Comment by bummzack** [comment]
CMS would be untouched. I'd just remove the dependency from `asset-admin/composer.json`.

I'm not sure what you mean by:
> so a config to define an extension may get sticky

Do you think solving it via Extension is problematic? Maybe the `campaign-admin` could even be left untouched and the extension could also be part of `asset-admin`, adding it in such a way:

```yml
---
Only:
  moduleexists: 'silverstripe/campaign-admin'
---
SilverStripe\AssetAdmin\Forms\FileFormFactory:
  extensions:
    - 'SilverStripe\AssetAdmin\Extensions\CampaignAdminExtension'
```

That way the button(s) would be added via extension, if the campaign-admin module is present. IMHO it's a cleaner architecture than solving it via conditions in PHP code.

**Comment by flamerohr** [comment]
Ah, that's a good idea, I completely forgot about the `moduleexists` condition
