### ISSUE TITLE
Pregenerate thumbnails on Upload

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#462]
## Acceptance Criteria

 * I can avoid large processing delays from batch generating thumbnails
 * I can upload a dozen images and view them immediately afterwards in the gallery view without unexpectedly long delays
 * Thumbnails exist immediate after upload
 * When uploading a file, we do not re-request a server thumbnail if one has been generated locally that can be used

## Notes

 * This is a SS3 problem rather than created through protected files
 * Client-side thumbnail generation of upload is already in place

**Comment by tractorcow** [comment]
Seems already implemented. AssetAdmin::getObjectFromData() is called on upload which generates thumbnails.
