### ISSUE TITLE
SS4 Ability to use real file locations in asset admin

### ISSUE THREAD

**Issue by tazzydemon** [silverstripe/silverstripe-asset-admin#464]
The new file management system seem to have real filesystem folders in existence but the files within those folders are abstracted for versioning. Personally I don't like this and I am wondering if the following might be a good idea:

1. Have the published file available as a real file, where it should be and copied there by the versioning choice made by the user.

2. Notwithstanding whether (1) is practical (and I think it is a jolly good idea) we need a way to copy extant file structures and have them brought into the SS4 file environment. This is possible on SS3 below

Clearly (2) would require removing the file from its original location if (1) was not enabled.

**Comment by mikenz** [comment]
What you're after is "legacy filename behaviour". 
https://github.com/silverstripe/silverstripe-assets/blob/master/src/Flysystem/FlysystemAssetStore.php#L55
We use it in production, it works without issue for us. I'm not sure if it's in any documentation.

**Comment by tazzydemon** [comment]
Awesome, thanks.
