### ISSUE TITLE
Asset area minor polish, thumbnail sizing and icon/text improvements

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#470]
Thumbnails in list view are not square (currently taller than wide, suggest 68px width and height)

Thumbnail hover text to update to "Details" so that with the icon it reads more like "Edit details" rather than "Edit view"
<img width="138" alt="pasted_image_10_05_17__5_33_pm" src="https://cloud.githubusercontent.com/assets/555033/25884499/fc345cd0-35a6-11e7-8387-07956fb9873b.png">

The wrong icon is used for image enlarge, it should use magnify icon rather than search icon. There are duplicate icons for enlarging which I will raise a separate issue for but icon can be updated in the centre of the image.

**Comment by chillu** [comment]
@newleeland @clarkepaul Can you please review this? Looks like the second and third items are fixed already?

**Comment by clarkepaul** [comment]
Yeah, I think this can be closed, seems the pull request has been merged and this issue not closed. I will raise the outstanding issue but from memory, there was still debate about the preferred viewing of thumbs in list view.
