### ISSUE TITLE
Existing files in UploadField should allow opening of edit view

### ISSUE THREAD

**Issue by feejin** [silverstripe/silverstripe-asset-admin#483]
When uploading an image for example, SilverStripe 3 has an "edit" option for inline editing of the file attributes. This is an important feature for accessibility, SEO etc. I also rely on it heavily for extensions such as focus point. Please bring it back in beta 2.

## Pull requests:
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/607

**Comment by sminnee** [comment]
Have you seen this on SS4 or SS3.6?

**Comment by feejin** [comment]
This was on a SilverStripe 4 dev-master branch from last week that @kinglozzer set up for internal testing. 
![screen shot 2017-05-22 at 09 28 19](https://cloud.githubusercontent.com/assets/1774129/26298986/11ae7806-3ed1-11e7-81c4-864821cf75b0.png)

**Comment by chillu** [comment]
At the very least, we need to link to the edit view in `admin/assets` here. At the moment, you can't even tell which folder the file is in.

I agree that in-context editing of attached files was a strong point of the old upload field. It was also adding a lot of complexity. We should probably try to reuse the existing React UI components as much as possible for this.

@clarkepaul Can you please have a think on how you'd see this working?

**Comment by clarkepaul** [comment]
Upload fields were designed to be selectable (opens the Files area with item selected in a modal) see https://projects.invisionapp.com/boards/VGX68PKC7PYB/ 
I don't recal the implementation of this so I'm not sure if it has broken since developemnt or wasn't included in the acceptence criteria. 

Outstanding designs (which I have noted):
- If a user doesn't have view/edit permissions of a file
- If a user doesn't have permissions to use/see the files area at all
- Error/success messages

**Comment by tractorcow** [comment]
@clarkepaul at the moment the insert / select media modal has this form:

![image](https://user-images.githubusercontent.com/936064/29647207-288a3330-88dc-11e7-9a48-46e0fc71ab33.png)

**Comment by clarkepaul** [comment]
@tractorcow Clicking an uploadfield item opens it in the Files area modal as you have pictured, nothing different really—same experience as far as I can see. Although I didn't realise we open the file in a new tab/window when editing the original but that is a separate issue and probably makes sense to leave as is until we have the "Usage" tab back again where people can link back to where it's used.

**Comment by clarkepaul** [comment]
Ah yeah and don't forget hover states on the uploadfield item :)

**Comment by chillu** [comment]
> Clicking an uploadfield item opens it in the Files area modal as you have pictured, nothing different really—same experience as far as I can see

Huh, I can't see it doing that. You can select "add from files" when no file is selected in the uploadfield. But once a file is selected, there's no way to get to any more detail on it than viewing the name. I've changed the title to reflect this: "Existing files in UploadField should allow opening of edit view"

**Comment by tractorcow** [comment]
I would suggest building in an "edit" button, so that the user is aware of the action being performed, prior to actually opening the modal. @clarkepaul do you want to think about how this interface should look? Perhaps a button next to the "x" for remove?

**Comment by clarkepaul** [comment]
The whole item should be clickable (with hover state and cursor change). Can we see if that makes sense without the edit icon for now, as I think eventually we will replace the "X" action to options "..." which will hold all actions (edit, remove... and any other action) in one place.

**Comment by flamerohr** [comment]
I would suggest the "edit" button would re-open the modal for that given file, but it'd be the same interface which @tractorcow has shown.
This will allow the user to switch to another image if they wanted, but the details of the image will require clicking the "Edit original file" button.
