### ISSUE TITLE
Upload replacement button out of alignment

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-asset-admin#486]
The button isn't stickied to the right side of the preview panel when the preview is missing, it's fine when the preview exists

![screen shot 2017-05-23 at 11 15 31 am](https://cloud.githubusercontent.com/assets/1064889/26332197/48548264-3fa9-11e7-9c58-0ad06abb164d.png)

**Comment by sachajudd** [comment]
Closing as the 'Replace file' action has since been moved to the more options menu.
