### ISSUE TITLE
Reduce the sort dropdown label to an icon for smaller screens

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#496]
Requires https://github.com/silverstripe/silverstripe-admin/issues/100 to be done first. 
[< 768px] Reduce sort dropdown in assets to icon so that it fits on smaller screens.
![image](https://cloud.githubusercontent.com/assets/555033/26616244/45857ec0-4621-11e7-9450-7bdb4493891c.png)

@clarkepaul to provide guidance on icon, he will provide an updated icon set with a new icon as part of this issue.

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/507
- [x] https://github.com/silverstripe/silverstripe-admin/pull/113

**Comment by clarkepaul** [comment]
@phalkunz this would be the next issue, I will sort the icon set for you.

**Comment by tractorcow** [comment]
I've tested and works fine. Please merge on green.
