### ISSUE TITLE
Folder Location doesn't reflect where the asset item is. It just says “Loading…”

### ISSUE THREAD

**Issue by phalkunz** [silverstripe/silverstripe-asset-admin#518]
## Problem
The folder location dropdown finishes loading but the "loading..." label does not update with the proper location information.

## Acceptance Criteria
* When a user navigates to either a folder or a file, the location field displays the current location once the data has been received
* While waiting for the location path to load and display in the field, the value of the field is "Loading..." and the field is read-only.

![silverstripe_-_files](https://user-images.githubusercontent.com/318116/27776496-3327040e-5fff-11e7-9e31-db9b4895caed.png)

## Tasks
* [ ] Task out this issue

**Comment by chillu** [comment]
I can't reproduce this - do you have a lot of folders, or any other specialities in your setup?

**Comment by clarkepaul** [comment]
@phalkunz can you confirm this is still the case.

**Comment by clarkepaul** [comment]
I don't see this so will confirm again with @phalkunz

**Comment by phalkunz** [comment]
@chillu @clarkepaul "Loading..." disappear after the loading but the field still show wrong detail. Have a look at my new screenshot.

**Comment by clarkepaul** [comment]
Cheers, okay we need to prioritize this then.

**Comment by flamerohr** [comment]
@phalkunz could you confirm that this is still happening?
TreeDropdownField has been through a fair amount of refactor before the Beta2 release, and I'm unable to reproduce it

**Comment by phalkunz** [comment]
I did a re-test and here's the screenshot:

![silverstripe_-_files](https://user-images.githubusercontent.com/318116/29048569-83be7d56-7c25-11e7-981c-539f09e643cf.png)

**Comment by flamerohr** [comment]
sorry @phalkunz, but still unable to reproduce this issue :( Folder shows properly in the Folder location field as well...
Has anyone else been able to reproduce this? @unclecheese @tractorcow @clarkepaul

**Comment by phalkunz** [comment]
I'll close this now since no one can replicate it.
