### ISSUE TITLE
Replacing the wrong file when Bulk action mode

### ISSUE THREAD

**Issue by phalkunz** [silverstripe/silverstripe-asset-admin#522]
Steps to reproduce:
  * Start with 3 images
  * Select the first (checkbox) 2 items
  * Click the third image (not selected for bulk action)
  * Replace the third image with a new image and 
  * You’ll see the second image get replaced instead of the third one

**Comment by tractorcow** [comment]
@phalkunz I suspect this could actually be replacing the correct file, but is re-ordering the files dynamically due to a rename (replacing the file adjusts the "Name" field, which is the default sort).

can you please confirm this?

**Comment by phalkunz** [comment]
@tractorcow Re-tested and found out it actually replaced the correct file.
