### ISSUE TITLE
Batch move files

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#523]
## Acceptance Criteria

 * I can move multiple selected files and folders in the current view into a folder of my choice
 * When a folder is contained in the selection, all contained files and folders will be moved as well
 * The folder does not need to be a direct subfolder of the currently displayed folder
 * There is error feedback when I don't have the permissions to move one or more selected files
 * The solution performs well with all ~20 items items on a page selected
 * There is a loading indication while the request processes

## Excludes

 * Selecting items beyond a single paginated file page

## Notes

 * Split out from https://github.com/silverstripe/silverstripe-admin/issues/128
 * See designs https://projects.invisionapp.com/boards/2JX68PNPDF6K/

## Related

 * [Batch add to campaign](https://github.com/silverstripe/silverstripe-asset-admin/issues/524)
 * [Batch publish and unpublish](https://github.com/silverstripe/silverstripe-asset-admin/issues/525)
 * [Batch move](https://github.com/silverstripe/silverstripe-asset-admin/issues/523)

**Comment by chillu** [comment]
@unclecheese Didn't you implement this already? Can you check the implementation against the ACs here?

**Comment by unclecheese** [comment]
Confirmed that https://github.com/silverstripe/silverstripe-asset-admin/pull/592 meets all of the acceptance criteria.
