### ISSUE TITLE
Batch publish and unpublish of assets

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#525]
## Acceptance Criteria

 * I can add publish or unpublish multiple selected files in the current view
 * The option is not available when folders are selected
 * The publication indicator on file thumbnails reflects the publication state after the action is performed
 * If a currently viewed file is included, the indicators on this details view reflect the publication state as well. This includes button messages e.g. ("✓ saved | ✓ published") for publishing item
 * There is error feedback when I don't have the permissions to change one or more selected files
 * The solution performs well with all ~20 items items on a page selected
 * There is a loading indication while the request processes
 * If mixed states are selected (both published and draft items), both publish and unpublish actions are available and will silently skip files where the action isn't applicable

## Excludes

 * Selecting items beyond a single paginated file page

## Notes

 * Split out from https://github.com/silverstripe/silverstripe-admin/issues/128
 * See designs https://projects.invisionapp.com/boards/2JX68PNPDF6K/
        * Consider loading of files and mobile access to the actions

## Related

 * [Batch add to campaign](https://github.com/silverstripe/silverstripe-asset-admin/issues/524)
 * [Batch move](https://github.com/silverstripe/silverstripe-asset-admin/issues/523)

## Pull Requests
- [x] https://github.com/silverstripe/silverstripe-admin/pull/226
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/614

**Comment by newleeland** [comment]
@unclecheese not sure if you'd be the man for this as you did the batch move. Would this be a viable solution? https://invis.io/3RD5LSAJE#/249886653_Files_-_Edit_File_-_Batch_Publish

**Comment by chillu** [comment]
@newleeland I don't like the complexity of the two-step flow for the mixed state (selecting both draft and published items shows both "publish" and "unpublish", then only shows one or the other). I think that the initial view is correct (shows both "publish" and "unpublish"), but when you trigger one of these, the batch actions simply disappear after completion. Makes both the UX and the implementation simpler. Do you think that's viable?

**Comment by newleeland** [comment]
@chillu At the moment the actions only appear when item(s) are checked, If we are to remove the actions after batch publish/unpublishing, we'll need to uncheck the items and provide some sort of confirmation notification of success or failure. (the current design avoids the confirmation notification, by using the checked visuals indicators to bring focus and show the user the changing of state i.e. draft>publish and vice versa).

I thought leaving the items checked after publishing/unpublishing action (with a single action) would be simpler to implement, as it was basically displaying same view as if you were to check only draft files or only published files. But unchecking them and using confirmation notification after batch publishing/unpublishing can work too.

**Comment by chillu** [comment]
I've added the following AC:

> If mixed states are selected (both published and draft items), both publish and unpublish actions are available and will silently skip files where the action isn't applicable

Good point about notifications, I wasn't aware that this is the first time where we need notifications because the changes aren't obvious in the UI (the existing "delete" action will clearly remove items, the existing "move" action clearly moves them, but publish/unpublish just changes a small icon on the thumbnail). I've created a separate card for this: https://github.com/silverstripe/silverstripe-admin/issues/176. @clarkepaul Do you think these notifications are more important than adding another new feature into 4.0? Currently they're not in the milestone, because it's scope creep for this card.
