### ISSUE TITLE
Remove background on cancel upload icon

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#526]
Really minor, the background needs to be transparent on upload.
<img width="148" alt="pasted_image_4_07_17__2_58_pm" src="https://user-images.githubusercontent.com/555033/27813340-4ceeb7ea-60c9-11e7-89f9-63c816aadb2d.png">

**Comment by robbieaverill** [comment]
Re @clarkepaul - upload a large image to test easier in lieu of breakpoints

**Comment by chillu** [comment]
The upload no longer shows the "selected" styling, so that visual glitch isn't present. Closing

**Comment by robbieaverill** [comment]
Looks like this is still happening from the asset-admin area, but not from WYSIWYG context:

![image](https://user-images.githubusercontent.com/5170590/30043274-9624e706-924a-11e7-8228-80f5c05cb047.png)
