### ISSUE TITLE
Misleading error message when API loading fails ("folder cannot be found")

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#528]
This shouldn't happen in the first place, but if it does we should deal with it more gracefully.

![image](https://user-images.githubusercontent.com/111025/27845557-7288d010-6184-11e7-825e-192aab81ec8f.png)

## Related 

 * [Upload can't handle large amount of files](https://github.com/silverstripe/silverstripe-asset-admin/issues/139)
 * [Implement cachable asset store](https://github.com/silverstripe/silverstripe-assets/issues/43)
 * [Large folder breaks GraphQL fetch](https://github.com/silverstripe/silverstripe-asset-admin/issues/536)
 * [Pregenerate thumbs on upload](https://github.com/silverstripe/silverstripe-asset-admin/issues/462)
 
## PRs
 
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/590
 - [x] https://github.com/silverstripe/silverstripe-admin/pull/198

**Comment by clarkepaul** [comment]
What are the scenarios for when this could happen?
I've experienced this when uploading a large file, while waiting navigate away to a different file's details—the view of the files and folders on the left fails.

**Comment by newleeland** [comment]
I've also had occur when saving edited files when my session has timed out.

**Comment by clarkepaul** [comment]
Error appears:
* When session times out
* Reached memory capacity
   * Individual file?
   * Folder?
   * Overall files area / system?

**Comment by tractorcow** [comment]
>  I've also had occur when saving edited files when my session has timed out.

I think in this case, we need to ensure the CMS re-authentication dialog works with asset admin section

**Comment by mister-todd** [comment]
@flamerohr what's thisblocked by?
