### ISSUE TITLE
Uploading larger files breaks the error message

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#532]
Tested with large image and large video file, with both showing the same issue.

![image](https://user-images.githubusercontent.com/555033/27886613-028ec014-6231-11e7-91d3-5f8afb635731.png)

## Related

 * [Large folder breaks GraphQL fetch](https://github.com/silverstripe/silverstripe-asset-admin/issues/536)

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/553

**Comment by chillu** [comment]
Excludes sanity check for PHP config vs. SS configured value. Please chekc if this is enforced, and create a ticket if it isn't. Ideally this graceful error handling would be handled fairly centrally.
