### ISSUE TITLE
Page batch actions submit button text missing

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#533]
![image](https://user-images.githubusercontent.com/555033/27887277-077a4f46-6234-11e7-8ea5-45e7548909e4.png)

**Comment by robbieaverill** [comment]
Can't reproduce any more - do you still see this @clarkepaul?

![image](https://user-images.githubusercontent.com/5170590/28151911-b39db41c-67f1-11e7-9cab-0f58cb70f23a.png)

**Comment by clarkepaul** [comment]
Sorry, should have said already that this is only with smaller screens. And the bug is that the text "Go" disappears.

I think we might need to bring back the text "Add" on the green button but that is a separate issue.

**Comment by robbieaverill** [comment]
Fix at https://github.com/silverstripe/silverstripe-admin/pull/152 - possibly a few ways to fix this - this is one way
