### ISSUE TITLE
Bulk upload: no indication of not-yet-started

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-asset-admin#535]
When you pull a lot of images into the asset admin, the uploads will take a while to start. This is fine.

However, it highlights that there is no indication of an image for whom the upload hasn't even started. You can see the issue here:

![silverstripe - files 2017-07-06 10-59-45](https://user-images.githubusercontent.com/59968/27888510-77eba580-623a-11e7-8e49-2f722c0e5386.png)

These images should be styled differently, e.g. greyed out or semi-transparent.

**Comment by newleeland** [comment]
We could just preload an empty loading pill that's grey would imply that the image is still waiting to be uploaded

**Comment by clarkepaul** [comment]
This was the original design with a background on the loading indicator, might have been forgotten https://projects.invisionapp.com/boards/ZRX68PCPKESN/

**Comment by bergice** [comment]
@sminnee, what version is this issue occurring on?

It is showing the grey progress bar for all files on `4.x-dev`, `4.3.x-dev`.

**Comment by sminnee** [comment]
It was a 4.x alpha release so may have been fixed. I'll re-test.

**Comment by sminnee** [comment]
Yeah this has been resolved now.
