### ISSUE TITLE
File Publish resets File ClassName

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-asset-admin#539]
I'm unsure whether this is the correct project to report this in as it relates to the File Manager in SS4 in the CMS (left-hand-side "Files"), if not then please tell me which is the most suitable and I can report it there.

(Re)Publishing an image file in the Asset Admin (file manager) resets the `ClassName` to `SilverStripe\Assets\Image`.

In an example whereby one has an extended Image class

```php
<?php
use SilverStripe\Assets\Image;

class SlideImage extends Image
{
}
```
The `SlideImage` is added correctly via any common method (eg: a page with a `$has_many=['SlideImages' => SlideImage::class];` which correctly sets the ClassName "SlideImage" in the `File` db table, all good. Then you go into the File Manager (CMS, left-hand-menu "Files"), locate the file, then make any modifications (or even none) and (re)publish the file, and the image "ClassName" is reset to `SilverStripe\Assets\Image`.

I am assuming this issue applies to any publishable extended file type, however so far I have just encountered an extended ` SilverStripe\Assets\Image`.

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/643

**Comment by robbieaverill** [comment]
This happens on save as well as on publish. I can't reproduce the behaviour with a unit test though =/

**Comment by robbieaverill** [comment]
Narrowed down to logic added in https://github.com/silverstripe/silverstripe-asset-admin/commit/8c40c580 - "FIX cast file to new class when appropriate" which switches the class name: https://github.com/silverstripe/silverstripe-asset-admin/blob/1.0.0-beta1/code/Controller/AssetAdmin.php#L977-L990

**Comment by tractorcow** [comment]
We still need to ensure that files with changed extensions match the appropriate "base" type. E.g. replacing a file.jpg with file.png MUST change it to a non-Image subclass.

My suggestion is to change this check such that it only performs the change if the "to" and "from" have different base classes (where the base-class is the class just above File).

E.g. MyImage won't change to Image, but it will change to File or PDFFile.

**Comment by tractorcow** [comment]
Off the top of my head:

```php
// if the class has changed, cast it to the proper class
$currentClass = $record->getClassName();
if (!is_a($currentClass, $newClass, true) || ($currentClass !== $newClass && ($currentClass === File::class || $newClass === File::class)) {
  // do the change
}
```

**Comment by flamerohr** [comment]
hmm, that's a good point :) maybe worth documenting somewhere
thanks, I'll give it a whirl
