### ISSUE TITLE
When creating a folder with a space as the title the folder name becomes digits

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#555]
Space was added to the field and saved, the output is a long digit.
![image](https://user-images.githubusercontent.com/555033/28400728-32468998-6d69-11e7-93bd-636ad36ed9b6.png)

**Comment by clarkepaul** [comment]
To confirm its fixed but there should be merge by @tractorcow

**Comment by tractorcow** [comment]
Yep, updated fix correctly passes the name through the FilenameFilter, and converts the space to a hyphen.

![image](https://user-images.githubusercontent.com/936064/28804569-3c7ced96-76b8-11e7-9d0e-084460e748dc.png)
