### ISSUE TITLE
Message for deleting a file/folder needs improving

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#557]
The concept of archiving files and folders doesn't exist as there is no way to re-enstate them. The success message needs improving to reflect the actual action taken.
![image](https://user-images.githubusercontent.com/555033/28498951-6aa160e6-6ffe-11e7-9196-279669c1e79d.png)

**Comment by clarkepaul** [comment]
Simple fix to change the naming to "Delete"

**Comment by robbieaverill** [comment]
PR at #569
