### ISSUE TITLE
Assets - Modifying the 'Filename' causes image to be lost.

### ISSUE THREAD

**Issue by mithungc** [silverstripe/silverstripe-asset-admin#562]
[Videos.zip](https://github.com/silverstripe/silverstripe-asset-admin/files/1171486/Videos.zip)

Scenario 1 - After uploading an image or groups of images, modifying the 'Filename' and clicking 'Save' causes the image to be lost.
STR -
1. Uploaded 6 images to a folder
2. Selected a 1904x934 image
3. Modified 'Filename' and 'Save'.

Scenario 2 - Deleting the 'broken image' and re-uploading the 'original image' also fails, as the image is lost as soon as it is selected, after the upload. (Note - Renaming the image does not work)

Note - Videos attached for reference.

Framework version - 4.x-dev

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-assets/pull/56
