### ISSUE TITLE
Update the Files area with improved single file move functionality

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#576]
## ACs

As a CMS user, I need to have a good intuitive alternative to moving files beyond drag-drop.
This should include:
* a clear action which indicates I can move the file
* a clear indication of where the file/folder currently lives
* a notification that the item I selected to move has been moved, or failed to move
* a notification of where the item I move has moved to, so they can either navigate to the new location or the actual file again if they choose to
* a clear indication of where you—once the file has been moved the user remains in the current location so they can choose to move more items

**Out of scope**
* an option to revert the changes if I moved the wrong item

TASKS
* [x] Use Option 1 as the base
* [x] Investigate using the full URL in selected option
* [x] Remove Path field
* [x] Confirm messaging still fits.

**Related**
https://github.com/silverstripe/silverstripe-asset-admin/issues/554

## Excludes
* This excludes the ability to move multiple items to a different folder (to open as separate issue)

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7285
- [x] https://github.com/silverstripe/silverstripe-admin/pull/191
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/586

**Comment by newleeland** [comment]
I've updated the Option 1 design, with a section of the path within the location dropdown. Instead of the full path. This is because short URLs i.e. grandparent/parent have a low cognitive load to process, additionally, the user already knows the first part the path, which is just the domain of their site.

Prototype update. https://invis.io/CRCZ3TZVQ#/247961341_Files_-_Edit_File_-_Move_Single_File_V3

**Comment by tractorcow** [comment]
PR for updating font icon at https://github.com/silverstripe/silverstripe-admin/pull/190
