### ISSUE TITLE
Add support for TinyMCE to insert other media living in Files area

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#580]
Currently, files other than images cannot be properly inserted into the page. They can be inserted as links to the file, however, we should allow for other file types. At least videos, audio and document files.

We also need to keep in mind browser support for these media types.

![screen_shot_2017-08-09_at_14_49_33](https://user-images.githubusercontent.com/8085295/29103178-2138f4b6-7d12-11e7-88fa-bb4dc27f2fb3.png)

**Comment by tractorcow** [comment]
Closing in favour of https://github.com/silverstripe/silverstripe-asset-admin/issues/563
