### ISSUE TITLE
Ask for confirmation before removing a file that's still used

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#591]
# Overview

When a file is deleted from the files area, pages which use the file still think the file is available and placed on the page leaving broken images.

Example of deleted image on published page:
![image](https://user-images.githubusercontent.com/555033/29442047-62f7485e-8423-11e7-8e8f-3d71a9bd542e.png)
![image](https://user-images.githubusercontent.com/555033/29442061-6d616414-8423-11e7-9623-4586c80031d0.png)

# Acceptance Criteria

 * When a file is deleted, show a generic warning if it is used on one or more pages (doesn't need to contain counts). Suggested message "Ensure files are removed from content areas prior to deleting them, otherwise they will appear as broken links."
 * The warning message is consistent for single file deletion from the file edit panel and bulk actions  
 * There is a warning that files might be in use when a user wants to delete multiple files (similar wording to single file delete)
 * Allow deletion after confirmation
 * ~~Direct the user to the existing "usage" tab on the "edit file" view for more details~~
 * ~~This logic applies to all UI triggers where a file can be deleted ("insert media", assets section)~~
 * The logic applies to batch operations
 * When an image is not found the image fallback text should be "File not found" not "Page not found" (as pictured above).

# Notes

 * The card doesn't include determining file usage across records. Usage is defined in the same way as shown on the "Usage" tab (which currently doesn't exist).
 * An alternative approach would be to allow users to delete but also remove all connections to those files so that we don't have broken images on pages
 
 ## PRs
 
  - [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/597

# Related

 * [Show usage of files in "edit file" screen](https://github.com/silverstripe/silverstripe-asset-admin/issues/593)

**Comment by flamerohr** [comment]
@clarkepaul There is a confirmation dialog which pops up when the user tries to delete via the bulk actions, are you talking specifically about the file edit form action?

A few other points:
> - Direct the user to the existing "usage" tab on the "edit file" view for more details
this is currently not possible, as the tab state is controlled within itself, we'd require a fair amount of refactoring to achieve this.

> - This logic applies to all UI triggers where a file can be deleted ("insert media", assets section)
> - The logic applies on batch operations 
Would you be able to clarify these two points? Insert media does not have the ability to delete
As mentioned above, batch delete has the confirmation already.

**Comment by clarkepaul** [comment]
@flamerohr I think Ingo edited this prior to removing the usage tab so I can re-adjust the AC's

**Comment by clarkepaul** [comment]
@flamerohr its seems you only get that warning if you bulk remove a single file and not multiple items so ideally we could improve the messaging for all scenarios of deleting even if we didn't have any data on whether it is used somewhere.

@chillu I've removed AC's refering to the "usage" tab and files being deleted from the "insert media" as you can't really delete a file from there.

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-asset-admin/pull/597

**Comment by clarkepaul** [comment]
@tractorcow I see you've already got a PR ready so this might not fit your fix but I was wondering if adding to the warning message with a bit more clarity was possible.

Adding the text... "Ensure files are removed from content areas prior to deleting them, otherwise they will appear as broken links."
![image](https://user-images.githubusercontent.com/555033/29600839-5fb1386e-882c-11e7-9039-1c63383be82e.png)

**Comment by tractorcow** [comment]
![image](https://user-images.githubusercontent.com/936064/29641460-c3e3463e-88b7-11e7-92e1-4ff43e6533a4.png)

@clarkepaul I've added this now.

**Comment by newleeland** [comment]
@tractorcow 
If we can't have dynamics messages for plurals, could change the word "places" to "places(s)"?
The file is currently used in 1 **place(s)**, are you sure..."

**Comment by tractorcow** [comment]
Done @newleeland. See https://github.com/silverstripe/silverstripe-asset-admin/pull/597

**Comment by tractorcow** [comment]
![image](https://user-images.githubusercontent.com/936064/29645270-824535e8-88d0-11e7-8b60-fe08dfa3636a.png)
