### ISSUE TITLE
Show usage of files in "edit file" view

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#593]
# Overview

We already have a "usage" tab there, but it doesn't do anything apart from showing "created" and "last edited" - that's misleading.

# Acceptance Criteria

 * The usage is listed for ownership relationships
 * The usage is listed for sitetree "image tracking" relationships (images in HTML content)
 * The record type is clearly distinguishable
 * Items in the list can be linked to their editing UIs (if available)
 * Items indicate their publication status
 * The user is clear about the limitations of this functionality (there are limitations?)
 * Usage works with hundreds of items (list can be truncated rather than paginated for now)
 * Does not affect initial edit form load

# Excluded

 * Usage is listed for arbitrary records with images in HTML content (non-SiteTree)
 * Indicate where in a record the usage ocurs (e.g. HTML embed vs. record association)
 * "Added by" and "edited by" indicators
 * Show usage count on tab (too hard due to lazy loading)

# Notes

 * Wireframes at https://projects.invisionapp.com/boards/M6X68PJ87FSB/
 * Should be built on GraphQL, see https://github.com/silverstripe/silverstripe-asset-admin/issues/251
 * Should be lazy loaded (not with initial form schema load). It might make sense to extend this lazy loading of data (not lazy rendering) to all form fields 
 * HTML usage is already in core, owns relationship usage can be determined through existing PHP APIs
 * Can be a one-off GraphQL table component (no need to write React GridField)

# Related

 * [Ask for confirmation before removing used files](https://github.com/silverstripe/silverstripe-asset-admin/issues/591)

@newleeland Can you please track down the existing designs for this?

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-admin/pull/427
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2094
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/734

**Comment by clarkepaul** [comment]
@chillu no designs for this as yet, just the wireframes which are already attached

**Comment by jamessilverstripe** [comment]
I have attached a fully designed artboard. Unlinkable items would have no hover state or pointer cursor.
![file usage 2](https://user-images.githubusercontent.com/29618750/30529073-a8b9a620-9c8d-11e7-9223-4fc67f378a4d.png)

**Comment by tractorcow** [comment]
At the moment this is what's there.

![image.png](https://images.zenhubusercontent.com/57352e6bbf93871ccd9af528/1d315073-3414-4b26-9513-663f212c1d07)

It needs re-styling and fixing to match the designs.

**Comment by clarkepaul** [comment]
@tractorcow do we need an issue to complete the design of this issue or where you able to tidy it up?

**Comment by flamerohr** [comment]
The designs are cleaned up, I think:
<img width="1393" alt="screen shot 2018-02-09 at 3 31 13 pm" src="https://user-images.githubusercontent.com/1064889/36008987-d1600d7a-0dae-11e8-9734-04e3885a000c.png">

@clarkepaul Do you have points that we may have missed?

**Comment by clarkepaul** [comment]
Looks clean enough cheers :)
