### ISSUE TITLE
UploadField ignores Description

### ISSUE THREAD

**Issue by adrexia** [silverstripe/silverstripe-asset-admin#598]
It seems like its no longer possible to provide a description field for a file upload. EG:

`$upload->setDescription('This is ignored');`

However the old 'setRightTitle', seems to work (though the alignment is a little off):

`$upload->setRightTitle('This is not ignored');`

![righhttitle](https://user-images.githubusercontent.com/984753/29640800-a7f46f28-88b4-11e7-90b6-4d1d2e0af22f.png)

**Comment by tractorcow** [comment]
Fixed with #670
