### ISSUE TITLE
Fix issue with drag n drop on checked and unchecked items

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#605]
In the files area, when a couple of items are checked and user then clicks and drags from a non-checked item, the drag preview shows the image of the non-checked item, however, if these items are dropped in a folder, only the checked items will be moved

![screen_shot_2017-08-29_at_4_25_24_pm](https://user-images.githubusercontent.com/8085295/29804652-1c2dd998-8cd8-11e7-9ceb-f69e11ee0cd9.png)

![screen shot 2017-08-29 at 16 25 36](https://user-images.githubusercontent.com/8085295/29804670-45e7e30a-8cd8-11e7-9ab4-2f6233572cce.png)

## Potential Solutions
- Using the above example. 2 items checked and an additional item (that is unchecked) is dragged, then that item also becomes checked and move along with the rest of the files. This is a pattern used by Dropbox and gmail and assumes that the user wanted to select the unchecked item as well. However, this does introduce complexities (i.e. with 3 items now checked, would the user be allowed to select and check a fourth?
- When cursor selects the third unchecked item and drags, the drag preview only shows the 2 checked items being dragged and is unable to check/select the third. This is the MacOS method.

**Comment by chillu** [comment]
Removing milestone - medium priority, but not as critical as other stuff

**Comment by clarkepaul** [comment]
Related issue to consider doing at the same time https://github.com/silverstripe/silverstripe-asset-admin/issues/424

**Comment by flamerohr** [comment]
fixing this while working on https://github.com/silverstripe/silverstripe-asset-admin/issues/424

**Comment by brynwhyman** [comment]
Can't recreate this on the latest branch: `silverstripe/asset-admin 1.4.0` - plus it looks to be using enhanced functionality, probably related to the comment above.
