### ISSUE TITLE
Asset Search - 'Limit to current folder and its sub-folders?' function doesn't work.

### ISSUE THREAD

**Issue by mithungc** [silverstripe/silverstripe-asset-admin#612]
When utilizing the 'Search feature' in the Asset Admin, enabling the "Limit to current folder and its sub-folders? - Checkbox" under 'Advanced', doesn't work as the search results show everything in the asset library that is related to the 'Search Parameter'.

Example -  
1. Create two Root Folders (Folder A & Folder B) in Asset Admin.
2. Create another folder within Folder A, such as 'Folder A2'
3. Create another folder within Folder B, such as 'Folder B2'
4. Upload files with a common name/search parameter to 'Folders A2 & B2' - e.g. Merrytest-640x420.jpg
5. Go into 'Folder B' and with the "Limit to current folder and its sub-folders?" feature enabled, search for '640x420'
6. The 'Search Results' display all the '640x420' assets from both 'Folder A2' & 'Folder B2'.

SS4 Build Version - master.2839

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-asset-admin/pull/613
