### ISSUE TITLE
canAttachExisting

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-asset-admin#615]
Since the beta release of SS4 I've noted that the `canAttachExisting` option has been removed. I believe this is a very important feature where one requires a user to only be able to add images/files, rather than optionally pick from existing ones.

Could you please give some clarity as to whether this feature will be returning to the UploadField or not?

**Comment by tractorcow** [comment]
Many of the old features of the legacy UploadField were removed to keep the feature set simple. It's possible the new field won't have as many functions. However, it could be built if someone felt like making an attempt. ;)

**Comment by axllent** [comment]
I'm totally for the KISS approach, but there is such a thing as over-simplifying it and removing useful functionality ;-) Unfortunately React is still on my TODO list :-/

**Comment by tractorcow** [comment]
I'm going to close this for now as a feature request.
