### ISSUE TITLE
BUG Pressing Enter key on the editor brings a file dialog box instead of submitting

### ISSUE THREAD

**Issue by phalkunz** [silverstripe/silverstripe-asset-admin#620]
This issue is reproducible on Chrome, Firefox, and Safari. Surprisingly, it works as expected on IE 11.

Steps to reproduce:

1. Go to Files sections
2. Select a file
3. Change the title
4. While the cursor still in the input, press Enter key
5. Saving/form submitting should be triggered but instead, the browser brings up the file dialog box

## Pull request

- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/647

**Comment by flamerohr** [comment]
Can we get a bit more detail on how to reproduce this?
Is this right after opening the file editor? After editing some fields? Any particular fields?

**Comment by phalkunz** [comment]
@flamerohr I've updated the issue with steps to reproduce the issue
