### ISSUE TITLE
Save / Publish buttons inconsistent with pages section. Button spacing still broken

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#625]
The save/publish buttons should use the existing pattern incl. icons and not create new ones (unless we update them globally), eg hover state is different, the icon is different.
![image](https://user-images.githubusercontent.com/555033/30194121-5fe0411a-94a5-11e7-8e37-16d8f42f18f0.png)

Button padding is still off (might already be fixed else where but thought to mention just in case)
![image](https://user-images.githubusercontent.com/555033/30194213-e51ce70c-94a5-11e7-81ce-9b68cee0e4e1.png)

## Notes

This should be reviewed with:
- https://github.com/silverstripe/silverstripe-admin/issues/126
- https://github.com/silverstripe/silverstripe-admin/issues/242

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/241
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1960
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/62
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7365

**Comment by chillu** [comment]
Can we please look at this in a bigger picture? There's too many regressions around this. Please check *all* of the following: 

 * ModelAdmin toolbars and edit screen
 * AssetAdmin toolbars and edit screen
 * CampaignAdmin toolbars, edit and preview screen
 * CMSMain toolbars, edit and preview screen
 * "Insert image"
 * "Insert media"

Button on GridFields are also misaligned. Please ensure this is not a one-off solution for CampaignAdmin, buttons on GridFields should work everywhere, and look the same everywhere.

![image](https://user-images.githubusercontent.com/111025/30254154-67e4ac12-96e8-11e7-86f7-e6bb458a84e8.png)

**Comment by chillu** [comment]
Changing to `impact/high` because we really need to get this under control, it's starting to look unprofessional this late in the beta stage.

**Comment by phalkunz** [comment]
@chillu I'd like to keep issue for button style. We have already have another issue (https://github.com/silverstripe/silverstripe-admin/issues/217) dealing with toolbar.
