### ISSUE TITLE
MigrateFileTask doesn't generate thumbs: AssetAdmin runs out of memory

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#626]
When new images are uploaded, thumbnails are generated on upload. When you migrate existing images from SS3 via `MigrateFileTask`, that's not the case. So the GraphQL request will attempt to generate the thumbnails, and run out of memory (see https://github.com/silverstripe/silverstripe-framework/issues/6457 for detail discussion).

We need to pre-generate thumbnails as part of the migration task, since it's too late when the GraphQL request is fired. I'd expect a good chunk of websites to hit this bug in production after upgrades, since many of them will have folders with 20+ images of 1-3MB size each. And it won't be immediately obvious during testing, unless you actually open every folder in AssetAdmin.

This came up in the context of https://github.com/silverstripe/silverstripe-framework/issues/6457

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/646
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7412

**Comment by sminnee** [comment]
Should we deal with further image resize edge-cases by allowing the use of a worker queue to deal with variant generation? Since we already have code that waits for eventually-consistent assets, this should pick up the generated asset once the worker queue has done its thing.

beyond this bug, a render queue would likely be handy for other use-cases

**Comment by chillu** [comment]
True, we could show "thumbnail not available" on the client until a later browser refresh shows it (after the queue has run through in the background). 

While I think that a queue system in core will be awesome (as described in your [RFC](https://github.com/silverstripe/silverstripe-framework/issues/6524)), I think it's far too late in the 4.x cycle to introduce that. And it's a fairly impactful change since it relies on every SilverStripe installation running a cron job, and us committing to an API for how jobs and queues should look like in core. And in this case, we couldn't make it optional, since without the queue running, things will break for users.

So overall, I'd much rather fix this during the migratino itself, because it's pretty much a one-off problem for 3.x sites upgrading to 4.x.

**Comment by sminnee** [comment]
Good call. Hopefully the queue system will be doable as a 4.(n>=1) feature, eg by creating an adapter for the legacy BuildTask and deprecating it.

**Comment by tractorcow** [comment]
What I had envisioned is an API that would allow you to query for a given thumb, but would only return existing variant (would never do a reload). See the `ExistingOnly` api suggestion at https://github.com/silverstripe/silverstripe-asset-admin/issues/358#issuecomment-286293854. We would need to implement this API as a part of this change.

**Comment by chillu** [comment]
I still think we should just implement thumbnail generation in the migration script. Assuming that the main way files make their way into the asset store is through CMS-powered uploads, those thumbnails should always be created on upload. Coding in a fallback handler ("images without thumbnails get url to generate-url endpoint instead") adds more complexity to the system, and I'd rather restructure this with a queue in a later 4.x release. What's the user impact if we just fix the migration aspect for now?
