### ISSUE TITLE
No way to view file history or rollback to previous file

### ISSUE THREAD

**Issue by MilesSummers** [silverstripe/silverstripe-asset-admin#629]
It is wonderful to have versioned file assets but there seems to be no way to view the history of a file or rollback to a previous version.

**Comment by clarkepaul** [comment]
Refer to this issue for rationale for removing it for the time being, but it will be reinstated soonish https://github.com/silverstripe/silverstripe-asset-admin/issues/581

Will close this one as hopefully 581 covers it.
