### ISSUE TITLE
Spacing bug in files action toolbar

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#635]
This is another padding issue. In the actions toolbar in the files area, when one item is selected the more options button is pushing the rest of the buttons down, Impact is high, as everyone will see it, and gives impression CMS is broken.

Example
![screen_shot_2017-09-19_at_10_22_48_am](https://user-images.githubusercontent.com/8085295/30568518-b62b9b78-9d29-11e7-8d06-e6651f3f8f88.png)

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/652

**Comment by phalkunz** [comment]
@newleeland It looks like it's no longer an issue.
