### ISSUE TITLE
BUG Cannot remove the last group from "only these people" lists

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#640]
If I've selected group e.g. Administrators from "Viewer Groups" or "Editor Groups" when editing a folder/file and I save, I then cannot remove that viewer group again if it's the last remaining group.

This is mainly made obvious since the Viewer Groups and Editor Groups select fields are always visible, rather than only when you've selected "only these groups (choose from list)" (see #636), otherwise we wouldn't notice that its still defined.

When clicking the "X" button on either the select field or the item in the field itself the item is removed, but when saving the file/folder it reappears again.

If the intention is that you shouldn't be able to set no groups for this list, the UI doesn't make this obvious since it still shows a "X" button both on the Administrators item and in the select field itself:

![image](https://user-images.githubusercontent.com/5170590/30624608-8200bc36-9e12-11e7-9a19-feaaadb5ccbf.png)

cc @clarkepaul

**Comment by flamerohr** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7434
TreeMultiselectField still has relics of the past...
