### ISSUE TITLE
BUG User without permission to edit a file can still edit it

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#641]
As an admin user, when I set a permission level for a file or folder of "Who can edit this file?" to "Only these groups (choose from list)", then I select "Administrators" from the list and save the file, the file or folder is still editable by users other than Administrators.

To test this I changed the title of a folder and a file that my user should only have access to view, and was able to save it.

The group I'm using to test this is a Content Author which has the following permissions:

![image](https://user-images.githubusercontent.com/5170590/30624697-080b6178-9e13-11e7-9ef4-25afd61056c8.png)

cc @clarkepaul

**Comment by clarkepaul** [comment]
@chillu something to consider pre RC?

**Comment by tractorcow** [comment]
I've attempted to reproduce this and I've not been able to get this error.

Can you confirm that your extensions (e.g. subsite) isn't interfering with it?

![image](https://user-images.githubusercontent.com/936064/31644855-0cfe0986-b355-11e7-9228-a3f066a95db9.png)

**Comment by robbieaverill** [comment]
Thanks @tractorcow - I'll try again to reproduce it with a fresh install in a bit and will update/close

**Comment by robbieaverill** [comment]
Yep, cannot reproduce now. This may have been caused by subsites.
