### ISSUE TITLE
Cannot drag-select files on the second level

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#659]
![screen_shot_2017-10-10_at_1_51_05_pm](https://user-images.githubusercontent.com/8085295/31365122-baaf45f8-adc5-11e7-984c-fbeed205678d.png)

in a second level folder, I cannot drag-select files but I can drag select folders

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/660

**Comment by flamerohr** [comment]
a bug with react-select... it does not do well after changing to another folder with different items

**Comment by flamerohr** [comment]
Spoke too soon, found that the code rendering gallery items were using the array index as component keys... which meant no mounting/unmounting when changing folders
