### ISSUE TITLE
BUG Permissions fields are not visibly read only when editing from a page context

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#662]
Given a page which `has_one` File, I upload a file and save. When I edit the image inline via the upload field the file form fields are readonly, but the radio inputs still look active and still react when you click them.

The inputs have the `readonly` attribute - perhaps they also need `disabled`? Screenshot of the difference:

![image](https://user-images.githubusercontent.com/5170590/31419414-43a9ca0e-ae98-11e7-9075-e5145fffeea8.png)

Probably a Bootstrap issue, and possible cross-reference https://github.com/twbs/bootstrap/issues/16413

---

Another option - replace the radio options with just the value of the selected option, since it's read only and the other options don't really matter unless you can edit them (also probably an issue for silverstripe-admin as a global policy rather than just here).

## Pull request
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/316

**Comment by clarkepaul** [comment]
Bootstrap does a slightly better version of it with a lighter label but would still be unclear if there were only disabled radios in view.
![image](https://user-images.githubusercontent.com/555033/31419684-988f185c-ae99-11e7-8c67-20bfa8847014.png)

**Comment by flamerohr** [comment]
I think we're a little behind in our bootstrap4 version?
When I apply the `disabled` class to the wrapping div like in their documentation, it didn't do anything... I've applied the necessary classes and properties, but styling is a bit off from expected due to the above.

@clarkepaul do you think we should grey out the radio button and text for readonly cases?

**Comment by newleeland** [comment]
@flamerohr 
> do you think we should grey out the radio button and text for readonly cases?

At the moment our readonly and disabled styles are the same, the only difference is that disabled is not selectable (cursor turns into a circle with a strike through it).

Its quite hard for the user to see the radio is unselectable if, we don’t change the colour of the text.

**NB.** The disabled text colour in BS4 doesn't pass WCAG standards, on white bg.

**Comment by flamerohr** [comment]
Fix is up, this affects both Radio buttons and Checkboxes the same.

**Comment by clarkepaul** [comment]
@newleeland We use a slightly darker color for .text-muted which populates all lighter text in the CMS so that it meets WCAG so this "should" happen automatically (in other words our variables are different than default bootstrap so not we don't need to be concerned about all the colours).
