### ISSUE TITLE
Dropdown is clipping behind the modal 

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#663]
![screen shot 2017-10-13 at 4 30 58 pm](https://user-images.githubusercontent.com/8085295/31529683-2a6bc0f6-b037-11e7-9cf9-2804fe4aad7c.png)

When moving a file after selecting the file and using the pop out action bar, modal appears to clip out the dropdown, covering up all the other directories
Tested on Chrome and Safari

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-admin/pull/312

**Comment by tractorcow** [comment]
Fixed.
