### ISSUE TITLE
Add support for TinyMCE to insert Doc files living in Files area

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#680]
At the moment as a CMS we can only add text and images to a page via TinyMCE. Another media file type that would be good to add is docs (and allow the browers to render it once clicked)

**Proposed design**
![pages_tinymce_insert media_docs](https://user-images.githubusercontent.com/8085295/32256421-cd3fb43c-bf13-11e7-9244-4504a4f99409.png)

![pages_tinymce_insert media_doc inserted](https://user-images.githubusercontent.com/8085295/32256420-cd187afc-bf13-11e7-814f-e85060dc09eb.png)

**Comment by clarkepaul** [comment]
This is now possible so closing
