### ISSUE TITLE
Lost setAllowedMaxFileNumber()

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-asset-admin#683]
# Overview

UploadField still allows multiple uploads, but for some reason the ability to limit the amount of files has been dropped. Ref: https://docs.silverstripe.org/en/3/developer_guides/forms/field_types/uploadfield/#multiple-fileupload

# Acceptance Criteria

 * If a max file number is specified on an upload field, I get an error when I try to upload a single file beyond this limit
 * If a max file number is specified on an upload field, I get an error when I try to bulk upload multiple files which would push beyond this limit
 * In both cases, the file isn't uploaded in the first place (no need to clean up on the server)

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/707

**Comment by tractorcow** [comment]
The removal was intentional; The existing feature set was pretty unwieldly.

I'll mark this as an enhancement request to re-implement this feature. :)

@chillu do we want to re-introduce this feature?

**Comment by chillu** [comment]
Hmm, I think it's a useful feature, but I agree that it's `impact/low` for us at the moment. An alternative solution would be to put those constraints in a GridField (e.g. limiting how many `GalleryItem` a `Gallery` can have, where `GalleryItem has_one Image`). That doesn't work for everyone of course. But I can see it becoming more common with an increased use of content blocks
