### ISSUE TITLE
File search results - can't see which folder a file is in

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#684]
Copied from https://github.com/silverstripe/silverstripe-cms/issues/376

When searching for files in the CMS using the filter on the left hand panel, the results don't show which folder a file is from. A folder or path should be added to the search results.

@clarkepaul can you comment on this? If this is no longer a need we can close the above issue.

**Comment by clarkepaul** [comment]
Each item can be selected to see the folder location without going away from the results page now but it could be a good idea/pattern in general (if we can work it into the design) for search results in all areas of the CMS to show location either through a path or parent.

I think we can close this issue as location is now available and consider if it makes sense adding more info globally to search results in the list view (not just for files).
