### ISSUE TITLE
Checkbox on thumbs isn't square

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#686]
![image](https://user-images.githubusercontent.com/555033/32472069-8c8aa436-c3c5-11e7-8367-435cef15b38f.png)

## PR
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/768

**Comment by tractorcow** [comment]
I think it's intentionally rounded corners.

**Comment by clarkepaul** [comment]
Ha, that's not what I meant. Unless my screen stretches things I think the checkbox is visually wider than it is high... meaning it's not square like a checkbox should be.

**Comment by tractorcow** [comment]
Oh, I see... sorry :D
