### ISSUE TITLE
Tab heights/padding are missing

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#689]
Looks like the tabs height/padding have disappeared and are now really thin—also the border on the bottom is now 1px instead of the 3px.

The height of each tab was 52px (line-height:20 + 16px padding top/bottom) with a 1px line spanning beneath the tab, the tab had a 3px border which overhangs the line on the bottom. The active tab would need padding-bottom 14px with the 3px border on the bottom.

<img width="173" alt="pasted_image_7_11_17__8_32_pm" src="https://user-images.githubusercontent.com/555033/32482135-2efeb146-c3fb-11e7-9b69-c08b8f8dafb0.png">

**Comment by sachajudd** [comment]
Closing as fix has been merged.
