### ISSUE TITLE
Modified indicator is missing from thumbnail and draft uses wrong style

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#694]
Draft indicator seems to be using the modified style and the modified indicator is missing completely.

These are the styles for whats being used on pages which we should align with:
![image](https://user-images.githubusercontent.com/555033/32756700-508198e8-c940-11e7-9f2b-5ac4e3953887.png)

Files indicator missing:
<img width="433" alt="pasted_image_14_11_17__1_37_pm" src="https://user-images.githubusercontent.com/555033/32756838-159a8c52-c941-11e7-9ec5-10ddf4409aac.png">

## PR

- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/764

## Notes

 * Track under ORB-175

**Comment by clarkepaul** [comment]
I'm increasing the impact rating of this issue now that these states are needing to be surfaced on elements like uploadfields, and actually need to communicate if files are presented on the live view or not. 

Modified files—currently no indicator looks as if a file is published but it isn't
Draft file—currently shows a modified indicator meaning people assume it is visible on the site

Good example of a use case on this related issue https://github.com/silverstripe/silverstripe-asset-admin/issues/721

**Comment by tractorcow** [comment]
I'm not sure this is high impact, but it's definitely easy to fix. Added a tentative 2 points.

**Comment by clarkepaul** [comment]
@tractorcow did you mean to remove the impact tag completely? perhaps you meant to give it a impact/medium

**Comment by tractorcow** [comment]
Sorry oops.
