### ISSUE TITLE
symfony/filesystem v4 incompatibility

### ISSUE THREAD

**Issue by nathansams** [silverstripe/silverstripe-asset-admin#703]
Hi guys,

When migrating a Silverstripe site from 3.6 to 4, I ran into an error when running `/dev/build`. An Exception was thrown: `Uncaught TypeError: Return value of Symfony\Component\Filesystem\Filesystem::toIterable() must be an instance of Symfony\Component\Filesystem\iterable`

At first, this seemed like a file system permissions issue, but after some troubleshooting and help from @flamerohr I noticed that the `symfony/config` dependency had pulled in `symfony/filesystem 4.0.1`. `symfony/filesystem` isn't an explicit dependency of the framework/asset-admin that I could find.

The above error was resolved by adding `symfony/filesystem 3.4.1` to my project's composer dependencies, but I wanted to raise a flag in case this is an overall incompatibility with `symfony/filesystem 4.*` or a missed dependency on `filesystem`.

**Comment by tractorcow** [comment]
Which PHP version are you using?

**Comment by nathansams** [comment]
7.0.22

**Comment by tractorcow** [comment]
Oh I see.

`symfony/filesystem` 4.0.1 has this dependency.

```
"require": {
    "php": "^7.1.3"
},
```

How did you install it with composer? Did you `--ignore-platform-reqs`?

**Comment by nathansams** [comment]
Oh, my php cli is 7.1.11 but the web server is running 7.0.22. Perhaps that's the problem then...

**Comment by tractorcow** [comment]
Ah yes that could cause it. :) Composer will always optimise for the current environment;

I suggest you try using this to optimise for php 7.0

https://getcomposer.org/doc/06-config.md#platform


```json
{
    "config": {
        "platform": {
            "php": "7.0.0"
        }
    }
}
```

**Comment by tractorcow** [comment]
Note we have a separate issue regarding zip downloads; In the future we will try to pre-optimise these for the lowest common version (php 5.6), but that won't help you with your issue.

**Comment by nathansams** [comment]
Thanks for your time and help mate.

**Comment by tractorcow** [comment]
Related https://github.com/silverstripe/cow/issues/65

**Comment by tractorcow** [comment]
No problem any time. :)
