### ISSUE TITLE
Up / Upload / Add Folder buttons unresponsive most of the time

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-asset-admin#705]
All the upper-left buttons (up, upload, add folder) require multiple clicks in different areas to actually activate them. I can replicate this on both Google Chrome as well as Firefox (Ubuntu), and happens both in the responsive as well as desktop layout (demo in responsive mode to save space).

![peek 2017-12-12 12-30](https://user-images.githubusercontent.com/1463435/33859366-7b1d6e48-df38-11e7-87ce-9534ff75d72c.gif)

# Pull requests

 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/714

**Comment by tractorcow** [comment]
Any errors in your JS console?
Live or dev mode?

**Comment by axllent** [comment]
No errors in JS console, both live and dev, and I can confirm it happens here on another virtual machine running ie11. This has been happening since the very first alphas right through to current stable. I just tried a fresh install with no additional modules and it has the same effect.

**Comment by tractorcow** [comment]
@flamerohr can you replicate?

**Comment by flamerohr** [comment]
I have an idea of what you're talking about, sometimes having the buttons become unresponsive... however I haven't been able to replicate the issue consistently on my end :/

**Comment by axllent** [comment]
Strange, I can replicate it consistently, in fact it's extremely hard to get any of those buttons to work. Every other button throughout the CMS works flawlessly, so it is related to these specific ones. 

So Linux & Windows, IE, Chrome & Firefox - so it's not an OS-thing or browser-thing - it must be something else. As I mentioned previously, no JS errors, nor any server response delays (ie: same with the browser file dialogue). It shouldn't matter, but this is on Apache.

**Comment by phalkunz** [comment]
I saw that happened but I couldn't find a pattern that reproduces all the time either.

**Comment by phalkunz** [comment]
Turns out it's caused by a feature that enables multiple-item selection by mouse. This issue can be reproduced by:

1. Hold the left mouse button on "Add folder" button
2. While still holding mouse button, move the mouse a little. This cause the UI to go into selection mode.
3. Release the mouse button

🐞 Observe that Create folder panel doesn't show up.

**Comment by axllent** [comment]
That could explain it @phalkunz and I'm glad you can replicate it! I would not have intentionally been moving my mouse when clicking, but the most minute movement is easy when clicking, depending on mouse type I guess. That could also explain how I could replicate it with multiple browsers and operating systems ~ all on the same PC (ie: same mouse).

**Comment by flamerohr** [comment]
Wow, that is one of the more bizzare bugs I've ever encountered... nice find @phalkunz
