### ISSUE TITLE
Freshly uploaded items always show in search

### ISSUE THREAD

**Issue by blueo** [silverstripe/silverstripe-asset-admin#719]
The search results always include new assets immediately after uploading.

Steps to reproduce:
1. upload a new asset
2. open the search bar and perform a search to exclude the new file (eg filter for documents after having uploaded an image). 
3. note that search results include the new asset even though it should be excluded.

Interestingly the Graphql response does not include any files - so this is likely some kind of client side caching.

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/726

**Comment by flamerohr** [comment]
that's correct, uploaded files are stored and listed on top of the current "page" or "results"

I guess it would make sense to clear that store when a search has been executed though... although, if you upload during a search then you'd still have that similar experience

**Comment by blueo** [comment]
yeah it would useful when you upload during search but a little unexpected when you're not - maybe it is more about visually distinguishing them from the search results so it is clear where they come from

**Comment by flamerohr** [comment]
yeah, we have plans to move uploaded items to a separate panel or something along those lines... in the future.

what I've suggested to clear is the reason I've marked this as a `bug` :)

**Comment by clarkepaul** [comment]
Marking this as potential UX item as we might be able to suggest a mid-way solution.

**Comment by flamerohr** [comment]
@clarkepaul sounds good, if it's a new UX element then I'd recommend a new ticket for that

a bug can be added to a patch release (e.g. 4.1.1) which means users get this bug fixed sooner
but a new UX element would be more suited to a minor release (e.g. 4.2.0)
