### ISSUE TITLE
UploadField error messages

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-asset-admin#720]
Granted it's hard to accomodate for every eventuality, however in the example below it's not even entirely obvious there _was_ an error:

![capture](https://user-images.githubusercontent.com/778003/34959761-cc7d6fe8-fa9c-11e7-9ac6-e31c145db5c5.PNG)

I think it would be nicer to have some set of 'default' type of error message, such as 

>There was a problem uploading your image

which would at least give the user some strong topical feedback.

In this case of the example, it was a `400 - Bad request` error from uploading a `PNG` to a field that only allows `ico`.

# PRs:

 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7785

**Comment by tractorcow** [comment]
@NightJar I can't reproduce this issue. On 4.0.x-dev and 4.1.x-dev the error message works fine for me.

![image](https://user-images.githubusercontent.com/936064/35247053-cd384e26-002d-11e8-808d-c169fd9f1837.png)

**Comment by tractorcow** [comment]
I also can't reproduce the error in 4.0.0 stable.

**Comment by tractorcow** [comment]
Blocked until reproduction can be provided.

**Comment by tractorcow** [comment]
PR https://github.com/silverstripe/silverstripe-framework/pull/7785

**Comment by NightJar** [comment]
Hooray, much better, thank you @tractorcow :)

![capture](https://user-images.githubusercontent.com/778003/35256534-38f3c322-0059-11e8-9cef-9eceda65276b.PNG)
