### ISSUE TITLE
Uploadfield indicator for draft/modified state

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#721]
# Overview

We need an indicator to state whether a file within an uploadfield is in draft or modified state as per other versioned content.

# Acceptance Criteria

 * A newly uploaded file shows as draft
 * A replaced image file shows as modified
 * This works with multiple files
 * On publishing/unpublishing a record owning the file, the indicator updates

# Notes

 * When a record is both draft and modified, use the same behaviour as pages
 * Pages only show up as "modified" when a file is added/removed on a has_one relationship (existing behaviour). It will NOT show up as "modified" on a has_many or many_many
 * No reordering in core UploadField with multiple uploads
 
# PRs:

 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/745

**Comment by clarkepaul** [comment]
cc @chillu

**Comment by phptek** [comment]
@clarkpaul good call. I and my users are stumbling over this time and time again: 

Client: "Why isn't that image showing?" "
Me: "Oh because it's not published."
Client: "Can I do that from the holder/page content?"
Me: "No"
Client: "Why not"?
Me: *Shrug*

**Comment by sachajudd** [comment]
To make states more visible we can add badges below the uploadfield item details.
cc @chillu @clarkepaul 

![upload indicators](https://user-images.githubusercontent.com/24258161/36506786-792d8ee4-17bc-11e8-821f-10f2877815be.png)

**Comment by phptek** [comment]
@tractorcow sure, but only if the dev knows about the concept of an "owner". I somehow missed that part of SS4 knowledge :-(

**Comment by tractorcow** [comment]
Yeah it'll be easier once we instill this as common knowledge, or at least make it really hard to version objects without adding it. E.g. "This object is related to at least one versioned object, but no owns is declared. " notice?

**Comment by tractorcow** [comment]
Approved can be merged once the PR is green.
