### ISSUE TITLE
File selected for publishing cannot be found

### ISSUE THREAD

**Issue by ivoba** [silverstripe/silverstripe-asset-admin#724]
When uploading files in admin/assets and immediatly check them and use "Publish" from the bulk actions menu in the toolbar the javascript fails with:

> vendor.js?m=1510059160:1 Uncaught Error: File selected for publishing cannot be found: 295
>     at bundle.js:1 

When i reload the page or reloading the gallery by paging the bulk action for "Publish" is working.

**Comment by tractorcow** [comment]
Seems to be fixed in current 4.0 branch; Will be tagged at 4.0.2 soon.

**Comment by tractorcow** [comment]
@ivoba please re-test in 4.0 latest branch and get back to me if you notice it's still failing on your side. :) I know we have made some changes to recently uploaded records, so I'm going to assume those addressed the original bug.
