### ISSUE TITLE
Asset-admin toolbar icons breaking in mobile view

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#729]
@newleeland commented on [Wed Jan 31 2018](https://github.com/silverstripe/silverstripe-versioned/issues/101)

Icons should be horizontal instead of vertically next to each other
![Screen_Shot_2018-01-31_at_11_45_57_AM.png](https://images.zenhubusercontent.com/596d365561b4ca3b0a74bd86/680ea4e5-0d85-466f-a250-67dd22570723)

- [ ] UX Review

## PR

https://github.com/silverstripe/silverstripe-asset-admin/pull/733

**Comment by lukereative** [comment]
The sort drop down is now wrapped to the icon on small sizes

![Screen Shot 2018-02-07 at 10.39.40 AM.png](https://images.zenhubusercontent.com/57b6527ce40e5714b16d8ab6/bdfe55d9-904a-47d1-ab1b-cd9c4095256c)
