### ISSUE TITLE
Default admin no longer able to see secure assets in SS4

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-asset-admin#777]
While testing the secureassets-migration from ss3/cwp1.8.1 to ss4/cwp2rc1 we came across a regression.

When setting a file folder to be only visible by a group e.g. blog user, in CWP1.8.1 the default admin can still access and see it. In CWP2.x the default admin _cannot_ see the permission restricted folder any longer. This seems to be a bug.

#### Acceptance Criteria
- An administrator has overarching permissions to view folders and files that would otherwise be restricted to another group.

#### Pull Requests
- [x] https://github.com/silverstripe/silverstripe-framework/pull/9241

**Comment by tractorcow** [comment]
Need to confirm this is cwp or a core framework issue.

**Comment by raissanorth** [comment]
Please excuse the delay in responding to this.

I tested again using the 4.x-dev silverstripe-installer and can confirm that this issue still exists outside of the CWP context. 

For instance, I added a folder Plants within the Files section of the CMS and left the default (inherit from parent folder) permissions. Then I added two files, but limited the view and edit permissions to only members of group Bloggers.

When logged in as a Blog Users (belongs to group Bloggers), I can see the following:

![image](https://user-images.githubusercontent.com/14869519/39281415-8e78339e-4958-11e8-9f66-b19637d1cb15.png)

When logged in as the default admin, I can see the folder, but not the files contained within:

![image](https://user-images.githubusercontent.com/14869519/39281442-b35fc708-4958-11e8-8eaa-74397efabdf2.png)

**Comment by raissanorth** [comment]
Also note that I haven't set any configurations regarding admin access permissions such as checked for in https://github.com/silverstripe/silverstripe-framework/blob/4/src/Security/Permission.php#L188 Given that admins have access to 'restricted' files in SS3, I expected the same behaviour.

**Comment by colintucker** [comment]
Can confirm that this is an ongoing issue in a standard install of `v4.4.1`, and I believe is related to the data pulled down via graphql.  You can replicate in the following way:

1. Create a security group.
2. Create a folder and allow only that group to view the folder.
3. Refreshing asset admin will show the folder until logging out.
4. Login again as administrator, the folder will have disappeared from asset admin.

:(

**Comment by brynwhyman** [comment]
Added the following AC to make it clear 
- An administrator has overarching permissions to view folders and files that would otherwise be restricted to another group.

There's been some very recent work on permission data via graphql, so we should have a fresh view of tackling this.

**Comment by robbieaverill** [comment]
Fixed in https://github.com/silverstripe/silverstripe-framework/pull/9241
