### ISSUE TITLE
Update CMS/PL Popover CSS to align with popover design

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#779]
CSS of popovers withing the CMS and Pattern Library are not consistent with design documation. This is because of several issues.
- Update to Bootstrap 4 stable, has caused some CMS bootrap CSS commenting redundant
- Originally Custom code made to Popovers originally, to make them as dropdown menus. e.g. campaigns
- SCSS Variable additions/removal/changes in BS4 Stable.

Popover Design:
https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/components/5ae267cb98330300118a7851

### Related scss files
- [ ] Update bootstrap CSS with latest bootstrap on src/styles/_bootstrap-variable.scss 
```### Update src/styles/_bootstrap-variable.scss
// Removed legacy commented variables which shouldn’t be used anymore ($popover-inner-padding, …
$popover-arrow-outer-width:         ($popover-arrow-width + 1px) !default;
$popover-inner-padding:             1px !default;

// Popovers (with //changes)

$popover-font-size:                 $font-size-base !default;  // SS custom
$popover-bg:                        $white !default;
$popover-max-width:                 276px !default;
$popover-border-width:              $border-width !default;
$popover-border-color:              rgba($black, .2) !default; // SS custom
$popover-border-radius:             $border-radius-lg !default;
$popover-box-shadow:                0 .25rem .5rem rgba($black, .2) !default; // SS custom

$popover-header-bg:                 darken($popover-bg, 3%) !default; // SS custom
$popover-header-color:              $headings-color !default;
$popover-header-padding-y:          .5rem !default; // SS custom
$popover-header-padding-x:          .75rem !default; // SS custom

$popover-body-color:                $body-color !default;
$popover-body-padding-y:            $popover-header-padding-y !default;
$popover-body-padding-x:            $popover-header-padding-x !default;

$popover-arrow-width:               1rem !default; // SS custom
$popover-arrow-height:              .5rem !default; // SS custom
$popover-arrow-color:               $popover-bg !default;

$popover-arrow-outer-color:         fade-in($popover-border-color, .05) !default;
```

- [ ] Potentially removing custom (hacky) code for component/PopoverField/PopoverField.scss in favour of using vanila bootstrap 4. There will need to be investigation into where this code is being used. First impression look like legacy code from BS4a where popover is being used as dropdown menu. Suggest replace with BS dropdown.
- [ ] Potentially removing variable src/styles/_variable.scss
![Screen Shot 2018-04-27 at 1.47.26 PM.png](https://images.zenhubusercontent.com/596d365561b4ca3b0a74bd86/ae9d4e16-5853-41a2-a64b-00b7b6152a35)

### Pull request

- [x] https://github.com/silverstripe/silverstripe-admin/pull/531
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/101
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/786
- [x] https://github.com/silverstripe/silverstripe-admin/pull/565
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/804

**Comment by maxime-rainville** [comment]
#101 is still ongoing.

**Comment by robbieaverill** [comment]
Reopening, it doesn't look like the popover designs were updated

**Comment by dhensby** [comment]
All PRs merged
