### ISSUE TITLE
BUG: Freshly uploaded files don't receive optimistic updates

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-asset-admin#782]
### Steps to reproduce
* Upload a file
* Select it
* Choose "publish" in the batch actions
* See that the red dot, indicating DRAFT is not removed

Suspect this is because the uploading process circumvents Apollo, making it invisible to the cache.

**Comment by brynwhyman** [comment]
I can't recreate this in version `1.4.x-dev`. 

![publish-file](https://user-images.githubusercontent.com/15868440/67167936-46b33000-f3fb-11e9-8f00-21b04b91c43f.gif)
