### ISSUE TITLE
Location is empty

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-asset-admin#788]
The fileEditForm show empty location while file is inside a folder

Steps to reproduce:
- Make a fresh install
- Create a folder
- Upload a file

Or maybe the location field is used for something else (moving the file?). It's confusing anyway.

As a side note, json response for the treeview does mark the folder as opened (opened: true), but with no visible effect on the component.

![silverstripe files](https://user-images.githubusercontent.com/250762/40772817-50b1cdd4-64c1-11e8-8190-21f57d325533.png)

**Comment by chillu** [comment]
Can't reproduce in 4.x branch - can you please recheck and let us know which SilverStripe version and browser version you're testing this on?

**Comment by lekoala** [comment]
Sure. I tried with silverstripe-recipe 1.1.2@stable on windows

It's doing it on chrome and firefox (latest) so I'm pretty sure it's not a browser issue.

What's strange is that if I click on the little cross to "unselect", it will change the location to "top level" (in dark, instead of the grayish default value). It seems it's really just a display issue : the current folder is not properly selected in the dropdown. I do see the little loading icon, but after that, it only displays (top level) in gray.

I can play around (move the file, publish, save) the location is never displayed properly.

maybe it's a window issue then ? (

**Comment by lukereative** [comment]
Hmm, I couldn't replicate it on that specific version on a few browsers (including IE) – but I don't have access to a Windows hosting environment. So unless you can track down the issue, I'm not sure how to 'fix' it sorry.

**Comment by lekoala** [comment]
it's not a windows thing either because i tested on a linux hosted website, and it's doing just the same.

as far as I can tell, it's simply because the "ParentID" is empty upon load and therefore not showing anything in the Location field. Even if its empty, it won't change the file location on save (i guess because "it didn't change". Manually selecting the same location ("Test/" in my case) just because blanks again after save (ParentID empty).

Here is a screenshot showing that

![desktop screenshot](https://user-images.githubusercontent.com/250762/42760230-13a7bbd4-890a-11e8-9b54-292e1420f1a8.png)

**Comment by maxime-rainville** [comment]
I'm replicating it on SS 4.0, 4.1, 4.2 and 4.x

**Comment by lekoala** [comment]
fyi, it's still happening on 4.3-RC1

**Comment by AljosaB** [comment]
It's happening for me too, SS 4.3.3, on linux and windows in all browsers

**Comment by lekoala** [comment]
so how comes that @chillu and @lukereative cannot replicate this issue? it's really confusing.

**Comment by DoggersHusky** [comment]
I can replicate this on SS  4.3.0 and 4.3.3 on windows and linux environment,

**Comment by robbieaverill** [comment]
Cannot reproduce on SS 4.4.0 with the following steps:

* Go to Assets
* Create a folder (MyFolder)
* Save the folder
* Open the folder
* Upload a file into it

The location contains MyFolder correctly. Would someone who is experiencing this issue mind testing it on SS 4.4?

**Comment by kinglozzer** [comment]
I didn’t comment at the time, but I could recreate this on 4.3.3 - I’m unable to on 4.4.1 so it seems to be fixed

**Comment by lekoala** [comment]
works fine for me as well, I just updated a project that had the issue, and its gone!
