### ISSUE TITLE
Restoring an archived file throws a FileExistsException

### ISSUE THREAD

**Issue by lukereative** [silverstripe/silverstripe-asset-admin#800]
If I have `SilverStripe\Assets\AssetControlExtension->keep_archived_assets: true` and I try to restore a deleted file record by using the `Versioned::writeToStage(Versioned::DRAFT)` I get a `FileExistsException` thrown by` Filesystem::assertAbsent()` because` File->onBeforeWrite()` is called when `writeToStage()`  is used.

I would expect the filesystem to recognise that this is the deleted records' files and it's actually required that the files still exist when using `Versioned::writeToStage()` otherwise the restored record won't actually have any valid file that it's representing.

I expect that the fix will entail writing a custom restore function like `SiteTree::doRestoreToStage()` which takes into account the requirements of restoring an archived record.

## Acceptance Criteria

 * I can restore deleted files from the archive and asset admin views when the "keep files" feature is enabled
 * I don't see the "restore" option on deleted files when the "keep files" feature is disabled

## Update
@lukereative: This `FileExistsException` was unable to be replicated again after this issue was picked up, the PR's below still address the AC's of hiding the restore action on files that do not have the original binary.

A [follow up issue](https://github.com/silverstripe/silverstripe-versioned-admin/issues/73) has been raised around communicating the absence of the restore action on records that cannot be restored.

## PRs
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/72
- [x] https://github.com/silverstripe/silverstripe-admin/pull/709

**Comment by lukereative** [comment]
I was unable to recreate this issue with the latest versions of 4 branches, I am now able to restore files without getting the exception.

**Comment by bergice** [comment]
I'm okay with merging this unless we want to fix the code coverage for `GridFieldFileRestoreAction.php`.

**Comment by unclecheese** [comment]
I'll write up a quick test for that one so we can get this moved across.

**Comment by unclecheese** [comment]
Have written a test. Hopefully that gets the patch coverage up.
