### ISSUE TITLE
UploadField not supported in frontend?

### ISSUE THREAD

**Issue by jinjie** [silverstripe/silverstripe-asset-admin#810]
Is UploadField still supported in the frontend for SS4? Can't seem to make it work after hours of digging

```php
$fields->push(
    UploadField::create('Images', 'Upload Images')
);
```

I have set the form to multipart/form-data by

```php
$form->setEncType(Form::ENC_TYPE_MULTIPART);
```
I still do not see any data posted.

**Comment by jinjie** [comment]
FileField the only way to go? Manually handling the file uploads in the frontend forms?

**Comment by dhensby** [comment]
That's right, it doesn't work on the front-end; it's an admin dependency.

This has been raised before but I can't find the duplicate issue, sorry.

**Comment by dhensby** [comment]
related: https://github.com/silverstripe/silverstripe-blog/issues/533#issuecomment-394290850

**Comment by jinjie** [comment]
For the purpose of anyone who might need to upload files on the frontend, I have extended UploadField to be compatible on the frontend using Dropzonejs.

Not stable yet. But core functionality is in place.

https://github.com/jinjie/silverstripe-frontenduploadfield
