### ISSUE TITLE
Tansifex broken?

### ISSUE THREAD

**Issue by Greg808** [silverstripe/silverstripe-asset-admin#826]
I looked in to www/vendor/silverstripe/asset-admin/client/lang/de.js the translation is english. 

It seems the transifex export is broken somehow; I was also not able to find the module on transifex.

**Comment by robbieaverill** [comment]
Hi @Greg808 

Some language packs may have English strings in them depending on how they're configured in Transifex.

The project is here: https://www.transifex.com/silverstripe/silverstripe-asset-admin

It looks like the German JS translations are all English - somebody probably needs to translate them! See: https://www.transifex.com/silverstripe/silverstripe-asset-admin/viewstrings/#de/master-js/97418155

If you're keen to get involved, I'd suggest getting involved with the Transifex project.

Thanks for logging this issue

**Comment by robbieaverill** [comment]
Reopened - it seems like we've incorrectly pushed English translations to all languages in this module, which means they aren't showing up as needing to be translated, e.g.

```
See "History"... e.g. AssetAdmin\.ADD_FOLDER_BUTTON "by silverstripe, a year ago"
```

We might be able to revert back in history in order to refresh the non-English translation files in Transifex.

**Comment by robbieaverill** [comment]
Hi @Greg808 @wernerkrauss

I've had a look at this - you can see that for the history of most of these translations there hasn't been anything other than English in them (except the first commit which only had one line): https://github.com/silverstripe/silverstripe-asset-admin/commits/1.2/client/lang/de.js

The translations may have been shifted over in some respect from SilverStripe Framework during the SilverStripe 3 to 4 upgrade, but that unfortunately means that there's no automatic upgrade path for them any more.

The only fix here is to re-translate them in [Transifex](https://www.transifex.com/silverstripe/silverstripe-asset-admin).

I'm sorry this couldn't be automated!

**Comment by robbieaverill** [comment]
I've deleted all of the German translations since they were all English.

@tractorcow can you confirm there's no danger in deleting the Javascript translations from Transifex when they're translated into non-English languages with English content? I think the fact that they don't show up as needing to be translated is an issue, but I don't want to delete them all without checking with you first.
