### ISSUE TITLE
Folders should not allow dots in their names

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-asset-admin#830]
Follow up on https://github.com/silverstripe/silverstripe-assets/pull/158

**Comment by robbieaverill** [comment]
Just added a frontend label to help distinguish it from the original (backend) issue

**Comment by robbieaverill** [comment]
@unclecheese just checking, do you still think we should disable this? I guess we could replace them with dashes instead of removing them or failing validation if you enter them?

**Comment by robbieaverill** [comment]
I'm going to make a PR that replaces dots with dashes as a middle ground

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-assets/pull/291

**Comment by tractorcow** [comment]
@unclecheese suggest to make it a soft-disallow (new folders are automatically renamed) but not a hard-disable (i.e. keep supporting url routing rules in case there is a period).

**Comment by robbieaverill** [comment]
https://github.com/silverstripe/silverstripe-assets/pull/291 means dots are replaced with dashes on upload. Closing.
