### ISSUE TITLE
File select insert button is very insignificant

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-asset-admin#832]
This button (see screenshot) does not call my attention, and I spent several seconds searching the interface for it :(

I think it at least needs to be the primary colour (green?) - whether or not it alters state when there is a selection is a nice to have I believe.

![image](https://user-images.githubusercontent.com/778003/45388614-9ad2d900-b66d-11e8-8e6c-a0f241cd75eb.png)

In this screenshot I'm using an `UploadField` to attach a file to a record (in this case an [Element](https://github.com/silverstripe/silverstripe-elemental-fileblock)).

## Pull Requests
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/934

**Comment by robbieaverill** [comment]
I guess once you've selected a file the "Insert" action is really the primary action

Probably needs @clarkepaul's thoughts before implementing anything

**Comment by clarkepaul** [comment]
When we supplied design direction the action was to be a green button for inserting images. The bottom toolbar should also extend the whole bottom of the modal (standard toolbar background colour) for both multi file insert and single insert.

I remember that the full desired user experience wasn't able to be built due to time limitations but I think the UX needs to revisited and improved, so I'll try and get the intended experience added to the [CMS style guide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe) but might not happen straight away though.

Ensuring the button is styled as a green button is a good first step.

**Comment by maxime-rainville** [comment]
That's what the Modal looks like when access via an UploadField.
![image](https://user-images.githubusercontent.com/1168676/47389203-a3d8bf00-d770-11e8-89b0-0d1306db5b26.png)

That's what it looks like when access via the WYSIWYG.
![image](https://user-images.githubusercontent.com/1168676/47389262-d2569a00-d770-11e8-9d53-b0f1a6b5d30e.png)

My guess is both of them should look like the WYSIWYG one.

**Comment by clarkepaul** [comment]
There is a difference here though, one allows multiple files (has checkboxes) to be inserted and the other only single files (no check boxes). It was designed intentionally for the button to be positioned next to the part which was most relevant. Button appearance should be the same for both views but not its position.

We had some prototype designs to check multiple items, and they all go to the edit panel with a way to cycle through them. This idea is still on the cards for some stage but at the time we wanted to take it through an MVP approach (which means the button would be in the same position).

**Comment by newleeland** [comment]
**These were the original designs styles for file insert:**

Click Batch insert and Single file insert
https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/folder/components/5c16d37d5d1e0fed52837855

**Comment by clarkepaul** [comment]
As this was not how it was designed, i've re-tagged as a bug and also increased the impact as there is a larger impact to the user here with such a common task.

**Comment by chillu** [comment]
Yeah agree it's high impact

**Comment by maxime-rainville** [comment]
Just confirming I'm looking at the right thing. That's what the _Insert_ button should look like when access via a an UploadField, correct?

![image](https://user-images.githubusercontent.com/1168676/55690976-77e28a80-59ec-11e9-8d09-c3e915082b7a.png)

[Direct Invision link to mockup](https://projects.invisionapp.com/share/WCMZMHHXRJV#/screens/337248421)

**Comment by clarkepaul** [comment]
Just recapping from today's conversation about this, the count doesn't need to go into the button if it isn't easily achieved, having the counter to the left of the action would also satisfy this issue.

**Comment by dnsl48** [comment]
ready for merge
