### ISSUE TITLE
Remove the broken radio tick when inserting single files

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#834]
Looks like the tick styling is slightly broken, when only one item is selected. Let's remove it.

When selecting multiple items, a checkbox is shown, we want to keep that!

![image](https://user-images.githubusercontent.com/555033/45459289-b14f6200-b74b-11e8-818e-04ec0898c59b.png)

# Pull Requests
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/979

**Comment by sachajudd** [comment]
Tested in 4.4, seems we've gone away from the circle designs to a square @clarkepaul?

<img width="200" alt="Screen Shot 2019-06-20 at 8 02 20 AM" src="https://user-images.githubusercontent.com/24258161/59813167-a7a2fc80-9364-11e9-9e01-0336fa17b780.png">

Think we can close this?

**Comment by newleeland** [comment]
NOTE. This issue only exists when selecting an image from uploadfield. 
Potential design solution is to remove the circle and tick all together. So when selecting a single item its just the border and background colour that changes to blue and shows authors the element is selected.

**Comment by bergice** [comment]
> NOTE. This issue only exists when selecting an image from uploadfield.
> Potential design solution is to remove the circle and tick all together. So when selecting a single item its just the border and background colour that changes to blue and shows authors the element is selected.

This is what it looks like on `4.4`: 
![image](https://user-images.githubusercontent.com/541886/63732291-a1328300-c8c7-11e9-9abb-afbc9444ee1c.png)

It looks better now, except the tick should be centered vertically.

Let me know if we still want to remove the tick, or just rejig it.

**Comment by brynwhyman** [comment]
@bergice, I'm not completely sure where this stems from, but I've been able to recreate it via the file upload field in a file block. See:

![broken-tick.gif](https://images.zenhubusercontent.com/5b17319354b51e4165e1fd0b/a3f94b3b-8e69-4371-acde-38ea8eac7f0e)

**Comment by robbieaverill** [comment]
Fixed in 1.4.x
