### ISSUE TITLE
UploadField doesn't correctly use form state

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-asset-admin#862]
### Version

1.x / 1.3.x / Probably all the versions

### Steps to reproduce

- Add an UploadField to a form
- Load the form through togglable FormBuilderLoader but set the `refetchSchemaOnMount` property to `false`.
- Mount the form, check the upload field is empty.
- Add a file using the form
- Toggle the form so it is unmounted, then toggle it again so it is remounted
- Note the UploadField is empty

In this case, the value prop of the field (provided by redux-form) is actually correct:  

![image](https://user-images.githubusercontent.com/3260989/47883893-b7340a80-de93-11e8-922a-24d719c2c21e.png)

But the files prop is wrong: 

![image](https://user-images.githubusercontent.com/3260989/47883913-c9ae4400-de93-11e8-9024-c3ccc709530d.png)

I assume part of the issue here is the file info is not persisted...

# Pull Requests

* [x] #863

**Comment by unclecheese** [comment]
Does this mean that I could be editing a page, upload a file, leave the page without saving, and then come back to it later to find the uploaded (unsaved) file still there?

**Comment by ScopeyNZ** [comment]
Yes - As long as you have told `FormBuilderLoader` to *not* refetch schema on mount.
