### ISSUE TITLE
Initial list view sort icon is inverted

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-asset-admin#864]
If you enable the list view in files with the default sort, it will initially show that the results are sorted by title with an upward caret ... implying that the list is sorted in descending order.

If you click on the Title column the list will sort in descending order and the icon will remain the same.

![image](https://user-images.githubusercontent.com/1168676/47893778-b31fe100-dec3-11e8-966e-ffde86fa7ed8.png)

**Comment by robbieaverill** [comment]
Re-labelled as a bug

**Comment by robbieaverill** [comment]
Fixed in #1085, thanks @Cheddam
