### ISSUE TITLE
"Insert Image" can't set width and height of image + Image is not resized + Proportions are not considered

### ISSUE THREAD

**Issue by StephanSchrade** [silverstripe/silverstripe-asset-admin#866]
I'm runnnig Silverstripe 4.2.
1:
If I want to insert an image with the Content Editor, I can't set the dimension of the image.
No matter what values I type in, the image will always inserted with the original size.
2:
Also the image is not really resized, only width and height in HTML are set, so the image is loaded with the full size and then scaled throughout the browser. This does not reduce the loading time.
3:
Proportions are not considered and have to be calculated in mind.
If I type in only the width, the height is not calculated automatically and vice versa.

**Comment by gorriecoe** [comment]
When is this likely to be released either in 4.2 or 4.3?

**Comment by DorsetDigital** [comment]
FWIW, this just came up on the community Slack channel.  It appears to have been working in 4.1.1 but no longer works in 4.2.1

**Comment by brynwhyman** [comment]
Closing this issue. No points can be reproduced in CMS 4.5.
