### ISSUE TITLE
BUG: weird dot at the end of Folder Name

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-asset-admin#868]
I tried to add a bunch of `test` folders to the Silverstripe demo site and they got a "dot" added to the end of their name. I added a folder "test" ten or so times. 

![image](https://user-images.githubusercontent.com/167154/29207778-7fd3f776-7edb-11e7-8169-0b484fccc511.png)

**Comment by sminnee** [comment]
@robbieaverill so is this fixed, then?
