### ISSUE TITLE
Editing a file in UploadField results in 404

### ISSUE THREAD

**Issue by nickspiel** [silverstripe/silverstripe-asset-admin#869]
I am getting a 404 error when editing and saving files in the `UploadField` in version 4.

**Steps to recreate:**
1. Upload a file to an `UploadField`.
2. Save and publish parent object.
3. Hit the edit button on the image.
4. Hit the save button.
5. A 404 page then appears in the upload field div.

Oddly, this is not an issue for `Images`.

**Comment by maxime-rainville** [comment]
@nickspiel From the date your submitted this issue, I presume this affects SilverStripe 3?

**Comment by ScopeyNZ** [comment]
> @nickspiel From the date your submitted this issue, I presume this affects SilverStripe 3?

> in version 4.

I am pretty sure this is no longer an issue as we probably would've had more complaints if this was broken for the last year!

**Comment by bergice** [comment]
Let me know if this is still an issue, along with what version.
