### ISSUE TITLE
UploadField failing validation for attached files due to size

### ISSUE THREAD

**Issue by p0lar-bear** [silverstripe/silverstripe-asset-admin#871]
Is there a reason that the UploadField validates the file size of a file already uploaded and stored in the database? It seems strange that I'm not allowed to attach an _existing_ file to a DataObject because it's larger than what my server will allow to be uploaded.

My use case is that our IT department copies files onto our webserver running Silverstripe manually after verifying that their contents contain no sensitive information, and then site admins link to these files after a file sync. Our UploadFields are set to not allow uploads anyway, and the production server's post_max_size and upload_max_filesize are set to low values for security reasons.

We're running SS 3.2, and I didn't see any issues open or closed talking about this.

**Comment by maxime-rainville** [comment]
The UploadField in SS4 doesn't have the problem.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
