### ISSUE TITLE
Uncaught ReferenceError: PropTypes is not defined on 1.3.0-rc1 prevents loading of AssetAdmin

### ISSUE THREAD

**Issue by elliot-sawyer** [silverstripe/silverstripe-asset-admin#876]
I have a fresh SS installation with the following dependencies:
```
        "silverstripe/framework": "4.3.0-rc1",
        "silverstripe/cms": "4.3.0-rc1",
        "silverstripe/assets": "1.3.0-rc1",
        "silverstripe/asset-admin": "1.3.0-rc1",
```
I am trying to run SS 4.3.0-rc1 to remove the File Tracking and Link Tracking tabs. If I install rc1 of this module, I get a console error in Chrome and the AssetsAdmin presents a blank screen. Downgrading to `^1.2` fixes it.

Trace below:
```
bundle.js?m=1541561487:1 

Uncaught ReferenceError: PropTypes is not defined
    at Object.15 (bundle.js?m=1541561487:1)
    at t (bundle.js?m=1541561487:1)
    at Object../client/src/components/AnchorSelectorField/AnchorSelectorField.js (bundle.js?m=1541561487:1)
    at t (bundle.js?m=1541561487:1)
    at Object../client/src/boot/registerComponents.js (bundle.js?m=1541561487:1)
    at t (bundle.js?m=1541561487:1)
    at Object../client/src/boot/index.js (bundle.js?m=1541561487:1)
    at t (bundle.js?m=1541561487:1)
    at Object../client/src/bundles/bundle.js (bundle.js?m=1541561487:1)
    at t (bundle.js?m=1541561487:1)
    at bundle.js?m=1541561487:1
    at bundle.js?m=1541561487:1

**Comment by robbieaverill** [comment]
Ah we upgraded to use the external library for React 16, must have missed a spot

**Comment by elliot-sawyer** [comment]
Probably worth mentioning, the Insert Media and Insert From Files modal disappears from TinyMCE as well

**Comment by robbieaverill** [comment]
@elliot-sawyer are you using a custom editor config or OOB?

**Comment by elliot-sawyer** [comment]
OOB, it's a fresh install

**Comment by robbieaverill** [comment]
@elliot-sawyer I can reproduce this by using your composer.json dependencies. Note that when I add them, the other non-listed dependencies get downgraded to 1.2.x:

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 6 updates, 4 removals
  - Removing silverstripe/errorpage (1.3.0-rc1)
Removing web directories for module silverstripe/versioned-admin:
  - Removing silverstripe/versioned-admin (1.1.0-rc1)
  - Removing silverstripe/recipe-cms (4.3.0-rc1)
  - Removing silverstripe/recipe-core (4.3.0-rc1)
  - Updating silverstripe/config (1.0.7-rc1 => 1.0.8):  Checking out ab03d6dc54
  - Downgrading silverstripe/versioned (1.3.0-rc1 => 1.2.2):  Checking out 0bc1d474b1
  - Downgrading silverstripe/admin (1.3.0-rc1 => 1.2.2):  Checking out c2de7cafa7
Exposing web directories for silverstripe-vendormodule silverstripe/admin with method auto:
  - client/dist
  - client/lang
  - thirdparty
  - Downgrading silverstripe/campaign-admin (1.3.0-rc1 => 1.2.2):  Checking out 0c8d62d7ca
Exposing web directories for silverstripe-vendormodule silverstripe/campaign-admin with method auto:
  - client/dist
  - client/lang
  - Downgrading silverstripe/reports (4.3.0-rc1 => 4.2.2):  Checking out 9ec437d033
Exposing web directories for silverstripe-vendormodule silverstripe/reports with method auto:
  - javascript
  - Downgrading silverstripe/siteconfig (4.3.0-rc1 => 4.2.2):  Checking out a75009555e
Writing lock file
Generating autoload files
```

This is what's causing this issue. The workaround is either to use a recipe, or to specify all of your requirements explicitly.

When 1.3.0 is stable it will pull those dependencies instead.

We could look at increasing the minimum constraints for all of the modules that require those dependencies not in your composer.json, e.g. these could be `^1.3@dev`:

```
$ composer why silverstripe/admin
silverstripe/asset-admin     1.3.0-rc1  requires  silverstripe/admin (^1)        
silverstripe/campaign-admin  1.2.2      requires  silverstripe/admin (^1@dev)    
silverstripe/cms             4.3.0-rc1  requires  silverstripe/admin (^1.1@dev)  
silverstripe/reports         4.2.2      requires  silverstripe/admin (^1.0@dev)  
silverstripe/siteconfig      4.2.2      requires  silverstripe/admin (^1)   
```

We could also add `@dev` constraints to each of those requirements above that don't already have them, in order to allow an rc to be installed for example.

**Comment by elliot-sawyer** [comment]
Good spotting, I was avoiding the recipes but I overlooked `silverstripe/admin` since framework pulls it in. From that, I can see it's likely a slightly older version, hence the error. Thanks!

**Comment by elliot-sawyer** [comment]
I only mentioned it in case this release candidate became the stable version with an error that wasn't noticed. I use stable versions and recipes otherwise... I only did it here (from 4.2.2 to 4.3.0-rc1) because I was trying to fix the issue where the Link/File Tracking tabs appear everywhere.

If it doesn't affect people using stable or recipes, it doesn't look like there's anything to fix.
