### ISSUE TITLE
Uploading a non-previewable file from the WYSIWYG editor context has incorrect message padding

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#878]
**Version: SS 4.3.0-rc1** (in CWP 2.2.0-rc1 context)

* Edit a page in the CMS
* Click "Insert from Files" button
* Choose a PDF document and upload it

The "This file type can only be inserted as a link" message has uneven padding:

![image](https://user-images.githubusercontent.com/5170590/48342356-1ce47b80-e678-11e8-936b-dc2f10cab016.png)

Related: #838

**Comment by robbieaverill** [comment]
If you halve the negative top margin here it seems to fix it:

![image](https://user-images.githubusercontent.com/5170590/48345753-92087e80-e681-11e8-97fb-cbe4eaf53ea3.png)

Also in #879

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/silverstripe-asset-admin/pull/1132

**Comment by emteknetnz** [comment]
The linked PR has been merged now
