### ISSUE TITLE
Replace file "save to continue" message has incorrect padding

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#879]
Closely related to #878 

**Version: SS 4.3.0-rc1** (in CWP 2.2.0-rc1 context)

* Upload a file
* Select that file
* Choose "replace" from the more actions menu
* Select a new file

Observe incorrect top padding on the message in the preview window:
![image](https://user-images.githubusercontent.com/5170590/48345090-b1061100-e67f-11e8-84fe-91176d7eb1a6.png)

**Comment by sachajudd** [comment]
**Note:** Looks like this is only happening if there is no thumbnail present. Works correctly if there is a thumbnail for an image or a default file/video/pdf thumbnail.

**Comment by robbieaverill** [comment]
Yeah good point. Reproducible for me by uploading a PDF, opening its details, then replacing it with another PDF.

![image](https://user-images.githubusercontent.com/5170590/82848258-9ed97580-9ea7-11ea-9f6d-ed8d8aa7e97b.png)

**Comment by robbieaverill** [comment]
Related (but not the same): https://github.com/silverstripe/silverstripe-asset-admin/issues/878

**Comment by emteknetnz** [comment]
Linked PR was merged
