### ISSUE TITLE
Right clicking and opening browser inspector triggers drag to select

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#884]
**Version: SS 4.3.0-rc1**

* Go to asset admin
* Right click in the assets list area
* Open browser inspector (or choose something else from the option menu e.g. Print)
* Notice that the "drag to select" state has been enabled

**Comment by ChloeSartorelli** [comment]
This is not the case in CMS 5 or the alpha for 6.
