### ISSUE TITLE
UploadFieldItem title attribute on div.uploadfield-item__error-message

### ISSUE THREAD

**Issue by ivoba** [silverstripe/silverstripe-asset-admin#891]
When the validator returns an error the UploadField renders a red Error kind of button.
This cuts longer error message for design reasons which is fine.
But an additional title attribute with the error message would make it possible to hover over the message and still read the whole string.

Should not be much of deal, what do you think?

**Comment by chillu** [comment]
Do you have a screenshot of the current state, and maybe a mockup of how you'd fix it?

**Comment by ivoba** [comment]
I extended UploadField with a json-schema validation, error messages are a bit longer now.
Current State:
![bildschirmfoto vom 2018-12-12 09-36-46](https://user-images.githubusercontent.com/471254/49857310-89c37080-fdf2-11e8-902e-7bc911d333bb.png)

Improved State:
![bildschirmfoto vom 2018-12-12 09-39-05](https://user-images.githubusercontent.com/471254/49857341-98aa2300-fdf2-11e8-9d34-392628b6cb28.png)

**Comment by robbieaverill** [comment]
Fixed with #900 - thanks @ivoba!
