### ISSUE TITLE
Folders sorting incorrectly across pagination

### ISSUE THREAD

**Issue by scott1702** [silverstripe/silverstripe-asset-admin#893]
## Overview

The fix here https://github.com/silverstripe/silverstripe-asset-admin/pull/844 caused another issue where folders will only appear at the top of the page they're on, not across all pages. E.g. if I have 50 pages of files/folders and I have a folder called 'Uploads', this folder may not appear until page ~45. This has a fairly big impact on the UX of asset-admin as content authors will struggle to find their folders.

## Acceptance Criteria

The below is documenting what already should be there before the regression was introduced.

 * [x] Shows all folders first in default sort
 * [x] Paginates across folders and files
 * [x] Shows folders visually separate from files if both types are on the same page
 * [x] Works with fluent
 * [x] Doesn't show folders first when changing sort order to "recently edited")

## PRs
 - [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/936

**Comment by robbieaverill** [comment]
So I understand that folders used to be shown first, before files, but now that has regressed and is no longer the case. This means that if you have one folder (Uploads) and 45 pages of files, it won't show up until page 45.

If that's the case, I'll triage as a high impact bug/regression

**Comment by chillu** [comment]
There's two ways we could do this. Examples with 50 folders and 10 files

1. Fix the regression

```
page 1: folder 1-20
page 2: folder 21-40
page 3: folder 41-50, files 1-10
```

2. Paul's alternative suggestion for new UI:

```
page 1: folder 1-10, files 1-10
page 1*: folder 1-50, files 1-10
```

We'd need either loading of all folders (cap at 100?), or we need infinite scrolling.

**Comment by tomaszpirc** [comment]
Both solutions have serious drawbacks when handling large assets libraries. Maybe the most intuitive solution would be using for folders the same Treeview that is used for Pages. This would:
- bring more coherence into both sections;
- allow accessing and listing between folders separately from files (avoid both awkward situations from these proposals);
- offer users a familiar interface (used by Wins and OS)

What do you think?

**Comment by dnsl48** [comment]
In my opinion any option will heavily depend on a project workflow.
I believe we have to revert the regression and bring back the original (4.0) behaviour first, then we could make a step back, rethink this, then gradually introduce new functionality or postpone the change until SS5.

**Comment by clarkepaul** [comment]
Just an FYI, this icon was supposed to present a tree view of the folder structure using the multiselect dropdown field. Currently it just links directly to edit the folder which was a temporary thing which never progressed (the edit link was to be at the top of the dropdown – can't find designs).
<img width="214" alt="Pasted_Image_16_04_19__9_49_AM" src="https://user-images.githubusercontent.com/555033/56167855-7c7ef280-602d-11e9-8639-b06cd2fc9527.png">

**Comment by ScopeyNZ** [comment]
I'm pretty sure this was in our pattern-lib at some point but I can't find it now. I don't think it either took you to edit or presented a tree view - I remember it allowing you to edit the folder name in-line.

Hopefully I didn't imagine all of that.

**Comment by clarkepaul** [comment]
Currently in the CMS it takes you to the edit panel, not sure about it being inline editable though?

**Comment by dnsl48** [comment]
> Shows all folders first in default sort (by name asc or desc)

I checked the 4.1 behaviour and that's a bit different.
Basically, "Folders first" only kicks in when there's no manual ordering picked.
If user picks asc or desc for title, then "folders first" doesn't happen anymore.
That doesn't seem to be intentional though, but rather caused by https://github.com/silverstripe/silverstripe-framework/issues/8926

I'm still going to reproduce that original behaviour in sake of backward compatibility.

**Comment by chillu** [comment]
Yep, I've removed the "(by name asc or desc)" from the AC, good catch

**Comment by dnsl48** [comment]
> - Shows folders visually separate from files if both types are on the same page
> -  Doesn't show folders first when changing sort order to "recently edited")

Currently the former AC takes precedence and when files with folders are on the same page, folders go first even with custom ordering.
I'm leaving that behaviour as is.
