### ISSUE TITLE
Alignment of insert media toolbar actions

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#896]
![192_168_3_157_8888_demo-template_admin_assets_-2](https://user-images.githubusercontent.com/8085295/50190607-c3661f80-038e-11e9-93ab-779e0b0e06a8.png)

Small CSS alignment issues and update sort button to be more modern and mobile friendly 
(icon: update to this icon)
![27721211-083cc1e6-5db3-11e7-9a8c-e93c12a079ba](https://user-images.githubusercontent.com/8085295/50190650-f4465480-038e-11e9-83b6-3f06b2b83605.png)

Although on its own its very low impact, it is set to Impact medium, as over a long term small tasks like this, easy build up and start deteriorating the experience and can damage overall perception of product if UX debt is not managed.

**Comment by newleeland** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Review insert file UI, raise any existing issues not captured yet](https://trello.com/c/XeRRjd9i/365-2-review-insert-file-ui-raise-any-existing-issues-not-captured-yet)

**Comment by emteknetnz** [comment]
If we align the buttons then there's an issue with the hover state being "cut off"

![image](https://user-images.githubusercontent.com/4809037/95727862-43cde100-0cd7-11eb-9eb8-2e46cd4f6b12.png)

![image](https://user-images.githubusercontent.com/4809037/95727951-5fd18280-0cd7-11eb-8f7a-cd50bd24a936.png)

We could still align it and have the hover state will "go over", though this may look worse

@sachajudd how would you like to proceed with this?

**Comment by emteknetnz** [comment]
Enhanced in https://github.com/silverstripe/silverstripe-asset-admin/pull/1145
