### ISSUE TITLE
Tabs within Image detail panel breaks in modal

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#899]
![screen shot 2019-01-10 at 10 01 16 am](https://user-images.githubusercontent.com/8085295/50928267-1ed38b00-14bf-11e9-8140-c077759623bc.png)

It appears the addition of **placement** tab makes it too long and is pushing **Used on** tab down.

**Step of reproduce:**
On a page using TinyMCE Click insert image button.
Select an image
Resize browser window to under 1200px wide.

**Comment by emteknetnz** [comment]
Closing this as 'placement' and 'details | permissions | used on' now live in different places

![image](https://user-images.githubusercontent.com/4809037/96533707-d596a900-12ea-11eb-8a79-e41686ad4bd9.png)

Clicking on the new "details" button

![image](https://user-images.githubusercontent.com/4809037/96533730-e0e9d480-12ea-11eb-8964-f2b742b5452b.png)
