### ISSUE TITLE
Image of folder while being dragged into another folder looks broken

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#902]
The folder icon should not scale down to a mini icon when dragged, we can leave it at the standard size.
![Screen Shot 2019-01-18 at 4.05.24 PM.png](https://images.zenhubusercontent.com/596d365561b4ca3b0a74bd86/5472d666-f823-4032-827a-d7052bbb6949)

# Pull Request
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/952

**Comment by maxime-rainville** [comment]
PR has been merged. Looks like this issue has been fixed. If it's not completely fixed, please reopen.
