### ISSUE TITLE
Remove focus state files search that clips text

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-asset-admin#912]
When the down arrow button is pressed it clips the "Advance" text. Makes CMS look broken.

![screen shot 2017-09-11 at 12 38 45 pm](https://user-images.githubusercontent.com/8085295/30256170-bb34ccf8-96fc-11e7-991e-94f91bfa37d3.png)

**Comment by clarkepaul** [comment]
Asset admin has been updated, so this issue is no longer relevant.
