### ISSUE TITLE
Unable to scroll file edit form

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-asset-admin#914]
```
silverstripe/admin                         1.3.0
silverstripe/asset-admin                   1.3.0
```

Likely caused by https://github.com/silverstripe/silverstripe-admin/pull/759, we should add the overflow rule back for this one form. The form fields appear beneath the actions, and it’s not possible to scroll down to reveal the fields at the bottom of the form

<img width="1588" alt="screenshot 2019-02-07 at 11 29 51" src="https://user-images.githubusercontent.com/1655548/52408941-f5148080-2acb-11e9-8b52-a77a8a39e8d6.png">

**Comment by ScopeyNZ** [comment]
🙁 I thought I had a PR here to add it back... 

https://github.com/silverstripe/silverstripe-asset-admin/pull/885

I must've missed a spot?

**Comment by torleif** [comment]
@ScopeyNZ  can confirm, we have the same issue

**Comment by ScopeyNZ** [comment]
There'll be a "quick fix" to just ensure the overflow rule is applied to the form with CSS. I'm not sure why the overflow isn't applied in your case (given #885) but I haven't had a chance to look into this further yet.

**Comment by ScopeyNZ** [comment]
Actually on review it looks like the overflow rule is applied to all fieldsets that appear within `.editor .editor__details` - BEM violations aside, it might make sense that there's an issue on forms that aren't "details". Can you identify what file forms are causing issues for you? PRs welcome!

**Comment by bergice** [comment]
Closing as this issue is resolved. Please open a new issue if there are still issues with other forms.
