### ISSUE TITLE
Error message from server contains extraneous markup 

### ISSUE THREAD

**Issue by gmlnchv** [silverstripe/silverstripe-asset-admin#915]
### Overview

Error messages that come straight from the server are not readable to the CMS user.

One example is PDF files exceeding the specified maximum file size (for the server) seem to have some extraneous markup surrounding the error message.

![screen shot 2019-02-15 at 2 37 57 pm](https://user-images.githubusercontent.com/1403779/52828893-85d40780-312f-11e9-990e-8641c4b65fa0.png)

### Recreation steps
1. Use a project hosted on Silverstripe Cloud (e.g. demo.silverstripe.org)
2. Upload a 13mb image to asset-admin 
3. Observe error

### Acceptance criteria
- Where the error message/ response comes straight from the server, exclude any HTML tags, ensuring the messaging is readable
- Look at the common status codes and create a specific error message, or default to a generic error message
- If any new translation strings are introduced, ensure they're pushed to Transifex

### Notes
- [Similar work has recently been done in the silverstripe/mfa module ](https://github.com/silverstripe/silverstripe-mfa/pull/401/files)

**Comment by robbieaverill** [comment]
Oh, that's probably coming from your web server (apache/nginx)! Is this reproducible on a vanilla installation by posting an enormous file at it? Could you please share some information about the versions you're running as well as any custom config, web server config etc? If you're running nginx especially

**Comment by gmlnchv** [comment]
@robbieaverill you are right - I could only reproduce this on SilverStripe Platform. Fresh SS4 installation doesn't seem to have this :) Should probably close and raise with the Platform instead?

**Comment by robbieaverill** [comment]
@gmlnchv I think you can leave the issue open, but maybe raise a helpdesk issue and reference this GitHub issue in it

**Comment by chillu** [comment]
The frontend logic should be looking at the status code *as well as* the content type of the response. If it's `text/html`, then don't use it. If it's `application/json`, then try to parse it for error messages. If it's `text/plain`, display it. In all cases, the output should be sanitised.

**Comment by gmlnchv** [comment]
> @gmlnchv I think you can leave the issue open, but maybe raise a helpdesk issue and reference this GitHub issue in it

@robbieaverill Still worthwhile raising with the helpdesk or can be fixed here you think?

**Comment by robbieaverill** [comment]
@gmlnchv I would suggest raising a ticket and reference this issue

**Comment by robbieaverill** [comment]
This is still an issue. I replicated earlier today by uploading a 13mb image to asset-admin on demo.silverstripe.org.

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/silverstripe-asset-admin/pull/1138

**Comment by emteknetnz** [comment]
Re-opening, linked PR hasn't been merged yet
