### ISSUE TITLE
Wrong Image in UploadField

### ISSUE THREAD

**Issue by lerni** [silverstripe/silverstripe-asset-admin#919]
In an Element with a has_one Image the Image "cache-hangs" in the CMS, specifically in UploadField. I've added a LiteralField with a Thumbnail and the path beside the UploadField to make the problem better visible. The LiteralField and also the Thumbnail thingy in the Elemental-GF are correct but on the second Element 'BBB' the Thumbnail in UploadField is wrong. It even shows the wrong Image if I click on the edit-eye in the UploadField. Check the short Screencast below.
```
class ElementTextImage extends BaseElement {
  private static $has_one = [
    'Image' => Image::class
  ];
  private static $field_labels = [
    'Image' => 'Bild',
  ];

  private static $owns = [
    'Image'
  ];

  private static $table_name = 'ElementTextImage';

  function getCMSFields() {
    $fields = parent::getCMSFields();

    if ($uploadField = $fields->dataFieldByName('Image')) {
      $uploadField->allowedExtensions = array('jpg', 'png');
      $uploadField->setFolderName('TextImageElement');
      $uploadField->setDescription('min. 1400x1800px');
    }
    $fields->addFieldToTab('Root', LiteralField::create('image-debug', $this->Image()->CMSThumbnail() .'<br>'. $this->Image()->URL), 'Image');

    return $fields;
  }
}
```
![wrong-image](https://user-images.githubusercontent.com/472115/53904500-8d0f7680-4046-11e9-8203-2507665dfcf3.gif)

```
silverstripe/admin                         1.3.2 
silverstripe/asset-admin                   1.3.2 
silverstripe/assets                        1.3.2 
silverstripe/cms                           4.3.2 
silverstripe/config                        1.0.12
silverstripe/framework                     4.3.2 
silverstripe/graphql                       3.0.2 
silverstripe/recipe-cms                    4.3.2 
silverstripe/versioned                     1.3.2 
silverstripe/versioned-admin               1.1.2 
```

**Comment by andreaslindahl** [comment]
I'm having the same problem. This is really bad, since the correct image gets replaced by the cached one when you save the DataObject.

**Comment by andreaslindahl** [comment]
Probably related to https://github.com/silverstripe/silverstripe-asset-admin/commit/69341e86d1efb0ee1fdc2585748021beefd496ac, which was added in Silverstripe 4.3.2. Everything seems to work fine in 4.3.1

**Comment by lerni** [comment]
@andreaslindahl I can confirm downgrading solves the problem. @ScopeyNZ - what do you think?

**Comment by prij** [comment]
I'm also having this issue after upgrading to 4.3.2, it was working fine in 4.3.1. 
Content uploader was very confused.

**Comment by andreaslindahl** [comment]
Yeah, this is a rather big and serious issue, since it makes all pages and DataObject with UploadFields more or less unusable and actually alters and removes content, since the correct image is replaced with the cached image when saving.

**Comment by nfauchelle** [comment]
I ran into this issue today and was about to raise an issue about it.
We upgraded to 4.3.2 at the start of the week and ran into this with people editing pages, images were being changed due to the cached state. Rolling back to 4.3.1 fixes the issue.

@ScopeyNZ - Here is the issue you wanted :)

**Comment by lerni** [comment]
yeah the destructive nature of it makes it problematic and if you downgrade you're running a version with a "High Severity Security Issue" :( Last minor update I've learnd `composer u` is a thing now I'm keen to use it soon again ;)

**Comment by kinglozzer** [comment]
Tentatively upgrading to `impact/critical`, as it’s potentially (silently) “destructive”

**Comment by UndefinedOffset** [comment]
@kinglozzer I wonder if there's a temporary work around that could be added to sites using the Injector API on the client side and essentially overriding the `componentDidMount` to revert 69341e86d1efb0ee1fdc2585748021beefd496ac?

**Comment by ScopeyNZ** [comment]
Hmmmn that commit is probably the issue... I'll take a look at this today.

**Comment by ScopeyNZ** [comment]
I've spent a little time investigating this and I can't seem to reproduce the original problem that was occuring with and without the fix. I'll PR a revert for it for now and re-address whatever was broken before when I can remember/reproduce it.

**Comment by ScopeyNZ** [comment]
PR at #922.

**Comment by kinglozzer** [comment]
https://github.com/silverstripe/silverstripe-asset-admin/pull/922 merged
