### ISSUE TITLE
UploadField max file size validation has no effect for large files

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-asset-admin#925]
Tested with 1.3.3

```php
/** @var Upload_Validator $validator */
$validator = $uploadField->getValidator();
$validator->setAllowedMaxFileSize('1m');
```

I’d expect this to prevent the upload, but it actually allows the file to be uploaded before validation is run server-side. That, while a little frustrating for CMS users who have slow connections, does work for smaller files, however...

If `post_max_size` is set to 10mb, the field is set to 1mb, and the user attempts to upload a 40mb file, they receive a useless error message: a 400 error code and `There has been an error` (or other webserver error message). Error logs show:

> PHP Warning:  POST Content-Length of 40500753 bytes exceeds the limit of 10485760 bytes in Unknown on line 0, referer:

Attempting to upload files via `AssetAdmin` does produce error messages prior to uploading, so client-side validation is obviously possible _somehow_.

### Expected results
- If the set UploadField max file size is exceeded, there is client-side validation alerting the user
- The file is prevented from being uploaded/does not reach the server 

## PRs

 - [x] https://github.com/silverstripe/silverstripe-assets/pull/341
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1017

**Comment by dnsl48** [comment]
Done. Tested in IE11 and Chromium
