### ISSUE TITLE
Null size images are wrongly inlined in GraphQL thumbnail responses

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#930]
When images return a null/zero size during thumbnail generation, they are wrongly inlined into the response, with the assummption that they're small enough for thsi. Since the size couldn't be computed, that's not the case, leading to massive asset admin GraphQL response payloads.

Original report and investigation from @frankmullenger

The responses generated for displaying the image metadata are massive (1-2MB). The reason the responses are massive is because thumbnail images are being inlined into the response:

Probably here:
https://github.com/silverstripe/silverstripe-asset-admin/blob/b4626ed2e629d4ec7c103751ab0c0f6f7d5e438d/code/Controller/AssetAdmin.php#L1221

Which calls here:
https://github.com/silverstripe/silverstripe-asset-admin/blob/5f0bacd05b9319b41c9cc972654a8762c2249d6f/code/Model/ThumbnailGenerator.php#L134

Because of setting here (which shouldn’t be used for large images) and means that protected image thumbnails are inlined:
https://github.com/silverstripe/silverstripe-asset-admin/blob/5f0bacd05b9319b41c9cc972654a8762c2249d6f/code/Model/ThumbnailGenerator.php#L58

## Pull Requests
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/964

**Comment by unclecheese** [comment]
This seems to be a pretty key part of the problem here:

https://github.com/silverstripe/silverstripe-asset-admin/blob/5f0bacd05b9319b41c9cc972654a8762c2249d6f/code/Model/ThumbnailGenerator.php#L116

That always evaluates `false`. The negation is tripping up the way that evaluates. Should use a `<`.

**Comment by chillu** [comment]
🤦‍♂
