### ISSUE TITLE
No way to set default folder for TinyMCE image insert dialog

### ISSUE THREAD

**Issue by MasonD** [silverstripe/silverstripe-asset-admin#933]
There is currently no way to set the default folder for the `TinyMCE_ssmedia` plugin. All the necessary features seem to be there (`InsertMediaModal` has a `folderId` prop which it uses as the default folder), it just is not exposed to the user.

What I mean by this is that there's currently no way to use the Injector to customise the `InsertMediaModal` component that is used by `TinyMCE_ssmedia` in order to use this prop. Despite the fact that `InsertMediaModal` is registered with Injector, `TinyMCE_ssmedia` imports the component directly. It calls [`loadComponent(InsertMediaModal)`](https://github.com/silverstripe/silverstripe-asset-admin/blob/master/client/src/entwine/TinyMCE_ssmedia.js#L15) to wrap the *imported* component, instead of calling `loadComponent('InsertMediaModal')` which would obtain the component from Injector's component factory. Thus, updating `'InsertMediaModal'` with Injector has no impact on the modal rendered when you click on the insert file button on a TinyMCE editor.

This seems like an easy fix: change the `loadComponent` call to passing a string, but I'm unsure about contribution guidelines/process, or if there was other reasoning for loading `InsertMediaModal` in this manner.

**Comment by tractorcow** [comment]
I wouldn't mind if the folder ID could be set via `TinyMCEConfig` on an editor-by-editor basis. tinymce_ssmedia could pick that up, and pass in the default folder to `InjectableInsertMediaModal` couldn't it?

**Comment by tractorcow** [comment]
Implemented at https://github.com/silverstripe/silverstripe-asset-admin/pull/1009
