### ISSUE TITLE
front end links to protected assets don't work when logged in without first visiting a web-page that owns the asset

### ISSUE THREAD

**Issue by Hels666** [silverstripe/silverstripe-asset-admin#937]
Issue:
- direct url links to assets that are visible only to logged in users don't work.

Tested on:
- silverstripe 4.2.4
- chrome, chrome incognito, safari, firefox

Steps to reproduce:
- install new silverstripe 4.2.4 project (no extra modules or custom code)
- upload a file to the assets-admin & set its permissions to logged in users only
- make a note of the url to the file
- visit the website home-page to log in
- try to visit the file's url -> it can't be accessed
- create a new webpage in the cms containing a link to the file's url & publish it
- visit the new webpage but do not click the file link
- in a new tab, try to visit the file's url again -> now it works

**Comment by maxime-rainville** [comment]
That's because you can't actually see a file until `AssetStore::grant()` is called and a grant entry is added to your session.

When you access a page/controller that reference that file you be granted access to see it.

I don't see how we fix this without altering the AssetStore interface.

**Comment by kinglozzer** [comment]
@Hels666 this does sound like you’re describing the same thing as https://github.com/silverstripe/silverstripe-assets/issues/221, so I’m going to close this in favour of that issue. Thanks for raising it!
