### ISSUE TITLE
radio label "undefined" suffix

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/silverstripe-asset-admin#938]
## Version

1.4.0

## Description

![undefined](https://user-images.githubusercontent.com/9313746/56873716-92a69d00-6a88-11e9-9347-a13843e36b48.png)

Here's the broken behat test: https://travis-ci.org/silverstripe/silverstripe-installer/jobs/522590190#L891

The issue is with the label only. I've tested manually that the actual functionality works, and tests are green with the labels changed accordingly.

## PRs
- [x] https://github.com/silverstripe/silverstripe-admin/pull/879

**Comment by robbieaverill** [comment]
It's nice that Behat is picking up this failure even though it's not explicitly testing for it!

**Comment by dnsl48** [comment]
Related https://github.com/silverstripe/silverstripe-admin/pull/854

**Comment by dnsl48** [comment]
the fix goes to 4.4.1
