### ISSUE TITLE
Missing file icon prevents video embed

### ISSUE THREAD

**Issue by elliot-sawyer** [silverstripe/silverstripe-asset-admin#953]
## Affected Version

A freshly generated CWP demo, running SilverStripe (Version - CMS: 4.3.3, CWP: 2.2.3)

## Description

I'm unable to use the WYSIWYG editor to embed a Facebook video because a PHP notice about a missing file is displayed in the Network response. 

## Steps to Reproduce

1. Generate a new CWP demo
2. Find some random Facebook videos, maybe any of these ones:
    a) https://www.facebook.com/brutnature/videos/the-honey-badger-is-not-afraid-of-anything/220639575159714/
    b) https://www.facebook.com/renewsnz/videos/185151292018376/
3. Click the insert media button and enter the URL.
4. Observe the following error:
```
Unexpected token < in JSON at position 0
```
5. This is in the network response, just before the JSON schema:
```
<br />
<b>Notice</b>:  File resources/vendor/silverstripe/asset-admin/client/dist/images/icon_file.png does not exist in <b>/var/www/html/vendor/silverstripe/framework/src/Control/SimpleResourceURLGenerator.php</b> on line <b>90</b><br />
<br />
<b>Notice</b>:  File resources/vendor/silverstripe/asset-admin/client/dist/images/icon_file.png does not exist in <b>/var/www/html/vendor/silverstripe/framework/src/Control/SimpleResourceURLGenerator.php</b> on line <b>90</b><br />
```

**Comment by maxime-rainville** [comment]
It's not specific to the CWP demo. Plain old regular SilverStipe has it as well. It's just a notice, so if you run the site with SS_ENVIRONMENT_TYPE set to "live" it will work because the JSON response won't get an error message in it.

@silverstripe/creative-commoners Shouldn't the CWP demo be running with SS_ENVIRONMENT_TYPE set to "live".

**Comment by robbieaverill** [comment]
@maxime-rainville yes it should, I've raised that here: v

**Comment by tractorcow** [comment]
fix at https://github.com/silverstripe/silverstripe-asset-admin/pull/1031
