### ISSUE TITLE
Drag zone doesn't show as where you click to start dragging

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#954]
**SS 4.4.0** tested in CWP 2.3.0-rc2

In the grid view for asset admin, click and drag to select a couple of files. Notice that the drag zone indicator is nowhere near where you clicked.

Makes it difficult to select files. _Edit_ actually it makes it impossible to select multiple files via drag to select. You can still check them individually to select in bulk.

# Pull Requests
- [x] Deselect previous selection when dragging: https://github.com/silverstripe/silverstripe-asset-admin/pull/956
- [x] Fix drag zone: https://github.com/unclecheese/react-selectable/pull/57
- [x] Update `react-selectable` version in `asset-admin/package.json` once above is merged
- [x] Close https://github.com/unclecheese/react-selectable/issues/52 once above is merged

**Comment by bergice** [comment]
This addresses the drag zone issue, there is also a code fix in there which has not been committed yet: https://github.com/unclecheese/react-selectable/issues/52

The files are still not selectable after fixing the drag zone. `Gallery.handleGroupSelect` simply returns an empty array for `items`.

**Comment by maxime-rainville** [comment]
Only @unclecheese can approve this because it's against his personal account. Shouldn't we take it over, if we're going to rely on it?

**Comment by unclecheese** [comment]
Nice work, everyone!

**Comment by unclecheese** [comment]
Have invited some of you as collaborators.
