### ISSUE TITLE
File permission labels show "undefined"

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#955]
**SS 4.4.0** via CWP 2.3.0-rc2

![image](https://user-images.githubusercontent.com/5170590/59240864-8e5dca00-8c59-11e9-925e-ceda6b2217a0.png)

**Comment by chillu** [comment]
Marking as "impact high" since it's a pretty common UI area and looks very unprofessional

**Comment by dnsl48** [comment]
this is a duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/938 and has been [fixed](https://github.com/silverstripe/silverstripe-admin/pull/879) in 4.4.1
