### ISSUE TITLE
600px default image size is not always the best default, add option for original size

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#961]
When placing an image into the editor the file width is presented at a default of 600px (currently broken in the latest version as per #917). This is fine if the site wants a default of 600px to be used for the majority of the images but this number doesn't consider what the usable space of the page to be, or what the original size of the image was (could be 650px). This results in pixelated images which don't take up the full width of the content area. This becomes more important with responsive views were the size set in desktop might not be as usable at other screen resolutions. 

Issues:
- Badly resized images resulting in pixelation.
- Can't see the original size of the image once the file is placed in the editor (from the editor view) and wouldn't know if the image is being resized larger than the original image.
- It isn't well known that the default size of 600px can be removed (make fields empty) so that the image acts responsively using its original size (typically also using max-width 100% of the usable area within template CSS).

# Acceptance criteria
- [x] Files have the ability to be configured between a "Best fit" and "Original size". The "Best Fit" size should inherit the 600px default from $insert_width (or look to depreciate that functionality?)
- [x] The "Best Fit" option should be selected by default when adding a new file
- [x] The image popover in TinyMCE is updated to include a "Best fit" and an "Original size" option
- [x] The "Best fit" and an "Original size" options are also available in the 'edit file' view
- [x] The alignment options are removed from the image popover, the Edit icon is kept\

# Designs
You can find the new TinyMCE designs under [TinyMCE Edit image](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/folder/components/5c68f96ffb26bb0018525d0a) and the dimensions Best fit / Original designs under [File details](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/folder/components/5d70aad32041c840c590d9cd).

# Notes
- We'll need to have a closer look at what we can get out of the TinyMCE popover. Depending on the outcome, we may need to look at other options.
- Let's also investigate allowing the developer to configure the defaults.
- STRETCH GOAL: allow the size options to be configured to set defaults, e.g small, medium, large

# Pull request
* [ ] https://github.com/silverstripe/silverstripe-framework/pull/9276
* [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/1018
* [ ] silverstripe/silverstripe-admin#965

**Comment by newleeland** [comment]
We potentially could use the popover thats in TinyMCE right now?

![Screen Shot 2019-08-26 at 5 15 24 PM](https://user-images.githubusercontent.com/8085295/63667388-a9d37c80-c827-11e9-9005-e9a794103bb6.png)

**Comment by clarkepaul** [comment]
At the moment the options shown are the text alignment actions, it doesn't show text wrapping options that you get when editing the image. Maybe we can remove those text alignment options from the popover? (img is wrapped in p tags).

So the options would be:
"Best fit" and "Original size", and "Edit". With "Best fit" being selected by default.

In the file placement area I imagine that a toggle to switch between "Best fit" and "Original" also makes sense.

**Comment by purplespider** [comment]
> At the moment the options shown are the text alignment actions, it doesn't show text wrapping options that you get when editing the image. Maybe we can remove those text alignment options from the popover? (img is wrapped in p tags).

![Screenshot from SilverStripe 4.4 showing alignment/edit image popover](http://spdr.me/a9oSxK+)
Yup, presumably these are TinyMCE's default image alignment options, which don't make sense to show in SilverStripe as it has it's own, more comprehensive, alignment options which aren't compatible.

It would be pretty handy to have SilverStripe's 5 different alignment options available as icons in this popover though. But obviously an enhancement request for the future.

> So the options would be:
"Best fit" and "Original size", and "Edit". With "Best fit" being selected by default.

> In the file placement area I imagine that a toggle to switch between "Best fit" and "Original" also makes sense.

Sounds perfect to me! 

Another future enhancement could be to add the ability for developers to add other presets, suitable for that particular website, e.g. "Small" (50px wide), "Medium" (350px wide), "Large" (1200px wide). Which would make it really easy for content authors to set images to consistent sizes.

**Comment by sachajudd** [comment]
I've uploaded some designs into the CMS style guide. You can find the new TinyMCE designs under [TinyMCE Edit image](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/folder/components/5c68f96ffb26bb0018525d0a) and the dimensions Best fit / Original toggle under [File details](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/folder/components/5d70aad32041c840c590d9cd). Let me know if you have any thoughts 🙂

**Comment by purplespider** [comment]
@sachajudd Ace! Looks good to me. My only thought is whether it should say "Original size" rather than just "Original" so that it is absolutely clear what that option does.

**Comment by maxime-rainville** [comment]
This issue has been worked on as part of a larger initiative focused on reducing the experience debt of the SilverStripe CMS.

Thank you for taking the time to raise this issue and/ or provide feedback supporting the implementation.

This is an initiative from the teams maintaining the commercially supported module list. If you're interested to read more about this initiative and keep up with our progress have a look at our [blog post on experience debt](https://www.silverstripe.org/blog/weve-got-experience-debt-in-our-sights).
