### ISSUE TITLE
Wrong FileID when switching between dataobjects

### ISSUE THREAD

**Issue by DimaSupport** [silverstripe/silverstripe-asset-admin#981]
When switching between dataobjects and there is an ajax request made. It puts the wrong FileID in the upload field on the dataobject. 

It saves the FileID of the first (non ajax) visited dataobject in the hidden input. If there is a fileID to save atleast. When you refresh the page it shows the right FileID again.

Ajax visited dataobject:
![hidden-input](https://user-images.githubusercontent.com/5096535/63929407-a4f21100-ca51-11e9-988a-3f8aacb108a9.png)

After refresh:
![hidden-input-correct](https://user-images.githubusercontent.com/5096535/63929651-18941e00-ca52-11e9-80ec-7bbdf8b7dd82.png)

Were using the following modules:

        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1.2",
        "silverstripe/recipe-cms": "4.4.x-dev",
        "silverstripe/googlesitemaps": "^2.1",
        "kinglozzer/metatitle": "^2.0",
        "symbiote/silverstripe-gridfieldextensions": "^3.2",
        "silverstripe/spamprotection": "^3.0",
        "undefinedoffset/silverstripe-nocaptcha": "^2.0",
        "matthiasmullie/minify": "^1.3",
        "gorriecoe/silverstripe-link": "^1.2",
        "gorriecoe/silverstripe-linkfield": "dev-master",
        "silverstripe/lumberjack": "^2.0",
        "colymba/gridfield-bulk-editing-tools": "dev-master",
        "tractorcow/silverstripe-fluent": "^4"

Running on PHP Version 7.2.21

Checked on the following browsers: 

- Chrome Version 76.0.3809.132
- Firefox Version 68.0.2

**Comment by maxime-rainville** [comment]
Can you clarify what you mean by "When switching between dataobjects". Could provide some reproduction steps?

**Comment by DimaSupport** [comment]
Yes of course, I'll try to be more specific next time.

- I click on an entry of the dataobject DownloadProduct on a ModelAdmin.
- The dataobject DownloadProduct has a $has_many relation to the dataobject Download, which is displayed by a GridfieldRecordEditor.
- On the dataobject Download we have a $has_one relation to the File class.
- I click on an entry of the dataobject Download, where a File has been uploaded.
- I go back 1 level by either clicking the back button in the browser, or clicking on the DownloadProduct entry in the breadcrumbs.
- I click on a different entry of the dataobject Download, where a (different) File has been uploaded.
- Here is where I see the FileID of the first visited Download entry.

I hope this clarifies the issue. I'm happy to share some of the code if needed.

**Comment by maxime-rainville** [comment]
I just tried to replicate what you describe with the following code sample and didn't manage to.

It might have been fixed by https://github.com/silverstripe/silverstripe-framework/pull/9072

```php
<?php

use Psr\Log\LoggerInterface;
use SilverStripe\Colorpicker\Forms\ColorPickerField;
use SilverStripe\Core\Injector\Injector;
use SilverStripe\ElementalBannerBlock\Form\BlockLinkField;
use SilverStripe\ORM\DataObject;
use SilverStripe\Admin\ModelAdmin;
use SilverStripe\Versioned\Versioned;
use SilverStripe\Assets\File;

class DownloadProduct extends DataObject
{

    private static $has_many = [
        'Downloads' => Download::class . '.Product'
    ];
}

class Download extends DataObject
{
    private static $has_one = [
        'Product' => DownloadProduct::class,
        'File' => File::class
    ];
}


class DownloadAdmin extends ModelAdmin
{
    private static $managed_models = [DownloadProduct::class];
    private static $url_segment = 'downloads';

}

```

**Comment by DimaSupport** [comment]
Hi, 

We've applied the patch described by sminnee on the [silverstripe/silverstripe-framework#9072](https://github.com/silverstripe/silverstripe-framework/pull/9072#issuecomment-525015048) issue. 
This indeed fixes the problem. 

We also experienced not being able to patch this on 4.4.4, as described by [lekoala](https://github.com/silverstripe/silverstripe-framework/pull/9072#issuecomment-535424354). So we downgraded to 4.4.3 to make it work.

Thank you for your help on the issue.
