### ISSUE TITLE
date displayed is a bit techy

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-asset-admin#990]
![image](https://user-images.githubusercontent.com/167154/64384590-2e28c980-d08a-11e9-9826-93cce1e031c2.png)
Can we change this to something like:

```
Monday 12 June 13:45
```
?

**Comment by robbieaverill** [comment]
cc @silverstripeux

**Comment by clarkepaul** [comment]
Yeah, something must be out there. I wonder if this happened when the optional date format in "Settings/Profile" was removed?
From my understanding, there is a CMS default date format (we should use this), but that format can be changed by developers for their particular project (things might have changed?).

**Comment by robbieaverill** [comment]
I think you're right. Other parts of the asset-admin UI use a format like `May 26, 2020, 12:38 PM`. Assuming that's the standardised format, let's use that instead.

**Comment by robbieaverill** [comment]
Ok I think the reason this particular datetime doesn't use the same format is that it's rendered in React from a raw datetime that comes from GraphQL, whereas the rest of the system's dates are mostly formatted with SilverStripe template helpers etc.

History viewer using moment.js and the current browser's locale to format in this style, so I'll do that too.
