### ISSUE TITLE
Reorder fields in the place file form to be more useful

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#991]
The order of the presented fields seems slightly odd to me for placing a file, they aren't prioritized in order of importance or in a logical order for the person filling out the form. For instance, ALT text is normally only needed if there is no Image Caption (slightly different purpose but you wouldn't want to just double up with the exact text), and Title Attribute generally isn't required if Caption and Alt exist and have done enough of an explanation.

Image presentation is generally the first interest of the admin and fits better to be closer to the image preview. [As per style guide designs](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5d70ab0cd81b4b445753d31b).

The current order of fields:

1. Image preview
2. Alternative text
3. Title attribute
4. Image caption
5. Image alignment
6. Image dimensions

Suggested new order:

1. Image preview
2. Image alignment
3. Image dimensions
4. Image caption
5. Alternative text
6. Title attribute

# PR 
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1004

**Comment by brynwhyman** [comment]
Note, #983 covers further work in this area of asset admin
