### ISSUE TITLE
FIle manager breadcrumbs is backwards

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-asset-admin#992]
silverstripe/asset-admin 1.4.0

The bread crumb in the file manger for nested folders is backwards, e.g.

Root folder > Subfolder level 1 > Subfolder level 2

Will display as

```
<a href="..">Subfolder level 1</a> / <a href="..">Root folder</a> /
<h2>Subfolder level 2</h2>
```

There are two options which would be better

a) Display the container folders left-to-right

```
<a href="..">Root folder</a> / <a href="..">Subfolder level 1</a> /
<h2>Subfolder level 2</h2>
```

b) Display the container folders left-to-right and get rid of the `<h2>` - more intuitive since it looks the most like a file path, and also just the standard way to display a breadcrumb

```
<a href="..">Root folder</a> / <a href="..">Subfolder Level</a> / Subfolder level 2
```

**Comment by brynwhyman** [comment]
I can't recreate this in `silverstripe/asset-admin 1.4.0` or `1.4.2`. Am I missing something?

![file-path](https://user-images.githubusercontent.com/15868440/64495596-25393180-d2f0-11e9-8ca7-3e1c98f47de4.gif)

**Comment by robbieaverill** [comment]
![image](https://user-images.githubusercontent.com/5170590/82848649-591dac80-9ea9-11ea-8a17-82c122556c0f.png)

Looks fine, and no response from OP - closing
