### ISSUE TITLE
Sorting by newest throws js error

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-asset-admin#997]
framework 4.4.1, unsure which version of asset-admin

/admin/assets/

Sort by > Newest

TypeError: _.ReactTestUtils is undefined

**Comment by Cheddam** [comment]
Hey @emteknetnz,

I can't reproduce this issue in a project running SilverStripe Recipe 4.4.3, with 3 files and a folder. Can you provide some additional details on what your assets directory contains, and check if updating to a more recent release resolves the issue?

**Comment by robbieaverill** [comment]
Working correctly in 4.5.1 (via demo.silverstripe.org), and no response from OP, so closing.
